### ISSUE TITLE
swift package describe returns "error: artifact not found for target 'xxx'" for package with binaryTarget

### ISSUE THREAD

**Issue by MarcoEidinger** [apple/swift-package-manager#4327]
### Expected behavior
`swift package describe` parses Swift package with binary targets correctly

### Actual behavior
Message "error: artifcat not found for target 'XXX'"

### Steps to reproduce

1. Download https://github.com/boffaindustries/americanbearthermometer.com
2. Run `swift package describe`. Result: "error: artifact not found for target 'FBSDKCoreKit_Basics'"

Note: `swift package resolve` runs successful. 

### If possible, minimal yet complete reproducer code (or URL to code)

See above

### Swift Package Manager version/commit hash

5.6 (Xcode 13.3)

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
Target: x86_64-apple-macosx12.0
Darwin C02VDF0EHTD6 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

**Comment by MarcoEidinger** [comment]
https://github.com/apple/swift-package-manager/pull/3810 is probably the solution. Need to retest once available in distributed version

**Comment by tomerd** [comment]
you can try to test with a nightly toolchain as well. I see it working with a 5.7 nightly.

**Comment by MarcoEidinger** [comment]
Fixed with Swift 5.7 (Xcode 14) :)
