### ISSUE TITLE
SwiftPM fails to support various target triples

### ISSUE THREAD

**Issue by stevapple** [apple/swift-package-manager#4328]
### Expected behavior

Ideally all targets supported by Swift Driver should be supported by SwiftPM.

### Actual behavior

`Triple` support in SwiftPM (from TSC) is out of sync with that in Swift Driver. For example, the following targets are not available:
- iOS, watchOS, tvOS and their simulators;
- Mac Catalyst;
- `pc` vendor;
- Other platforms with experimental support;
- …

### Steps to reproduce

Take iOS as example, we cannot directly build against iOS through
```
swift build --sdk /path/to/ios/sdk --triple arm64-apple-ios15.4
```
Instead we need:
```
swift build --sdk /path/to/ios/sdk -Xswiftc -target -Xswiftc arm64-apple-ios15.4 -Xcc --target=arm64-apple-ios15.4 -Xcxx --target=arm64-apple-ios15.4
```

The command becomes verbose and less robust, as a change in compiler can easily reject the passed triple flag. 

### If possible, minimal yet complete reproducer code (or URL to code)

_[anything to help us reproducing the issue]_

### Swift Package Manager version/commit hash

`swift-5.6-RELEASE`

### Swift & OS version (output of `swift --version && uname -a`)

Swift 5.6 (bundled in Xcode)

**Comment by peterkos** [comment]
It looks like this is being addressed in https://github.com/apple/swift-package-manager/pull/6828 :eyes:

**Comment by peterkos** [comment]
Oops, correction: iOS got `--triple` support in #6732. Not sure about the other targets :eyes:

**Comment by MaxDesiatov** [comment]
SwiftPM now (as of 5.10) uses the exact same `Triple` under the hood as Swift Driver. IMO this can be closed. Feel free to reopen with more details otherwise.
