### ISSUE TITLE
[SR-14350] Examples at https://swift.org/package-manager/#example-usage use an old tools version

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4444]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14350      |
   |Radar             | rdar://problem/75452546         |
   |Original Reporter | owenvoorhees (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug, Documentation        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1b6ee405d4811c8c3079af2e864c8aa8

  </details>

**Issue Description:**

A couple of examples on this page use a swift-tools-version of 4.0. There have been a lot of PackageDescription API updates since then, so I think they're probably doing more harm than good now

**Comment by sjavora** [comment]
@tomerd I opened https://github.com/apple/swift-org-website/issues/506, since this isn't related to the implementation of SwiftPM. I think this can be closed.
