### ISSUE TITLE
[SR-13980] SwiftPM does not treat headerSearchPath as a target relative path when generating xcodeproj.

### ISSUE THREAD

**Issue by kateinoigakukun** [apple/swift-package-manager#4458]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13980      |
   |Radar             | rdar://problem/72558644         |
   |Original Reporter | @kateinoigakukun      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

$ swift package --version  
Swift Package Manager - Swift 5.3.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b1a28aaedfa4ce21532b7f92dceab770

  </details>

**Issue Description:**

SwiftPM supports to specify custom header directories with .headerSearchPath with target directory relative path. It adds -I options to compiler arguments.

``` java
let package = Package(
    name: "Example",
    dependencies: [],
    targets: [
        .target(name: "Example", cSettings: [
            .headerSearchPath("Headers")
        ]),
    ]
)
```

"swift package generate-xcodeproj" also adds them to HEADER_SEARCH_PATHS, but it just add it as -I./Headers, which is not resolved as target directory relative path.  
I think SwiftPM should set HEADER_SEARCH_PATHS with $(SRCROOT)/Sources/Example/Headers.

One temporary workaround is creating a symbolic link of Sources/Example/Headers in project root dir. (like <https://github.com/swiftwasm/wamr-swift/tree/aa2991edaf43bc6301972fb3d16c731dad71d25c)>

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
