### ISSUE TITLE
[SR-13870] generate-xcodeproj crash on binary targets dependency

### ISSUE THREAD

**Issue by krzyzanowskim** [apple/swift-package-manager#4473]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13870      |
   |Radar             | rdar://problem/71555616         |
   |Original Reporter | @krzyzanowskim      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)  
Target: x86_64-apple-darwin20.1.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug, RunTimeCrash        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 4fa5d3a8ddaf0286801e913712bec2ca

  </details>

**Issue Description:**

If a package has a dependency that comes with a binary target, it no longer can generate an Xcode project for the package.

For example:

    let package = Package(
        name: "Foo",
        platforms: [
            .macOS(.v10_12)
        ],
        dependencies: [
            .package(url: "https://github.com/krzyzanowskim/CryptoSwift.git", .upToNextMinor(from: "1.3.5"))
        ],
        targets: [
            .target(
                name: "Foo",
                dependencies: ["CryptoSwift"])
        ]
    )

 

    ❯ swift package generate-xcodeproj
    Fetching https://github.com/krzyzanowskim/CryptoSwift.git
    Cloning https://github.com/krzyzanowskim/CryptoSwift.git
    Resolving https://github.com/krzyzanowskim/CryptoSwift.git at 1.3.5
    [13280/13280] Downloading binary artifacts
    Fatal error: file Xcodeproj/pbxproj.swift, line 400
    zsh: illegal hardware instruction  swift package generate-xcodeproj

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
