### ISSUE TITLE
[SR-13803] Can’t archive App that uses a swift package with an xcframework

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4481]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13803      |
   |Radar             | rdar://problem/70967526         |
   |Original Reporter | canius (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode Version 12.3 (12C33)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 12         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | @neonichu      |
   |Priority          | Medium      |

   

   md5: c6a1645c0dfce3d2940b09dc2a5c8d57

  </details>

**Issue Description:**

thread:  
<https://developer.apple.com/forums/thread/662247>

reproduce project:  
<https://github.com/canius/ArchiveErrorDemo>

feedback:

<https://feedbackassistant.apple.com/feedback/8932696>

**Comment by neonichu** [comment]
This has been fixed in Xcode 12.5.
