### ISSUE TITLE
[SR-13615] Unable to generate-xcodeproj for package with binary target dependency

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4495]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13615      |
   |Radar             | rdar://problem/69702573         |
   |Original Reporter | Steven0351 (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b4a7ab13fce64a115af93739ea17faa9

  </details>

**Issue Description:**

If a Swift Package has a dependency on a binary target, performing

**Comment by sjavora** [comment]
@tomerd this can be closed since generate-xcodeproj has been removed.
