### ISSUE TITLE
[SR-13360] generate-xcodeproj's xcschemes are modified just by opening the project in Xcode

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4512]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13360      |
   |Radar             | rdar://problem/67361240         |
   |Original Reporter | ille (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963916-4453b725-e631-496f-b5e8-70280272f314.gz)

      
<details>
  <summary>Environment</summary>

Tested with \`swift-package-manager\` \`4d720d6693e9d2059819a101855369ae86387faa\` and Xcode 12 beta.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 205d04030ce6bd6f2d6f19c07c165cff

  </details>

**Issue Description:**

To reproduce, use \`swift package generate-xcodeproj\` to generate an Xcode project, check it in to source control, then open it in Xcode.

Expected results:

Xcode doesn't modify any of the files that have been checked in, as long as you don't actually change any project settings.  Xcode does generate various additional files within the .xcodeproj, but they can be safely ignored.

Actual results:

Xcode leaves alone the \`project.pbxproj\`, but modifies the \`xcscheme\` in a number of ways; see attached diff.

 

On its face this seems like an Xcode problem, but Xcode does not always rewrite the file; it only does so if it actually wants to change the settings.  For example, if I take Xcode's \`xcscheme\` file, modify one of the attributes, and add some random whitespace to the XML, then open the project in Xcode, Xcode preserves not only the modified attribute but also the whitespace.  Thus, in theory it should be possible for SwiftPM to generate an \`xcscheme\` that Xcode will not modify.

**Comment by sjavora** [comment]
@tomerd this can be closed since generate-xcodeproj has been removed.
