### ISSUE TITLE
[SR-13220] Compiling for iOS 8.0, but module <dependency> has a minimum deployment target of iOS 13.5

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4524]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13220      |
   |Radar             | None         |
   |Original Reporter | JonasVautherin (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

macOS 10.15.5

Xcode 11.5 (11E608c)

swift 5.2.4

SPM 5.2.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: d583c0bc9d117d9eafb1524a0a258969

  </details>

**Issue Description:**

For the record, this comes from here: <https://github.com/grpc/grpc-swift/pull/887.>

It seems like \`swift package generate-xcodeproj\` sometimes wrongly guesses that a dependency requires iOS 13.5.

Here are detailed steps to reproduce with SwiftProtobuf:

1\. Create a new project with \`swift package init\`.  
2. In \`dependencies\`, add \`.package(name: "SwiftProtobuf", url: "https://github.com/apple/swift-protobuf.git", from: "1.9.0"),  
3. In \`targets: (dependencies\`, add \`SwiftProtobuf\`)  
4. Run \`swift package generate-xcodeproj\`  
5. Run \`open \<project-name\>.xcodeproj\` to open with Xcode  
6. In the (only) source file "\<project\>.swift", add the line: \`import SwiftProtobuf\`  
7. Try to build for "iPhone 11".

You should see the following error:

\> Compiling for iOS 8.0, but module 'SwiftProtobuf' has a minimum deployment target of iOS 13.5: /path/to/x86_64-apple-ios-simulator.swiftmodule

But SwiftProtobuf does not require iOS 13.5.

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
