### ISSUE TITLE
[SR-13099] [SwiftPM] Xcode project targets from generate-xcodeproj do not include resources

### ISSUE THREAD

**Issue by purpleblues** [apple/swift-package-manager#4528]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13099      |
   |Radar             | rdar://64804615         |
   |Original Reporter | @purpleblues      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963868-6864917a-35ef-4409-b429-2a277aa59e46.gz)

      
<details>
  <summary>Environment</summary>

Xcode Version 12.0 beta (12A6159)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2133e47b3d62a1c99d1be876fcf5cdfb

  </details>

**Issue Description:**

Xcode project targets made by **swift package generate-xcodeproj** do not include any resources associated with the targets

 

**Expected Behavior**: Generated Xcode project target has build phases that handle resources from the package target (e.g. Copy Bundle Resources for plain text files or image files, Compile Sources for Metal shaders)

 

**Current Behavior**: None of the package target resources are handled during the build processes of generated Xcode project target.

**Comment by sjavora** [comment]
@tomerd this can be closed since generate-xcodeproj has been removed.
