### ISSUE TITLE
[SR-12171] SwiftPM Windows support

### ISSUE THREAD

**Issue by aciidb0mb3r** [apple/swift-package-manager#4606]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12171      |
   |Radar             | rdar://problem/59496018         |
   |Original Reporter | @aciidb0mb3r      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: fc970f030fefa310647295169d9d13eb

  </details>

**Issue Description:**

This is an umbrella bug for tracking remaining issues related to Windows support in SwiftPM.

**Comment by compnerd** [comment]
I'm going to close this for now.  I think that we are far enough along that we can close this and address the other issues individually.
