### ISSUE TITLE
[SR-11972] swift package init with Xcode is broken

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4632]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11972      |
   |Radar             | rdar://problem/58455078         |
   |Original Reporter | andreasw (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b23f0db06721f53306c4860f2535c181

  </details>

**Issue Description:**

Initializing a Swift project on macOS 10.15.2 with Swift 5.1.3 and Xcode 11.3 via

\> swift package init --type executable

, then generating an Xcode project with

\> swift package generate-xcodeproj

and trying to compile in Xcode fails with:

\> cannot load module 'swift' as 'Swift'

Renaming the package

\> let package = Package(  
\> name: "bla",

, the target

\> .target(  
\> name: "bla",

and the Sources directory

\> Sources/bla

makes it work.

**Comment by sjavora** [comment]
@tomerd this can be closed since generate-xcodeproj has been removed.
