### ISSUE TITLE
[SR-11804] SPM generate xcodeproj sets custom header search paths wrong

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4645]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11804      |
   |Radar             | rdar://problem/57348899         |
   |Original Reporter | Ybrin (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

❯ swift --version  
Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)  
Target: x86_64-apple-darwin18.6.0

 

macOS version: 10.14.5

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 53019692f235f77d8c483bcda6dfb4c2

  </details>

**Issue Description:**

If {code:swift}headerSearchPath

**Comment by sjavora** [comment]
@tomerd can be closed since `generate-xcodeproj` has been removed.

**Comment by ikesyo** [comment]
As @sjavora pointed out, `generate-xcodeproj` command doesn't exist anymore. Closing.
