### ISSUE TITLE
[SR-11790] 'generate-xcodeproj' fails to provide '.headerSearchPath(…)' includes

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4647]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11790      |
   |Radar             | rdar://problem/57246846         |
   |Original Reporter | --marc (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963541-a2e6d5f7-0482-4066-b221-bbdff3d3d3d7.gz)

      
<details>
  <summary>Environment</summary>

-   macOS Mojave 10.14.6 (18G1012)

-   Xcode 11.2.1 (11B500)

-   Swift 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)

-   swift-tools-version:5.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: a641106cd9052b5772cc527190ed20b8

  </details>

**Issue Description:**

\`generate-xcodeproj\` fails to \`-I\` include from \`CXXSetting.headerSearchPath("Realm/ObjectStore/src")\`

*A build of \`swift package generate-xcodeproj\` generated project is expected to provide includes base on any '.headerSearchPath(…)' just like \`swift build\` does.*

Addition discussion can be found in the GitHub realm/realm-cocoa issue \#6345. (<https://github.com/realm/realm-cocoa/issues/6345>).

****Steps****

1\. An example project is provided as an attachment and as the GitHub repository marc-medley/RealmSPMXcode. (<https://github.com/marc-medley/RealmSPMXcode>).

2\. Build the example project with \`swift build\`. The build should complete with a small number of warning not related to this issue. Observe that the expected includes are present: "-I.../RealmSPMXcode/.build/checkouts/realm-cocoa/Realm/ObjectStore/src". And, later in the log file more instances of "Realm/ObjectStore/src" are present like "-MF '.../RealmSPMXcode/.build/x86_64-apple-macosx/debug/Realm.build/Realm/ObjectStore/src". See attached log-swift_build.txt.

3\. Create an Xcode project with \`swift package generate-xcodeproj\`. Build the generated Xcode project. Observe the absense of "Realm/ObjectStore/src" in the build log. See attached log-generation-xcode-build.txt.

Note that the expressly stated \`headerSearchPath(...)\` incluse are present in step 2 but not in step 3.

**Comment by sjavora** [comment]
@tomerd this can be closed since generate-xcodeproj has been removed.
