### ISSUE TITLE
[SR-11789] 'generate-xcodeproj' does not preserve quotes in '.define(...)'

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4648]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11789      |
   |Radar             | rdar://problem/57246625         |
   |Original Reporter | --marc (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963540-1c3902fa-75cb-444d-a933-d95dcc11eb3c.gz)

      
<details>
  <summary>Environment</summary>

-   macOS Mojave 10.14.6 (18G1012)

-   Xcode 11.2.1 (11B500)

-   Swift 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)

-   swift-tools-version:5.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 79f46a0ff4af4cd4a402e387fc528123

  </details>

**Issue Description:**

\`generate-xcodeproj\` does not preserve quotes in \`.define("REALM_VERSION_STRING", to: ""(coreVersionStr)"")\`.

*\`swift package generate-xcodeproj\` is expected to preserve the expressly stated inner quotes just like \`swift build\` does.*

Addition discussion can be found in the GitHub realm/realm-cocoa issue \#6345. (<https://github.com/realm/realm-cocoa/issues/6345)>

****Steps****

1\. An example project is provided as an attachment and as the GitHub repository marc-medley/RealmSPMXcode. (<https://github.com/marc-medley/RealmSPMXcode)>

2\. Build the example project with \`swift build\`. The build should complete with a small number of warning not related to this issue. Observe that the quotes are preserved in the resulting \`-DREALM_VERSION_STRING="5.23.6"\`.

3\. Create an Xcode project with \`swift package generate-xcodeproj\`. Build the generated Xcode project. Observe that the result does not include the express stated quotes \`-DREALM_VERSION_STRING=5.23.6\`.

Note that the expressly stated inner quotes are not preserved in step 3.

**Comment by sjavora** [comment]
@tomerd this can be closed since generate-xcodeproj has been removed.
