### ISSUE TITLE
[SR-11501] XCTUnwrap is not available for SwiftPM on 5.1

### ISSUE THREAD

**Issue by dduan** [apple/swift-package-manager#4663]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11501      |
   |Radar             | rdar://problem/51959291         |
   |Original Reporter | @dduan      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 11 GM 2

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 6         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | @aciidb0mb3r      |
   |Priority          | Medium      |

   

   md5: 8c288844b10d333b82c348c07f950084

  </details>

**Issue Description:**

When executing tests with {{swift test}} in 5.1, tests that uses XCTUnwrap does not compile, resulting in error {{error: use of unresolved identifier 'XCTUnwrap'}}

**Comment by henrik-dmg** [comment]
@jpsim it does seem that way. Can this issue be closed?
