### ISSUE TITLE
[SR-11235] Package Manager crashes even with non-cyclic dependencies per product.

### ISSUE THREAD

**Issue by YOCKOW** [apple/swift-package-manager#4680]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11235      |
   |Radar             | None         |
   |Original Reporter | @YOCKOW      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift-DEVELOPMENT-SNAPSHOT-2019-07-28-a

-   Apple Swift version 5.1-dev (LLVM 200186e28b, Swift 37abe9d4d3)

-   Swift Package Manager - Swift 5.1.0 (62e96834)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: e2321dad8765380249f0a7d1b4a50398

  </details>

**Issue Description:**

(Although this might be a reduced case of SR-10793, stack traces differ. That is why this is filed separately.)

\[How to reproduce\]

``` java
$ git clone https://github.com/YOCKOW/SwiftPMUncycledCycle
$ cd ./SwiftPMUncycledCycle/PackageA
$ swift build
```

Then, Package Manager crashes.

\[Explanation\]

-   The repository contains two packages: "PackageA" and "PackageB".

-   "PackageA" has two targets: "TargetA1" and "TargetA2"

-   "PackageB" has only one target: "TargetB"

-   "TargetA2" depends on "TargetB"(ProdcutB). "TargetB" depends on "TargetA1"(ProdcutA1).

    -   It is NOT cyclic dependency per product.

**Comment by sjavora** [comment]
@tomerd with Swift 5.9.2 I get the following output, not a crash:

```swift
error: cyclic dependency declaration found: PackageA -> PackageB -> PackageA
```
