### ISSUE TITLE
[SR-10805] The `root` property in PackageModel.Sources struct should use the directory name as on disk

### ISSUE THREAD

**Issue by aciidb0mb3r** [apple/swift-package-manager#4699]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10805      |
   |Radar             | rdar://problem/49648458         |
   |Original Reporter | @aciidb0mb3r      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug, StarterBug        |
   |Assignee          | Nevwild (JIRA)      |
   |Priority          | Medium      |

   

   md5: f50a6a909df06a42211f31452a8f37d6

  </details>

**Issue Description:**

The root property in PackageModel.Sources struct currently gets the target directory's basename from the target name in the package manifest. This is troublesome on case-insensitive filesystems because we're not using the exact path on disk.

**Comment by sjavora** [comment]
@tomerd looks like this was already implemented per this comment: https://github.com/apple/swift-package-manager/issues/4699#issuecomment-1116967951
