### ISSUE TITLE
[SR-10803] Descriptive Help for "swift package init --type" in SPM

### ISSUE THREAD

**Issue by neonichu** [apple/swift-package-manager#4701]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10803      |
   |Radar             | rdar://problem/47951431         |
   |Original Reporter | @neonichu      |
   |Type              | Improvement    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963310-8a7ed31a-239f-47ce-8757-b1bb2cdde982.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Improvement, StarterBug        |
   |Assignee          | Greenaway (JIRA)      |
   |Priority          | Medium      |

   

   md5: d7d16c9fa6fbd23758e129578722fbe0

  </details>

**Issue Description:**

The help for the command line "swift package init" command does not explain the --type option. I have to always go to the online docs on GitHub to remember I can use --type executable. At least --type is not explained in an easy to find place.

**Comment by Overcot** [comment]
@tomerd Maybe then close this issue if it's merged?)
