### ISSUE TITLE
[SR-8824] Users have no way to customize target's Info.plist in SwiftPM

### ISSUE THREAD

**Issue by dduan** [apple/swift-package-manager#4757]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8824      |
   |Radar             | None         |
   |Original Reporter | @dduan      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Improvement, Screened        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 51e69fa30efb16d6a53f4ee10c7e6b15

  </details>

**Issue Description:**

When using \`swift package generate-xcodeproj\`, there's no convenient way to include a Info.plist for an Xcode target.

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
