### ISSUE TITLE
[SR-7825] SwiftPM should consider a target with header files but no sources as a ClangTarget

### ISSUE THREAD

**Issue by aciidb0mb3r** [apple/swift-package-manager#4806]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7825      |
   |Radar             | rdar://problem/34412874         |
   |Original Reporter | @aciidb0mb3r      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 8153b914e535cdeee67774fc66e8763e

  </details>

**Issue Description:**

Currently, swiftpm will complain that there are no source files in the target.

**Comment by k-kohey** [comment]
@aciidb0mb3r 
I make a draft https://github.com/apple/swift-package-manager/pull/6006
If no one has worked on this issue, could you review the changes?
