### ISSUE TITLE
[SR-6514] Using `libSwiftPM` in Xcode Project is blocked by `error: missing required module 'clibc'`.

### ISSUE THREAD

**Issue by norio-nomura** [apple/swift-package-manager#4850]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6514      |
   |Radar             | rdar://problem/67516759         |
   |Original Reporter | @norio-nomura      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164962460-45770a58-4585-44ea-9db8-879b6119fab6.gz)

      
<details>
  <summary>Environment</summary>

swift 4.0.2-RELEASE

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9cba4834f2c2ee99f4952a52b7775c26

  </details>

**Issue Description:**

Example: https://github.com/jpsim/SourceKitten/pull/454  
Build log: <https://circleci.com/gh/jpsim/SourceKitten/757>

**Comment by MaxDesiatov** [comment]
Since libSwiftPM doesn't have a versioned stable API other than in `PackageDescription` and `PackagePlugin` modules, its use outside of toolchain components developed in lockstep (like SourceKit-LSP) is not supported.
