### ISSUE TITLE
[SR-10317] Generated xcodeproj should set MACOSX_DEPLOYMENT_TARGET according to Manifest

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4865]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10317      |
   |Radar             | None         |
   |Original Reporter | matthew_seaman (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: e45d538de4c8c01eefb21e9ba493c70a

  </details>

**Issue Description:**

MACOSX_DEPLOYMENT_TARGET in generated Xcode projects should be set to the minimum macOS version in "platforms" in the Manifest, if applicable. Right now, it is set to 10.10.

This may not be high priority since each individual target has its deployment target properly set.

**Comment by sjavora** [comment]
@tomerd this can be closed since `generate-xcodeproj` has been removed.
