### ISSUE TITLE
[SR-10132] New Command - swift package update-xcodeproj

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4869]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10132      |
   |Radar             | None         |
   |Original Reporter | Sanvean (JIRA User)      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Package Manager    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 56252a3c5e0c8df649ed70fc75feec3a

  </details>

**Issue Description:**

As discussed on this thread:

<https://forums.swift.org/t/swift-package-update-xcodeproj/21794>

When actively developing a server side app in Xcode using SPM it can be a pain adding new package dependencies and then running

1.  swift package update

2.  swift package generate-xcodeproj

when the Xcode project contains scheme configuration information such as runtime args or environment variables as this information is immediately lost and has to be re-input.

A workaround suggestion on the thread is to create a workspace file separate from the Xcode project file, however I think a new alternate command of "update-xcodeproj" that just updates the dependency related information of the Xcode project file would be simpler and a good improvement to the developer experience in Xcode if made available.

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
