### ISSUE TITLE
[SR-9441] Option for preserving environment variables during regeneration of an Xcode project

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4883]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9441      |
   |Radar             | None         |
   |Original Reporter | smartello (JIRA User)      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Package Manager    |
   |Labels            | Improvement, GeneratedXcodeProject, Screened        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 357d0752df0d3778cbfd528b5a830d93

  </details>

**Issue Description:**

\`swift package generate-xcodeproj\` now creates LaunchAction in the schema file (**SchemesGenerator.swift:190**). LaunchAction contains Environment variables if they are defined in the project:

``` java
</BuildableProductRunnable>
<EnvironmentVariables>
  <EnvironmentVariable
    key = "NAME"
    value = "XCode based instance"
    isEnabled = "YES">
  </EnvironmentVariable>
  ...
</EnvironmentVariables>
<AdditionalOptions>
```

These variables are convenient for configuration data like database credentials or verbose level that are overwritten later by docker-compose.yml (or any other tool). With this approach we have a single codeline for every deployment. 

When there is a new dependency in Package.swift, xcode project must be regenerated. Right now the project is generated from scratch. Instead, package manager can check if the xcodeproj (now obsolete) is available and if the schema file contains LaunchAction and EnvironmentVariables inside. If it's the case, it can pass the set of variables to Schema Generator. 

This behavior may be closed by additional flag, e.g. \`swift package generate-xcodeproj --preserve_environment_vars

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
