### ISSUE TITLE
[SR-7073] Support excluding files/folders from Xcode project generation

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4899]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7073      |
   |Radar             | None         |
   |Original Reporter | kdawgwilk (JIRA User)      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Package Manager    |
   |Labels            | Improvement, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 619e0b9302765e64654899180ccaab7e

  </details>

**relates to**:  
* [SR-7074](https://bugs.swift.org/browse/SR-7074) Support including top level files to generated Xcode project  

**Issue Description:**

SPM now adds all root level folders to the generated Xcode project (super helpful!) but it would be nice to be able to exclude some of those folders from being added.  This could be done by passing flags to the \`generate-xcodeproj\` subcommand like so:

 

``` java
$ swift package generate-xcodeproj --exclude resources --exclude travis.yml
```

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
