### ISSUE TITLE
[SR-6805] `generate-xcodeproj` does not honor library `type: .static`

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4900]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6805      |
   |Radar             | None         |
   |Original Reporter | --marc (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164962525-c323392f-1c3e-474f-8c7e-de17a9fb945b.gz)

      
<details>
  <summary>Environment</summary>

Xcode Version 9.2 (9C40b)  
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)  
Apple Swift Package Manager - Swift 4.0.0-dev (swiftpm-13752)

 

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 4         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: eca9f978ea38aeefedb1abc9ce116c45

  </details>

**Issue Description:**

When a library is expressly declared \`type: .static\` in the library's Package.swift manifest, then it seems that one should reasonably expect \`swift package generate-xcodeproj\` to generate an Xcode project which preserves the library as static through out the build process.

**Example**

The following two Swift Manager Packages (SPM) packages are both attached to this issue and also available on GitHub:

1.  Static Library Depedency: \`TinkerEvalStaticLib\` ([https://github.com/VaporExamplesLab/TinkerEvalStaticLib)](https://github.com/VaporExamplesLab/TinkerEvalStaticLib)  used \`swift package init --type library\` as the starting point.

2.  Command Line Executable: \`TinkerEvalStaticCli\` ([https://github.com/VaporExamplesLab/TinkerEvalStaticCli)](https://github.com/VaporExamplesLab/TinkerEvalStaticCli) used \`swift package init --type executable\` as the starting point.

\`TinkerEvalStaticLib\` has one simple function and is expressly set to a type \`.static\` in Package.swift.

*TinkerEvalStaticLib.swift*

``` none
public class TinkerEvalStaticLib {
    public static func printSomething() -> String {
        let s = "Library says, 'Hello.'"
        print(s)
        return s
    }
} 
```

*Package.swift*

``` none
…
products: [
  .library(name: "TinkerEvalStaticLib", 
           type: .static, // expressly set to be a static library
           …
```

\`TinkerEvalStaticCli\` is also simple and has the static library \`TinkerEvalStaticLib\` as a dependency.

*main.swift*

``` none
import TinkerEvalStaticLib
let _ = TinkerEvalStaticLib.printSomething() 
```

*Package.swift*

``` none
…
name: "TinkerEvalStaticCli",
dependencies: [
  .package(
    url: "git@github.com:VaporExamplesLab/TinkerEvalStaticLib.git",
        .branch("master") ),
],
…
```

**Observation**

1\. In the \`TinkerEvalStaticCli\` directory, \`swift build\` will create a standalone relocatable, statically linked executable.

``` none
prompt> ./TinkerEvalStaticCli_spm 
Library says, 'Hello.'
```

 

2\. However, the Xcode project created with \`swift package generate-xcodeproj\` creates a dynamically linked executable that requires the separate library.

``` none
prompt> ./TinkerEvalStaticCli_xc 
dyld: Library not loaded: @rpath/TinkerEvalStaticLib.framework/Versions/A/TinkerEvalStaticLib
Referenced from: /Users/…/./TinkerEvalStaticCli_xc
Reason: image not found
Abort trap: 6
```

**Comment by krin-san** [comment]
https://github.com/apple/swift-package-manager/pull/5748 removed `generate-xcodeproj` command. I guess this issue could be closed, but without an alternative way to generate Xcode project from Package manifest projects like https://github.com/unsignedapps/swift-create-xcframework will stop working with the next Swift release.

**Comment by neonichu** [comment]
Yep, agreed, let's close it.
