### ISSUE TITLE
[SR-6193] new options' request for `swift package generate-xcodeproj`

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#4933]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6193      |
   |Radar             | None         |
   |Original Reporter | rockywei (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0b223e9b121b7ea14593a85d6c78814e

  </details>

**Issue Description:**

Hi, I think these option flags would be useful:

``` java
swift package generate-xcodeproj -p $PWD -e key1=value1 -e key2=value2
```

where \`-p $PWD\` is equal to \`customWorkingDirectory = "$PROJECT_DIR" \` in Xcode and \`-e\` means to store an environmental variable to the settings as well.

currently, I have to use my DIY script:  
<https://github.com/PerfectSideRepos/XcodeInit>

This would be very useful for testing purposes.

Thank you.

**Comment by sjavora** [comment]
@tomerd since `generate-xcodeproj` has been removed, this no longer make sense.

**Comment by ikesyo** [comment]
As @sjavora pointed out, `generate-xcodeproj` command doesn't exist anymore. Closing.
