### ISSUE TITLE
[SR-5470] "swift generate xcodeproj" fails when Package.swift specifies sub-dependency

### ISSUE THREAD

**Issue by stephencelis** [apple/swift-package-manager#4981]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5470      |
   |Radar             | None         |
   |Original Reporter | @stephencelis      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 4 (Xcode 9 beta 3 snapshot)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug, GeneratedXcodeProject        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f23c7a30376a69730fb136443099ff2f

  </details>

**Issue Description:**

If a "Package.swift" file specifies a sub-dependency as a dependency of one of the "targets" dependencies, the following error spits out when one runs "swift generate xcodeproj":

> error: The product dependency 'SubDependency' was not found.

The "Package.resolved" still includes "SubDependency", though, it's included in ".build/checkouts", and "swift build" appears to work just fine.

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
