### ISSUE TITLE
[SR-4900] XCode Project generated by SPM doesn't include system-module package headers correctly for C++ module

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#5017]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4900      |
   |Radar             | None         |
   |Original Reporter | spencerkohan (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164962107-a4acce76-6763-446c-bf77-9f192f5a8446.gz)

      
<details>
  <summary>Environment</summary>

macOS 10.12.4  
XCode 8.3  
Apple Swift version 3.1 (swiftlang-802.0.48 clang-802.0.38)  
Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: a63a6806dac3c5eeac17f00eafa93078

  </details>

**Issue Description:**

When implementing a package which contains c++ sources which depend on a system-module package, a generated XCodeProject does not correctly include the library headers for use in the c++ sources.

Steps to reproduce:

1\. Clone the demo project

$ git clone <https://github.com/spencerkohan/SPMGenerateXCodeprojBug>  
$ cd SPMGenerateXCodeprojBug

2\. Building from the command line succeeds:

$ swift build  
Compile Swift Module 'App' (1 sources)  
Linking ./.build/debug/App

3\. Generate an Xcode project:

$ swift package generate-xcodeproj

Building the target "App" in this project fails with the error " 'btBulletCollisionCommon.h' file not found" (see attached screenshot)

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
