### ISSUE TITLE
[SR-4265] [SwiftPM] `CURRENT_PROJECT_VERSION` should be defined on `generated-xcodeproj`

### ISSUE THREAD

**Issue by norio-nomura** [apple/swift-package-manager#5063]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4265      |
   |Radar             | None         |
   |Original Reporter | @norio-nomura      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift-3.1-DEVELOPMENT-SNAPSHOT-2017-03-15-a  
swift-DEVELOPMENT-SNAPSHOT-2017-03-15-a

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 4         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | @abertelrud      |
   |Priority          | Medium      |

   

   md5: 97683a9b8e492477adf93de57734c991

  </details>

**relates to**:  
* [SR-12926](https://bugs.swift.org/browse/SR-12926) provide a way to get the SHA of the current package in code  

**Issue Description:**

SwiftPM generates \`Info.plist\` to library targets on generating Xcode project.  
Those \`Info.plist\` contain \`CFBundleVersion\` key as following:

``` java
  <key>CFBundleVersion</key>
  <string>$(CURRENT_PROJECT_VERSION)</string>
```

But, generated Xcode project does not have settings that defines \`CURRENT_PROJECT_VERSION\`, so framework target is build with emtpty \`CFBundleVersion\` key in their \`Info.plist\`.  
If those frameworks are used on Apps, those are rejected on validation by iTunes connect with following error:

> This bundle Pyload/\*\*\*\***.app/Frameworks/**\*\*\*.framework is invalid.  
> The Info.plist file is missing the required key: CFBundleVersion.

Xcode's template for framework target has settings that defining \`CURRENT_PROJECT_VERSION\` as \`1\` for avoiding such scenario.

SwiftPM should define \`CURRENT_PROJECT_VERSION\` as \`1\` on generating Xcode project as same as Xcode's template does.

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
