### ISSUE TITLE
[SR-3737] Unable to link system archives in generated Xcode project

### ISSUE THREAD

**Issue by harlanhaskins** [apple/swift-package-manager#5126]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3737      |
   |Radar             | None         |
   |Original Reporter | @harlanhaskins      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

macOS 10.12.4

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 6c2fc5247b76dc9b7ebb3f4c47c5845a

  </details>

**Issue Description:**

When trying to compile a fresh clone of LLVMSwift, it fails with the following warning for each archive: `ld: warning: ignoring file /usr/local/Cellar/llvm/3.9.1/lib/libLLVMCodeGen.a, file was built for archive which is not the architecture being linked (arm64)`

Steps to reproduce:

`brew install llvm` (or have `llvm-config` 3.9.x in your `PATH`)  
`git clone https://github.com/trill-lang/LLVMSwift.git`  
`swift utils/make-pkgconfig.swift`  
`swift package generate-xcodeproj`  
Attempt to build the project

**Comment by ikesyo** [comment]
`generate-xcodeproj` command doesn't exist anymore. Closing.
