### ISSUE TITLE
[SR-710] Generate XCTestCaseProvider entries on Linux

### ISSUE THREAD

**Issue by mxcl** [apple/swift-package-manager#5320]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-710      |
   |Radar             | rdar://problem/32453385         |
   |Original Reporter | @mxcl      |
   |Type              | Improvement    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961160-d4991ca3-a3c7-4101-bb8b-598864429fbd.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 6         |
   |Component/s       | Package Manager, XCTest    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: d49557eb297404f7997ff4b6bf1a55f5

  </details>

**Sub-Tasks**:  
* [SR-1613](https://bugs.swift.org/browse/SR-1613) Require blocks runtime when compiling SourceKit on Linux  
* [SR-1639](https://bugs.swift.org/browse/SR-1639) [SourceKit] Add in-process implementations of sourcekitd functions only defined for XPC  

**is blocked by**:  
* [SR-1676](https://bugs.swift.org/browse/SR-1676) Build SourceKit on Linux  

**duplicates**:  
* [SR-32](https://bugs.swift.org/browse/SR-32) Find way to make allTests required / audited on OS X  

**Issue Description:**

To test on Linux XCTestCase entries must conform to the protocol XCTestCaseProvider.

This means mostly mac developers probably won't bother making their tests run on Linux, which is not ideal.

XCTestCaseProvider will exist until Swift has reflection support on Linux, so we should try to generate these entries on Linux for now in the PM.

Use the AST to extract XCTestCase classes and their test functions, generate a source, add it to the test module.

Also generate an XCTMain for the full package suite.

This feature depends on me landing testing support (hopefully today).

**Comment by MaxDesiatov** [comment]
IIUC this was resolved for some time now with test discovery available for XCTest via index store on non-Darwin platforms.
