### ISSUE TITLE
createBuildCommands mystery line

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-package-manager#5504]
This line in the [plugins guide](https://github.com/apple/swift-package-manager/blob/main/Documentation/Plugins.md#implementing-the-build-tool-plugin-script) is a bit mysterious and looks awfully like something that swallows bugs.  Can a comment be added that explains why it's the right thing to do?

```swift
        guard let target = target as? SourceModuleTarget else { return [] }
```

Thanks

**Comment by Kyle-Ye** [comment]
> This line in the [plugins guide](https://github.com/apple/swift-package-manager/blob/main/Documentation/Plugins.md#implementing-the-build-tool-plugin-script) is a bit mysterious and looks awfully like something that swallows bugs. Can a comment be added that explains why it's the right thing to do?
> 
> ```swift
>         guard let target = target as? SourceModuleTarget else { return [] }
> ```
> 
> Thanks

I used to have the same question as you. Maybe you can check some context here to get the answer. https://forums.swift.org/t/pitch-amend-se-0303-plugin-api-to-use-main-for-plugin-entry-point/51250/20

**Comment by dabrahams** [comment]
Thanks, I might get around to that, but in the meantime I want the plugins guide to clear up its own mysteries.

**Comment by Kyle-Ye** [comment]
> Thanks, I might get around to that, but in the meantime I want the plugins guide to clear up its own mysteries.

+1. Maybe @abertelrud could see this feedback and improve it in the future.

**Comment by dabrahams** [comment]
@neonichu exactly how does that change address the request I'm making for the plugins guide to explain that line?  It still looks like something that would swallow bugs, if the return statement is ever actually executed.
