### ISSUE TITLE
Indexing is not getting disabled when creating build description

### ISSUE THREAD

**Issue by parthv21** [apple/swift-package-manager#5579]
### Description

I work on the Amazon Flex delivery app. We use SPM with over 100 different packages, made by different teams. We have a couple of issues with SPM related to package resolution and build times. We had a discussion with Apple engineers David and Artem during WWDC22 open hour lab. They asked us to open issues with SPM for the issues we are seeing. 

### Expected behavior

Indexing should be disabled when creating build description.

### Actual behavior

Our build gets slowed down and stuck on phase create build description for 40-50 mins when indexing is enabled. As a workaround we disable indexing and that speeds up the build. But then we lose all the benefits of indexing. The build times are better on M1 Macs but still the issue is there. 

### Steps to reproduce

I am not sure if the scale of our app causes this issue. We have 100 packages that depend on each other in a complicated graph. With a complex app like this, to reproduce the issue all you have to do is try to build the app with indexing enabled and you will see the build stuck.

### Swift Package Manager version/commit hash

SPM 5.6

### Swift & OS version (output of `swift --version && uname -a`)

```
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0
Darwin f4d488949cc9.ant.amazon.com 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
```

**Comment by neonichu** [comment]
This is an issue in Xcode's build system, already tracked by rdar://91362310, so I am going to close this.
