### ISSUE TITLE
SwiftPM Build Tools are built for target when cross compiling

### ISSUE THREAD

**Issue by colemancda** [apple/swift-package-manager#5588]
### Description

When cross compiling a Swift package using `swift build --destination destination.json` invocation, the SwiftPM plugins are built for host architecture while the build tools the plugin uses are incorrectly cross compiled for the target architecture.

### Expected behavior

Build tools that Plugins depend on should be built for host platform and not target platform.

### Actual behavior

Build tools are being built for target platform.

```
error: command Generate Bluetooth Company Identifier Definitions failed: unable to spawn process '/__w/Bluetooth/Bluetooth/.build/armv7-unknown-linux-gnueabihf/release/GenerateBluetooth' (Exec format error)
[3/6] Generate Bluetooth Company Identifier Definitions
```

### Steps to reproduce

1. Make a Swift package with plugins
2. Attempt to cross compile using `--destination` option

### Swift Package Manager version/commit hash

5.7.1

### Swift & OS version (output of `swift --version && uname -a`)

Ubuntu 20.04 (Official Swift Docker image)
```
$ swift --version
Swift version 5.7.1 (swift-5.7.1-RELEASE)
Target: x86_64-unknown-linux-gnu
```

**Comment by abertelrud** [comment]
rdar://95123262

**Comment by colemancda** [comment]
Just ran into this again 

```
[60/68] Linking SwiftRustTool
[100](https://github.com/MillerTechnologyPeru/swift-rust-example/actions/runs/3600532335/jobs/6065280400#step:6:101)
error: command Compile Rust failed: unable to spawn process '/__w/swift-rust-example/swift-rust-example/.build/armv7-unknown-linux-gnueabihf/debug/SwiftRustTool' (Exec format error)
[101](https://github.com/MillerTechnologyPeru/swift-rust-example/actions/runs/3600532335/jobs/6065280400#step:6:102)
[61/68] Compile Rust
```

https://github.com/MillerTechnologyPeru/swift-rust-example/actions/runs/3600532335/jobs/6065280400

**Comment by neonichu** [comment]
I was pretty sure that this has been resolved and, indeed, in current `main` this is resolved.
