### ISSUE TITLE
unable to override package

### ISSUE THREAD

**Issue by Zeropointer11** [apple/swift-package-manager#5647]
### Description

Hi i have currently on my build server the following issue can some one help me?.

```
Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ./project.xcworkspace -scheme project -derivedDataPath ./derivedData -disableAutomaticPackageResolution

User defaults from command line:
    IDEDerivedDataPathOverride = [project Dir]/derivedData
    IDEPackageOnlyUseVersionsFromResolvedFile = YES
    IDEPackageSupportUseBuiltinSCM = YES

Resolve Package Graph
unable to override package 'CryptoService' because its identity 'cryptoservice' doesn't match override's identity (directory name) 'cryptoservice'unable to override package 'SecureStore' because its identity 'securestore' doesn't match override's identity (directory name) 'securestore'
```

i found the log line here but i am missing the absolute path of the package locations to identify why the locations are different.
https://github.com/apple/swift-package-manager/blob/6e798dc29cfa643100a275648228a1baa5d3175b/Sources/Workspace/Workspace.swift#L1958

### Swift & OS version (output of `swift --version && uname -a`)

XCode 13.4.1

swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: x86_64-apple-macosx12.0
Darwin [hostname] 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

**Comment by neonichu** [comment]
Not 100% sure about this scenario, but I could see this being fixed by https://github.com/apple/swift-package-manager/pull/5550 potentially. 

Could you try out Xcode 14 beta with your project?

**Comment by Zeropointer11** [comment]
Sorry for the late reply but after a long time i finally could test it with the new Xcode 14 beta 5
```
swift-driver version: 1.62.3 Apple Swift version 5.7 (swiftlang-5.7.0.123.8 clang-1400.0.29.50)
Target: x86_64-apple-macosx12.0
```
and it worked thanks for your help
