### ISSUE TITLE
Make referencing a non-existent plugin an error

### ISSUE THREAD

**Issue by tonyarnold** [apple/swift-package-manager#5650]
### Description

If I have no resources associated with a target, but subsequently generate resources using a build tool plugin, the `Bundle.module` extension is not added to my target, meaning that I cannot easily access the resources I've just added.

### Expected behavior

If I generate resources as part of a build tool plugin, that should have the same effect as adding resources via the Package description - I should be able to use `Bundle.module`.

### Actual behavior

`Bundle.module` is not added to my target, meaning that I cannot easily refer to generated resources that the build tool plugin has added to my target.

### Steps to reproduce

Please see the attached sample: [Tools.zip](https://github.com/apple/swift-package-manager/files/9089759/Tools.zip)

### Swift Package Manager version/commit hash

Swift 5.7.0

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.60 Apple Swift version 5.7 (swiftlang-5.7.0.120.1 clang-1400.0.28.1)
Target: arm64-apple-macosx13.0
Darwin Tonys-MBP.localdomain 22.0.0 Darwin Kernel Version 22.0.0: Tue Jun 28 20:46:36 PDT 2022; root:xnu-8792.0.134.131.2~1/RELEASE_ARM64_T6000 arm64

**Comment by tomerd** [comment]
@neonichu I _think_ you looked into this before?

**Comment by neonichu** [comment]
Yah, this works. 

It looks like plugin products aren't available inside the package itself, similar to library products, so the plugin reference should be

```plugins: [ .plugin(name: "GenerateLocalizedStringsTool"),  ]```

This situation is made a little more confusing by the fact that there is no error for referring to a non-existing plugin. 

(note: the given plugin is also hitting the known `async` codegen bug for me, might be fine on non-x64_64)

**Comment by neonichu** [comment]
I think we should clean up the confusion here by at least making this an error -- potentially we could also allow referring to plugin's with their product's name as well? Retitled the issue accordingly.

**Comment by tonyarnold** [comment]
@neonichu even after I'd fixed the plugin name reference to be "GenerateLocalizedStringsTool", the `module` accessor still isn't available. Is this due to the async bug that you linked to earlier?
