### ISSUE TITLE
Failure with build tool plugin on Windows

### ISSUE THREAD

**Issue by ericsink** [apple/swift-package-manager#5656]
### Description

AFAICT, all build tool plugins fail on Windows because PackagePlugin.dll cannot be found.

FWIW, related thread on the forums:

https://forums.swift.org/t/known-case-of-a-working-build-tool-plugin-on-windows/58825

### Expected behavior

The plugin should execute

### Actual behavior

![dll_not_found](https://user-images.githubusercontent.com/3877005/178778172-af4e2250-1e01-4ef6-9718-6b5b81a3f03c.png)

### Steps to reproduce

1. Start with https://github.com/abertelrud/swiftpm-buildtool-plugin-examples
2. cd "Example 1 - SwiftGen"
3. swift build

In this particular case, what *should* happen is that the plugin should be compiled and executed, and then we should get some kind of failure due to the fact that binary target is Linux specific.  But it never gets that far.  FWIW, I've tried lots of combinations wherein I add an actual Windows exe for the binary target, as well as cases where I change the plugin itself to be simpler.  None of that matters because the plugin never actually launches.

### Swift & OS version (output of `swift --version && uname -a`)

I've tried this with 5.6.2, 5.7 snapshot, and main snapshot.  They all give the same result.  OS is Windows 11.

**Comment by compnerd** [comment]
Looking at apple/swift-installer-scripts:
https://github.com/apple/swift-installer-scripts/blob/main/platforms/Windows/devtools-amd64.wxs#L149-L151

I think that this is the result of a simple oversight: we need to adjust `Path` when executing the plugin on Windows as we do tests: https://github.com/apple/swift-package-manager/blob/57af70f2f9f5645514a9ce8e6279995c701333b0/Sources/Commands/Utilities/TestingSupport.swift#L133
