### ISSUE TITLE
Can't import the same plugin in 2 dependent packages

### ISSUE THREAD

**Issue by danyf90** [apple/swift-package-manager#5671]
### Description

We have a package defining a build tool plugin that we would like to add to the targets of all our packages (for example, to run SwiftLint on build)

### Expected behavior

We can add the build tool plugin to all our packages

### Actual behavior

An error is received when trying to open/build a package depends on a package using the plugin:
```
error: 'packagea': product 'Sample' required by package 'packagea' target 'PackageA' not found in package 'SPMPlugins'.
```

### Steps to reproduce

1. Download the [attached sample](https://github.com/apple/swift-package-manager/files/9132394/PluginError.zip)
2. `cd PackageA && swift build` works correctly
3. `cd PackageB && swift build` fails with error `error: 'packagea': product 'Sample' required by package 'packagea' target 'PackageA' not found in package 'SPMPlugins'.`

### Swift Package Manager version/commit hash

Tested with both Xcode 13.4 and 14.0b3

### Swift & OS version (output of `swift --version && uname -a`)

```
swift-driver version: 1.60 Apple Swift version 5.7 (swiftlang-5.7.0.120.1 clang-1400.0.28.1)
Target: arm64-apple-macosx12.0
Darwin Danieles-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```

**Comment by tomerd** [comment]
cc @neonichu @abertelrud

**Comment by neonichu** [comment]
Yah, looks like this is the same as https://github.com/apple/swift-package-manager/pull/5649

**Comment by danyf90** [comment]
@tomerd @neonichu I still have the same issue in Xcode 14 beta 5, is it expected that the change is not included yet?
