### ISSUE TITLE
Swift package resource bundle accessor isn't concurrency-safe

### ISSUE THREAD

**Issue by OneSadCookie** [apple/swift-package-manager#5689]
### Description

The swift package resource bundle accessor `Bundle.module` is generated as 
```swift
extension Bundle {
    static var module: Bundle = { ... }()
}
```
When compiled with -strict-concurrency=complete, the compiler complains about uses of it:
> warning: Reference to static property 'module' is not concurrency-safe because it involves shared mutable state

The use of `var` in the declaration seems erroneous; it's not intended to be mutable. It could be changed to `let`.

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.7.0

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.60 Apple Swift version 5.7 (swiftlang-5.7.0.120.1 clang-1400.0.28.1)
Target: arm64-apple-macosx12.0
Darwin LM-YQ027RFQ63 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

**Comment by neonichu** [comment]
We're tracking this issue internally already under rdar://94565594

**Comment by kkk669** [comment]
#5736 and #5737 should fix this.

**Comment by neonichu** [comment]
Yah that is true, thanks @kkk669
