### ISSUE TITLE
Trouble when debugging build of ObjC package: `error: no such module 'PackageDescription'`

### ISSUE THREAD

**Issue by ncooke3** [apple/swift-package-manager#5705]
### Description

I am trying to better understand how SPM builds an ObjC package and would like to debug the SPM source code while doing so.

I've followed the CONTRIBUTING.md guide to get set up for local development. I've created a simple ObjC Swift package and am trying to use my local, cloned copy of SPM to build it.

While I can build a simple Swift project just fine, I can't get a ObjC package to build.

### Expected behavior

I expected the ObjC package to build when pointing to it (as a launch argument in the scheme definition) while running the `swift-build` scheme. 

### Actual behavior

I get the following error in the console:

```console
Invalid manifest
/Users/nickcooke/Developer/ObjcPackage/Package.swift:4:8: error: no such module 'PackageDescription'
```

Note that the ObjC package builds fine when running `swift build` in it's directory.

### Steps to reproduce

1. Create a simple ObjC package using Swift Package manager.
    My project's `Package.swift` looks like:

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/36927374/182413141-7a1de1cd-09e9-465b-a712-0053a24fec68.png">

2. Navigate to your local copy of Swift Package Manager and open the `Package.swift` in Xcode.
3. Select the `swift-build` scheme
4. Edit the scheme to pass the following argument on launch:
```console
--package-path /path/to/ObjcPackage 
```
5. Run the scheme.

I'm getting the follow error in the console.
```console
Invalid manifest
/Users/nickcooke/Developer/ObjcPackage/Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
```

### Swift Package Manager version/commit hash

5275f3789028f4faee7ccaa8012129ef678a1402

Tip of `main` from July ~21

### Swift & OS version (output of `swift --version && uname -a`)

```console
swift-driver version: 1.60 Apple Swift version 5.7 (swiftlang-5.7.0.120.1 clang-1400.0.28.1)
Target: x86_64-apple-macosx12.0
```

**Comment by neonichu** [comment]
Did you previously build the "SwiftPM-Package" scheme?

**Comment by ncooke3** [comment]
Thanks for looking @neonichu. I don't recall but am not 100% sure. Should I build it?

**Comment by neonichu** [comment]
Yah, you basically always have to build that scheme first, because it builds the PackageDescription library.

**Comment by ncooke3** [comment]
Thanks @neonichu! That worked 🎉 

Do you have an explanation as for why I was able to successfully build a Swift-only package without first building the `SwiftPM-Package` scheme?

**Comment by ncooke3** [comment]
Also, what do you think about me adding a note [here](https://github.com/apple/swift-package-manager/blob/main/CONTRIBUTING.md#using-xcode-easiest) to clarify that one should build the `SwiftPM-Package` scheme before  running other schemes?

**Comment by neonichu** [comment]
We cache the results of manifest evaluation, so it could be that we considered the cached results as valid and didn't end up needing the PackageDescription library.

Adding a note about this sounds good to me, thanks.

**Comment by ncooke3** [comment]
Gotcha, thanks!
