### ISSUE TITLE
Neither local `.netrc` nor `--netrc-file` are honored

### ISSUE THREAD

**Issue by MPLew-is** [apple/swift-package-manager#5730]
### Description

Support for local `.netrc` was added in #3790, but I'm not able to get that working on Mac or Linux - might be user error though. However, providing an explicit `--netrc-file` also does not work which is very surprising since it's a documented option.

Moving the same `.netrc` file back to `~/.netrc` works seamlessly.

### Expected behavior

1. Providing a local `.netrc` should pull credentials from that file

2. Explicitly providing a `--netrc-file` option should read from that specified file (should also work on `swift build` in my opinion, but it's only documented for `swift package`)

3. Moving that same `.netrc` back to `~/.netrc` should not fix the issue (indicating the credentials themselves are fine)

### Actual behavior

1. Local `.netrc` is not honored
```
$ ls -la
drwxr-xr-x  20 mplewis  staff   640 Aug 16 14:31 .
drwxr-xr-x  48 mplewis  staff  1536 Aug 15 13:56 ..
drwxr-xr-x   5 mplewis  staff   160 Aug 16 14:31 .build
drwxr-xr-x  16 mplewis  staff   512 Aug 16 14:22 .git
-rw-r--r--   1 mplewis  staff   431 Jul  7 17:44 .gitignore
-rw-------   1 mplewis  staff    66 Aug 16 14:23 .netrc
-rw-r--r--   1 mplewis  staff  6131 Aug 13 01:46 Package.resolved
-rw-r--r--   1 mplewis  staff  1753 Aug 13 01:45 Package.swift
-rw-r--r--   1 mplewis  staff  2063 Aug 13 03:23 ReadMe.md
drwxr-xr-x   3 mplewis  staff    96 Jun 23 04:23 Sources
$ swift package update    
Fetching https://github.com/[redacted] from cache
Skipping cache due to an error: Couldn’t fetch updates from remote repositories:
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
error: Failed to clone repository https://github.com/[redacted]:
    Cloning into bare repository '/Users/mplewis/[redacted]/.build/repositories/[redacted]-617999aa'...
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
Fetched https://github.com/[redacted] (0.81s)
```

2. Explicit `.netrc` is not honored
```
$ swift package --netrc-file "$(pwd)/.netrc" update
Fetching https://github.com/[redacted] from cache
Skipping cache due to an error: Couldn’t fetch updates from remote repositories:
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
error: Failed to clone repository https://github.com/[redacted]:
    Cloning into bare repository '/Users/mplewis/[redacted]/.build/repositories/[redacted]-617999aa'...
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
Fetched https://github.com/[redacted] (0.62s)
```

3. Moving `.netrc` back to home directory fixes all problems:
```
$ mv .netrc ~/.netrc
$ swift package update
Fetching https://github.com/[redacted] from cache
Fetched https://github.com/[redacted] (0.93s)
Creating working copy for https://github.com/[redacted]
Working copy of https://github.com/[redacted] resolved at [redacted]
```

### Steps to reproduce

1. Put a local `.netrc` in your package root (with no `~/.netrc` file existing)
2. Attempt to `swift package update`/`swift build`, with or without specifying the path explcitly via `--netrc-file`

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.6.0 (from `swift package --version`)

### Swift & OS version (output of `swift --version && uname -a`)

Mac:
```
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: x86_64-apple-macosx12.0
Darwin [redacted] 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64
```

Linux:
```
Swift version 5.6.2 (swift-5.6.2-RELEASE)
Target: x86_64-unknown-linux-gnu
Linux 43e76e19b213 5.10.109-0-virt #1-Alpine SMP Mon, 28 Mar 2022 11:20:52 +0000 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by neonichu** [comment]
I think the local .netrc / `--netrc-file` are specifically for registry dependencies and fetching binary artifacts today and they're not being passed to git invocations. cc @tomerd

**Comment by tomerd** [comment]
that is correct, these files are explicitly for http operations. git operations should be managed via standard git utilities and configuration files.

**Comment by MPLew-is** [comment]
@tomerd thanks for the clarification - given the confusion I had, can this be documented somewhere? The `--netrc-file` option description would lead me to believe it impacted everything SPM was doing.

**Comment by tomerd** [comment]
@MPLew-is not that I am aware. perhaps a new article in the documentation folder?
