### ISSUE TITLE
SPM (and Xcode) fails to download binary artifact from the JFrog Artifactory platform

### ISSUE THREAD

**Issue by richardtop** [apple/swift-package-manager#5752]
### Description

Given a binary-based package where the binary stored at a remote location and the repository is used only to store the `Package.swift` package manifest like this, similar to this one: https://github.com/PSPDFKit/PSPDFKit-SP/blob/master/Package.swift

```
// swift-tools-version:5.3
 
import PackageDescription
 
let package = Package(
    name: "OpenSSL",
    platforms: [
        .iOS(.v9),
        .macOS(.v10_15)
    ],
    products: [
        .library(
            name: "OpenSSL",
            targets: ["OpenSSL"]),
    ],
    targets: [
        .binaryTarget(
            name: "OpenSSL",
            url: "https://jenkins.com/job/OpenSSL-XCFramework/8/artifact/Frameworks/OpenSSL.xcframework.zip",
            checksum: "ac987a9c798a9c89a8c798c6a8c7a68c8768ec8768c768d787c8a768768c7"),
    ]
)
```
everything works fine... Until I change the URL to artifactory:
`https://artifactory.domain.com/artifactory/openssl-spm-generic-local/OpenSSL.xcframework.zip`

Then I'm getting the following error in Xcode or when running `swift build`:

> error project: failed downloading 'https://artifactory.domain.com/artifactory/openssl-spm-generic-local/OpenSSL.xcframework.zip' which is required by binary target 'OpenSSL': badResponseStatusCode(403)

Still, I'm able to download the very same artifact with curl:

> curl -o OpenSSL.xcframework.zip https://artifactory.domain.com/artifactory/openssl-spm-generic-local/OpenSSL.xcframework.zip

>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 22.0M  100 22.0M    0     0  3480k      0  0:00:06  0:00:06 --:--:-- 4998k

Opening the same link with the browser also downloads the artifact successfully

### Expected behavior

Package resolved and installed successfully when the URL in the Package.swift manifest is an artifactory URL.

### Actual behavior

Getting an error 
> error project: failed downloading 'https://artifactory.domain.com/artifactory/openssl-spm-generic-local/OpenSSL.xcframework.zip' which is required by binary target 'OpenSSL': badResponseStatusCode(403)

Alternatively, I might get the following error:
> error project: failed downloading 'https://artifactory.domain.com/artifactory/openssl-spm-generic-local/OpenSSL.xcframework.zip' which is required by binary target 'OpenSSL': badResponseStatusCode(401)

i.e. the status code can be either 401 or 403

even though the file is accessible without any authentication and can be downloaded with both the web browser and via the `curl` command.

### Steps to reproduce

1. Have a `generic-local` repository on Artifactory with a zipped XCFramework uploaded 
2. Create a Git-based repository with the binary package definition. E.g. similar to https://github.com/PSPDFKit/PSPDFKit-SP/blob/master/Package.swift and pointing to the artifactory xcframework URL
3. Try installing that package in an empty project and get an error
4. Replace an url in the package manifest to some other (non-artifactory URL) and the issue is now resolved, the package is being installed properly.

### Swift Package Manager version/commit hash

Xcode 13.4.1, Xcode 14.0 Beta 6, neither work

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0
Darwin *********** 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64

**Comment by MikePendo** [comment]
@richardtop 
one of our colleagues has the same issue, how did u resolve it?

**Comment by richardtop** [comment]
I think I've removed `.netrc` file completely and any mention of artifactory from there, so it started working.
