### ISSUE TITLE
SwiftPM requires librarian to be installed before it can build anything

### ISSUE THREAD

**Issue by finagolfin** [apple/swift-package-manager#5761]
### Description

This was introduced by #5720, which moved detecting the archiver executable from inside of llbuild to SPM. This has always been kind of a mess with SPM, with llbuild always grabbing whatever archiver was in the path. This didn't crop up much unless you were building the rare Swift package that had a static library and happened not to have a binutils package installed in your system.

However, [trunk SPM now won't build anything without an archiver included in the Swift toolchain or system path](https://github.com/buttaface/swift-android-sdk/runs/8225511990?check_suite_focus=true#step:6:6396), which is too strict. This is particularly an issue because the Swift toolchain doesn't ship with an archiver: I just checked when debugging this issue and was surprised to find that the official builds don't include `llvm-ar`.

The Swift compiler itself is much better on this issue, as [you can supply an alternate `-tools-directory` flag where it should look for an archiver, as done for Android](https://github.com/apple/swift/blob/main/docs/Android.md#2-compiling-helloswift-to-run-on-an-android-device). I just ran a variant of that compiler command and confirmed it uses the NDK llvm-ar:
```
> ./swift-5.6.3-RELEASE-ubuntu20.04/usr/bin/swiftc -tools-directory /home/butta/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin
-target aarch64-unknown-linux-android24 -sdk android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/sysroot
-resource-dir swift-5.6.3-android-aarch64-24-sdk/usr/lib/swift swift/test/Interpreter/Inputs/lto/module1.swift
-emit-library -static -v
...
/home/butta/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar crs libmodule1.a /tmp/TemporaryDirectory.yREHfG/module1-1.o
```
However, I see no flag to do the same with SPM, whereas [I could always pass the `-tools-directory` I want to SPM with the extra swiftc flags before](https://github.com/buttaface/swift-android-sdk/blob/45a56fcc752514b7521b6def4ba7a546c4a7c28e/android-aarch64.json#L11). With SPM itself checking for an archiver now, it errors before that compiler flag is ever used. I worked around this issue on my Android CI by [adding the NDK `llvm-ar` to my system path](https://github.com/buttaface/swift-android-sdk/commit/bcec0251beb986e6b57fcbb8fbd2fb44573af7b9#diff-76992bc322b65ab94f299c05ba3cbd8b3ab2e32ebfdde6db5adba70fa9f5a26aR68).

There are various ways to fix this: my preference would be to start shipping `llvm-ar` with the Swift toolchain and make that the default archiver we use.

### Expected behavior

Don't require `ar` or `llvm-ar` to be installed before building any Swift package, particularly since most won't use it.

### Actual behavior

`error: toolchain is invalid: could not find llvm-ar`

### Steps to reproduce

1. Make sure binutils is not installed.
2. Try to build any Swift package.

I realize that binutils is listed as a dependency of the Swift toolchain on linux, but when cross-compiling for other platforms and supplying your own archiver, as I'm doing for Android, it shouldn't be required that a system archiver be installed.   

### Swift Package Manager version/commit hash

Tested with the September 5 trunk snapshot

### Swift & OS version (output of `swift --version && uname -a`)

September 5 trunk snapshot running on Ubuntu 20.04 x86_64

**Comment by tomerd** [comment]
cc @compnerd @abertelrud

**Comment by tomerd** [comment]
we can roll back https://github.com/apple/swift-package-manager/pull/5720 if necessary, but I'd like to see what @compnerd thinks as he wanted this change to fix things on Windows.

**Comment by buttaface** [comment]
This is a bit of a corner case, so no need to revert #5720. We should put some thought into how we handle this though, and do something to at least soften this new requirement before the 5.8 branch.

**Comment by compnerd** [comment]
We already have the dependency on `ar` for things like swift-syntax which is now being built as part of the toolchain itself.  I think that adjusting the path is reasonable, though an alternative approach would be to set the `AR` environment variable.  Packaging `llvm-ar` is completely reasonable and something that we should do though.
