### ISSUE TITLE
Using moduleAliases can break resolution of older package dependencies

### ISSUE THREAD

**Issue by jaysenmarais** [apple/swift-package-manager#5762]
### Description

When using a moduleAlias for a Swift Package target dependency, resolution of unrelated dependencies in the package can fail.

For example `moduleAlias`ing [swift-algorithms v0.2.1](https://github.com/apple/swift-algorithms/blob/0.2.1/Package.swift) whilst also depending upon [aepsdk-core-ios v3.3.1](https://github.com/adobe/aepsdk-core-ios/blob/3.3.1/Package.swift) will cause `swift package update` to fail. 

In this case, removing the `moduleAlias` OR removing the `aepsdk-core-ios` dependency will cause the same manifest to update successfully. 

[aepsdk-core-ios v3.3.1](https://github.com/adobe/aepsdk-core-ios/blob/3.3.1/Package.swift) uses `swift-tools-version:5.1` and therefore references its sub-dependencies by names other than their repository names, which may be relevant.

### Expected behavior

I expect to be to use moduleAlias and reference older repositories (like [aepsdk-core-ios v3.3.1](https://github.com/adobe/aepsdk-core-ios/blob/3.3.1/Package.swift)) then successfully run `swift package update`

### Actual behavior

`swift package update` returns error _"error: 'aepsdk-core-ios': product 'AEPRulesEngine' required by package 'aepsdk-core-ios' target 'AEPCore' not found."_ in this case

### Steps to reproduce

1. Initialise a new SPM package `ModuleAliasBug`
2. Paste the following into the newly created `ModuleAliasBug/Package.swift`

```swift
// swift-tools-version:5.7
import PackageDescription
let package = Package(
    name: "ModuleAliasBug",
    products: [.library(name: "ModuleAliasBug", targets: [ "ModuleAliasBug" ])],
    dependencies: [
        .package(url: "https://github.com/adobe/aepsdk-core-ios.git", exact: "3.3.1"), // comment this line and `update` works
        .package(url: "https://github.com/apple/swift-algorithms.git", exact: "0.2.1")
    ],
    targets: [
        .target(
            name: "ModuleAliasBug",
            dependencies: [
                .product(
                    name: "Algorithms", 
                    package: "swift-algorithms"
                    , moduleAliases: ["Algorithms": "Alias"] // OR comment this line and `update` works
                )
            ]
        ),
    ]
)
```

3. Run `swift package update` for the new `ModuleAliasBug` package

Or as a script:
```swift
mkdir ModuleAliasBug
cd ModuleAliasBug
swift package init
cat <<\EOT>Package.swift
// swift-tools-version:5.7
import PackageDescription
let package = Package(
    name: "ModuleAliasBug",
    products: [.library(name: "ModuleAliasBug", targets: [ "ModuleAliasBug" ])],
    dependencies: [
        .package(url: "https://github.com/adobe/aepsdk-core-ios.git", exact: "3.3.1"), // comment this line and `update` works
        .package(url: "https://github.com/apple/swift-algorithms.git", exact: "0.2.1")
    ],
    targets: [
        .target(
            name: "ModuleAliasBug",
            dependencies: [
                .product(
                    name: "Algorithms", 
                    package: "swift-algorithms"
                    , moduleAliases: ["Algorithms": "Alias"] // OR comment this line and `update` works
                )
            ]
        ),
    ]
)
EOT
swift package update
```

### Swift Package Manager version/commit hash

5.7 (Xcode 14.0 RC)

### Swift & OS version (output of `swift --version && uname -a`)

```
swift --version
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0

uname -a
Darwin *********** 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
```

**Comment by tomerd** [comment]
cc @elsh

**Comment by JacksonUtsch** [comment]
Looks like I'm having the same issue here

**Comment by elsh** [comment]
Thanks for the bug report. rdar://104768426 has been filed to track this.

**Comment by waterskier2007** [comment]
Is there any update on this? It seems to still be an issue.

**Comment by neonichu** [comment]
I wasn't actually aware of this GH issue, but separately discovered the issue again. It's been fixed in https://github.com/apple/swift-package-manager/pull/6793 very recently.
