### ISSUE TITLE
Resolving goes in an endless loop with specific packages

### ISSUE THREAD

**Issue by azarovalex** [apple/swift-package-manager#5763]
### Description

At Mapbox, we develop most of our libraries in Open Source and we've been distributing them using SPM for a couple of years already. Usually, everything goes very smoothly, but we found out that specific versions of packages result in endless resolving with both Xcode and `swift build`.

These can be reproduced with these two versions for example, even in an empty `swift package init` project:

```
.package(url: "https://github.com/mapbox/mapbox-navigation-ios.git", from: "2.8.0-beta.2"),
.package(url: "https://github.com/mapbox/mapbox-search-ios.git", from: "1.0.0-beta.33")
```

Building SPM from sources reproduces the issue, and PubGrupResolver goes into an endless cycle.

### Expected behavior

SPM should either resolve packages or show an error if they are not compatible.

### Actual behavior

Both CLI command `swift build` and Xcode stop responding and go into an endless loop.

### Steps to reproduce

1) Create an empty project with `swift package init`
2) add these specific dependencies, no need to actually depend on them in targets:
```
.package(url: "https://github.com/mapbox/mapbox-navigation-ios.git", from: "2.8.0-beta.2"),
.package(url: "https://github.com/mapbox/mapbox-search-ios.git", from: "1.0.0-beta.33")
```
3) Try to open Package.swift in Xcode or build the project with `swift build`

### Swift Package Manager version/commit hash

5b88aef25fd3adee5505e990f846f9de424b6742 (latest on main rn)

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0

Darwin FVFG62GJQ05P 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64

**Comment by azarovalex** [comment]
@tomerd I see you've been working a lot on the PubGrub resolver itself, can you take a look?

**Comment by SDGGiesbrecht** [comment]
If you (fork into experimental repositories and) tag versions without the beta suffix, does the same dependency tree work? I ask because my initial gut instinct says the version set logic might be ruling something out but failing to mark it as such and thus retrying over and over. (I have never seen this happen before, but I have never used beta suffixes, and they have specialized behaviour when used with version ranges.)

**Comment by tomerd** [comment]
cc @neonichu

**Comment by neonichu** [comment]
I fixed one instance of this in https://github.com/apple/swift-package-manager/pull/5725, there might be additional bugs in `VersionSetSpecifier` around pre-release identifiers.

I think it could also be worthwhile to make the resolver more robust against getting into endless loops, right now it seems actually pretty easy to get into such states.

**Comment by Overcot** [comment]
@azarovalex I tried reproducing your problem, but encountered 401 error
```
failed downloading 'https://api.mapbox.com/downloads/v2/mapbox-common/releases/ios/packages/23.2.0-beta.1/MapboxCommon.zip' which is required by binary target 'MapboxCommon': badResponseStatusCode(401)
failed downloading 'https://api.mapbox.com/downloads/v2/search-core-sdk/releases/ios/packages/0.63.0/MapboxCoreSearch.xcframework.zip' which is required by binary target 'MapboxCoreSearch': badResponseStatusCode(401)
failed downloading 'https://api.mapbox.com/downloads/v2/mobile-maps-core/releases/ios/packages/10.10.0-beta.1/MapboxCoreMaps.xcframework-dynamic.zip' which is required by binary target 'MapboxCoreMaps': badResponseStatusCode(401)
failed downloading 'https://api.mapbox.com/downloads/v2/mobile-navigation-native/releases/ios/packages/121.0.0/MapboxNavigationNative.xcframework.zip' which is required by binary target 'MapboxNavigationNative': badResponseStatusCode(401)
failed downloading 'https://api.mapbox.com/downloads/v2/mapbox-events-ios/releases/ios/packages/1.0.10/MapboxMobileEvents.zip' which is required by binary target 'MapboxMobileEvents': badResponseStatusCode(401)
fatalError
```

Are your dependencies available for everybody without vpn or some kind of auth?

**Comment by azarovalex** [comment]
This 401 error is actually a good sign, it means that SPM successfully resolved the versions and started downloading binary artifacts.
I forgot to mention that you'd need a private token in `~/.netrc` to download binaries, but it's actually not needed, because the bug used to be during resolving stage.

I just checked that it works on my machine with the latest Xcode, to be honest it's still not clear if it was a fix in the SPM itself, or new releases of packages are not affected by the bug.

For now let's close the ticket, if I'll find stumble upon something similar I'll create a more isolated example and open a new issue.
