### ISSUE TITLE
Time to graduate PKG_CONFIG_PATH to a command-line option?

### ISSUE THREAD

**Issue by buttaface** [apple/swift-package-manager#5815]
### Description

The `PKG_CONFIG_PATH` environment variable is used to [specify alternate paths to search for pkg-config `.pc` files](https://github.com/apple/swift-package-manager/blob/17b3ad89e78cc322e96adcbfc0478a86b92d401a/Sources/PackageLoading/PkgConfig.swift#L34), which is useful when building packages against alternate sysroots, eg for cross-compilation. Strangely, SPM does not check the alternate sysroot specified by the `--sdk` flag, which is what I pass to this environment variable again anyway.

This is now [relevant to SPM itself, since it recently began looking for SQLite3 this way in trunk](https://github.com/apple/swift-package-manager/commit/239f3178b8f7f2463a7754d2a802535a9832d320#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR173), so I had to modify my Android CI to start passing in the path to a cross-compiled SQLite3 for Android when cross-compiling SPM, buttaface/swift-android-sdk@f36e045.

**Comment by neonichu** [comment]
I think both checking the SDK and having an additional CLI option would make sense.

**Comment by buttaface** [comment]
@MaxDesiatov, any progress on this? I can take it over if you're busy with other stuff.

**Comment by MaxDesiatov** [comment]
Thanks for the ping, let me have a quick look.

**Comment by MaxDesiatov** [comment]
I'd assume we want to keep the existing handling of `PKG_CONFIG_PATH` env var for compatibility?

**Comment by neonichu** [comment]
> I'd assume we want to keep the existing handling of PKG_CONFIG_PATH env var for compatibility?

Yes, we should. It is also something that is generally supported by pkg-config tooling, so it might make things just work in certain scenarios where people have already set this.

**Comment by torarnv** [comment]
I don't suppose there's a way to pass this when building inside Xcode? 🤞🏻
