### ISSUE TITLE
Cannot use plugin targets from external Packages

### ISSUE THREAD

**Issue by schwa** [apple/swift-package-manager#5824]
### Description

I want to use this SPM plugin in my Package: https://github.com/iKenndac/localized-strings-symbols

The author's instructions seem totally reasonable:

> SPM Packages
>
> First, add the package to your dependencies list:

…
dependencies: [
    .package(url: "https://github.com/iKenndac/localized-strings-symbols.git", branch: "main")
],
…

> Then, add the dependency and the plugin to your target(s):

…
    .target(
        name: "MyCoolPackage",
        dependencies: [.product(name: "Generate Strings File Symbols", package: "localized-strings-symbols")],
        plugins: ["Generate Strings File Symbols"]
    ),
…

Unfortunately when I add the dependency to my package and the plugins line to my target I get this error:

```
swift build
Fetching https://github.com/iKenndac/localized-strings-symbols.git from cache
Fetched https://github.com/iKenndac/localized-strings-symbols.git (0.72s)
Creating working copy for https://github.com/iKenndac/localized-strings-symbols.git
Working copy of https://github.com/iKenndac/localized-strings-symbols.git resolved at main
error: 'test': no plugin named 'Generate Strings File Symbols' found
```

It seems plug-ins are not available when pulled in from a remote package?

Do all plugins need to be declared and defined locally?

**Comment by schwa** [comment]
(Also filed as https://github.com/iKenndac/localized-strings-symbols/issues/1)

**Comment by neonichu** [comment]
This is how you can refer to an external plugin product:

```
.executableTarget(
            name: "Test",
            plugins: [.plugin(name: "Generate Strings File Symbols", package: "localized-strings-symbols")]

        )
```
