### ISSUE TITLE
SPM - Target Dependency Condition ignored for .target dependencies

### ISSUE THREAD

**Issue by gpfister** [apple/swift-package-manager#5866]
**Describe the bug**

I have a package which holds my Cloud API (built on Firebase). I have multiple apps (macOS, iOS) which uses this API, shared as a single package. I'm now trying to build a watchOS companion App, and some of the Firebase API is not provided, namely the Analytics. So I split my code into multiple libraries (inside the same package), and user condition: .when(platforms: [.iOS, .macOS]) so that I can only included dependencies (Analytics is a behind the scene piece, not really something I manipulate within the app).

However, the condition is ignored, it tries to build this target which fails because the framework is missing for watchOS.

**To Reproduce**

Here's a swift package example:

```swift
import PackageDescription

let package = Package(
    name: "OSKCloudKit",
    platforms: [.iOS(.v15), .macOS(.v12), .watchOS(.v8)],
    products: [
        .library(
            name: "OSKCloudAnalytics",
            targets: ["OSKCloudAnalytics"]
        ),
        .library(
            name: "OSKCloudAuth",
            targets: ["OSKCloudAuth"]
        ),
        .library(
            name: "OSKCloudCore",
            targets: ["OSKCloudCore"]
        ),
        .library(
            name: "OSKCloudModel",
            targets: ["OSKCloudModel"]
        ),
        .library(
            name: "OSKCloudServices",
            targets: ["OSKCloudServices"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/firebase/firebase-ios-sdk.git", .upToNextMajor(from: "9.2.0")),
    ],
    targets: [
        .target(
            name: "OSKCloudAnalytics",
            dependencies: [
                .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk"),
                .product(name: "FirebaseCrashlytics", package: "firebase-ios-sdk"),
            ]
        ),
        .target(
            name: "OSKCloudAuth",
            dependencies: [
                .target(name: "OSKCloudAnalytics", condition: .when(platforms: [.iOS, .macOS])),
                .target(name: "OSKCloudModel"),
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
            ]
        ),
        .target(
            name: "OSKCloudCore",
            dependencies: [
                .product(name: "FirebaseAppCheck", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
                .product(name: "FirebaseFirestore", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
                .product(name: "FirebaseFunctions", package: "firebase-ios-sdk"),
                .product(name: "FirebaseStorage", package: "firebase-ios-sdk")
            ]
        ),
        .target(
            name: "OSKCloudModel",
            dependencies: [
                .product(name: "FirebaseFirestoreSwift", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
            ]
        ),
        .target(
            name: "OSKCloudServices",
            dependencies: [
                .target(name: "OSKCloudAnalytics"),
                .target(name: "OSKCloudModel"),
                .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk"),
                .product(name: "FirebaseFirestore", package: "firebase-ios-sdk"),
                .product(name: "FirebaseFunctions", package: "firebase-ios-sdk"),
                .product(name: "FirebaseStorage", package: "firebase-ios-sdk")
            ]
        ),
        .testTarget(
            name: "OSKCloudKitTests",
            dependencies: [
                "OSKCloudModel",
                "OSKCloudServices",
            ]
        ),
    ]
)
```

When building OSKCloudAuth on iOS device, it works, on watchOS device it fails:

/Users/xxxxxxxx/Library/Developer/Xcode/DerivedData/ios-oskey-dev-azwwbbesmdjzuvbwptqniydxopne/SourcePackages/artifacts/firebase-ios-sdk/FirebaseAnalytics.xcframework:1:1: While building for watchOS Simulator, no library for this platform was found in '/Users/gpfister/Library/Developer/Xcode/DerivedData/ios-oskey-dev-azwwbbesmdjzuvbwptqniydxopne/SourcePackages/artifacts/firebase-ios-sdk/FirebaseAnalytics.xcframework'.

**Expected behavior**

The target OSKCloudAuth has a dependency on OSKCloudAnalytics:

```swift
        .target(
            name: "OSKCloudAuth",
            dependencies: [
                .target(name: "OSKCloudAnalytics", condition: .when(platforms: [.iOS, .macOS])),
                .target(name: "OSKCloudModel"),
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
            ]
        ),
```

It should not try to build it, just like if it was:

```swift
        .target(
            name: "OSKCloudAuth",
            dependencies: [
                .target(name: "OSKCloudModel"),
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
            ]
        ),
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS 12.4
 - Xcode Version/Tag/Branch: Xcode 13.4.1

**Additional context**

**Comment by neonichu** [comment]
The issue here is that we have two competing definitions of what should be built for root packages. On the one hand, there's the rule to always build all targets, on the other hand there's the reasonable expectation that if a target is conditionalized at least once, it should not be build in that context.

We're aware of this issue and it has recently been fixed for SwiftPM itself https://github.com/apple/swift-package-manager/pull/5784 -- an equivalent fix will be needed on the Xcode build system side to solve this concrete case, though.

**Comment by gpfister** [comment]
Thank you for the feedback. It seems that this issue can be closed.

**Comment by linkrjr** [comment]
Do we have a solution for this in xcode?

**Comment by NikolayJuly** [comment]
I have same issue. Work with "swift build" in terminal and doesn't work in xcode. Here id Feedback id - FB15945161
