### ISSUE TITLE
SPM Full git clones are not sustainable

### ISSUE THREAD

**Issue by racer1988** [apple/swift-package-manager#5878]
### Description

To my understanding SPM Clones full repositories of all packages.

Everytime a Package version number does not match (cause another developer updated the package.resolved file) I am forced to "Reset Package Cache" via Xcode, which starts the cloning process from scratch!

I don't have a fiber connection (cause that is not the norm in the whole world)
so my package resolving takes at least 15 **minutes**!

It also downloads a huge amount of data (since some repositories contains full binary history)

Although Github suggest not to use shallow clones, I would really like to understand how to use SPM.

Why aren't package repositories stored on the system and used to generate the update with a pull and a checkout, instead of fully cloning again each time?

**Comment by MaxDesiatov** [comment]
This looks like an Xcode-specific bug, please use Feedback Assistant for that. Outside of Xcode I've never seen this re-cloning behaviour ever happening, and repository caching seems to be working great.
