### ISSUE TITLE
`swift build --no-static-swift-stdlib` fails after running `swift build --static-swift-stdlib`

### ISSUE THREAD

**Issue by MaxDesiatov** [apple/swift-package-manager#5926]
### Description

When switching between different linking modes on Linux, the build state is apparently not cleaned up correctly, which causes build errors.

### Expected behavior

Running `swift build --no-static-swift-stdlib` after `swift build --static-swift-stdlib` should rebuild the project with correct linker settings with no errors.

### Actual behavior

Build fails with this error message
```
error: link command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld.gold: error: cannot find -lDispatchStubs
/usr/bin/ld.gold: error: cannot find -lCoreFoundation
/usr/bin/ld.gold: error: cannot find -luuid
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Steps to reproduce

1. Generate a new project with `swift package init --type executable`
2. Build it with `swift build --static-swift-stdlib`
3. Build it again, now with `swift build --no-static-swift-stdlib`

### Swift Package Manager version/commit hash

5.7.0

### Swift & OS version (output of `swift --version && uname -a`)
```
Swift version 5.7 (swift-5.7-RELEASE)
Target: aarch64-unknown-linux-gnu
Linux 2e60786449d5 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by adam-rocska** [comment]
Sooo.... what's up with this?

**Comment by MaxDesiatov** [comment]
No longer reproducible with Swift 5.7.3, 5.8.1, or 5.9 development snapshots on Ubuntu Jammy.

**Comment by neonichu** [comment]
🥳

**Comment by gregcotten** [comment]
I currently have this problem on any (I mean any) Swift version on Ubuntu 22.04, when building a shared library with `--static-swift-stdlib`.

**Comment by finagolfin** [comment]
@gregcotten, it sounds like you're hitting a long-standing issue that I filed in #8198: try the workaround there.
