### ISSUE TITLE
Path.removingLastComponent() recurses infinitely

### ISSUE THREAD

**Issue by tonyarnold** [apple/swift-package-manager#5956]
https://github.com/apple/swift-package-manager/blob/4111569c63698f1a6339dd053c9c4babb3e3ed95/Sources/PackagePlugin/Path.swift#L78-L93

I was working on a build plugin recently that walked parent directories looking for a configuration file to read, which worked great - until it hit the root of the filesystem ("/"). 

I would expect the result of calling `removingLastComponent()` on a `Path` representing "/" to be `nil`. 

It actually returns itself, so recursing continues infinitely.

**Comment by neonichu** [comment]
Hm, https://developer.apple.com/documentation/foundation/nsstring/1411141-deletinglastpathcomponent seems to have the same behavior

**Comment by tonyarnold** [comment]
Oof. I guess this problem is only relevant if you're iterating over the parents of a Path.

**Comment by neonichu** [comment]
We deprecated `PackagePlugin.Path`, so I think we can close this.
