### ISSUE TITLE
swift clean

### ISSUE THREAD

**Issue by wieczorek1990** [apple/swift-package-manager#5992]
Hello everyone,

I want to propose a feature of the `swift` program which is `clean`.
It would run a `rm -r .build/`.
`clean` action is something that is missing for people using `make`.

**Comment by tomerd** [comment]
there is `swift package clean` and `swift package reset` which should cover this need:

```
SUBCOMMANDS:
  clean                   Delete build artifacts
  reset                   Reset the complete cache/build directory
```

**Comment by wieczorek1990** [comment]
Thanks.

W dniu czw., 22.12.2022 o 18:19 tomer doron ***@***.***>
napisał(a):
