### ISSUE TITLE
XcodeTarget dependencies is always an empty list

### ISSUE THREAD

**Issue by doozMen** [apple/swift-package-manager#6003]
### Description

Make a tool aan print the xcodetarget dependencies. This is always an empty list.

### Expected behavior

To list the dependencies as the doc describes

### Actual behavior

empty list

### Steps to reproduce

see description

### Swift Package Manager version/commit hash

with xcode 14

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
Darwin MacBook-Pro-3.lan 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

**Comment by MaxDesiatov** [comment]
Could you provide more detailed steps please to help in reproduction of the issue? What kind of tool are you referring to? How exactly do you print the dependencies? What specific dependencies do you expect to see?

**Comment by doozMen** [comment]
``` swift
import Foundation
import PackagePlugin

@main
struct FooPlugin: BuildToolPlugin {

  func createBuildCommands(
    context: PackagePlugin.PluginContext,
    target: PackagePlugin.Target) async throws -> [PackagePlugin.Command]
  {
    print(target.dependencies)
    let output = URL() // some output file
    return [
      .buildCommand(
        displayName: "📦 FooPlugin",
        executable: try context.tool(named: "foo-tool").path,
        arguments: target.dependencies.map { $0.name },
        outputFiles: [output]),
    ]
  }

}

// https://developer.apple.com/forums/thread/707813
#if canImport(XcodeProjectPlugin)

import XcodeProjectPlugin

extension FooPlugin: XcodeBuildToolPlugin {
  func createBuildCommands(context: XcodePluginContext, target: XcodeTarget) throws -> [Command] {
    print(target.dependencies)
    let output = URL() // some output file
    return [
      .buildCommand(
        displayName: "🔨 FooPlugin",
        executable: try context.tool(named: "foo-tool").path,
        arguments: target.dependencies.map { $0.name },
        outputFiles: [output]),
    ]
  }
}
#endif

```

That is the plugin code and with dependencies  mean the section in xcode with that  id called  `Frameworks, Libraries, and Embedded Content`

![Screenshot 2023-01-04 at 14 44 57](https://user-images.githubusercontent.com/686038/210568376-a246a4a8-facb-4293-8e1a-a40e6f1947fe.png)

## Expected

The plugin in xcode or in spm have simular output for dependencies. When the plugin with similar code as above is applied to an spm library then it correctly outputs the depedencies based on the targets dependencies as defined in the package.swift.
For xcode I would expect it to print the dependencies listed in the section `Frameworks, Libraries, and Embedded Content`.

## Actual

For xcode targets the plugin is unable to read out the dependencies of a target, prints always an empty list

## Use case

I pass the dependencies to a tool that generates code based on the added dependencies. Now I can work around this by adding a file to an xcode targets compile sources listing the dependencies and that reading it out. But this is just ugly.

**Comment by tomerd** [comment]
cc @neonichu @abertelrud

**Comment by doozMen** [comment]
Any news on this?

**Comment by dfed** [comment]
I'm seeing this too.

**Comment by theoriginalbit** [comment]
Can confirm, also unable to see any `XcodeTargetDependency`. I've tested by adding a package to 'Package Dependencies' and adding that dependency to a Target. I also have a local Swift Package that is added to the target, it isn't listed as a dependency either, nor are any of its transient dependencies (I also see no trace of the local package in `context.xcodeProject.filePaths` or `context.xcodeProject.targets[0].inputFiles`)

**Comment by MaxDesiatov** [comment]
This repository does not track closed-source software such as Xcode. For that, you'll have to file feedback at http://feedbackassistant.apple.com.

As far as I understand, this issue is not reproducible with command-line `swift build` invocation, please feel free to reopen it otherwise.
