### ISSUE TITLE
Is there a libSwiftPM built into Swift or macOS can use directly?

### ISSUE THREAD

**Issue by surinrasu** [apple/swift-package-manager#6008]
👀

**Comment by tomerd** [comment]
You could pull it in as a dependency. It is also included in the Swift toolchain

**Comment by neonichu** [comment]
>  It is also included in the Swift toolchain

Just saw this because it was closed, but this isn't actually true. We do not include libSwiftPM as a separate library in Swift toolchains, it is statically linked into he SwiftPM executables only.
