### ISSUE TITLE
Error while fetching remote repository xxxx An unknown error occurred. username does not match previous request (-1)

### ISSUE THREAD

**Issue by veescope** [apple/swift-package-manager#6012]
### Description

I can clone this repo from the command line by using:
git clone XXXXX
However, swift package manager always displays he error message.

Error while fetching remote repository xxxx An unknown error occurred. username does not match previous request (-1)

There seems to be no work around for this.

### Expected behavior

It should allow me to clone the repo in swift package manager with the same as the git command line.  This does not work properly and needs a fix.

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-macosx12.0
Darwin MacBook-Pro-5.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

**Comment by veescope** [comment]
The problem was fixed by rebooting the machine.  Xcode was then able to work properly without displaying the error.

**Comment by tomerd** [comment]
thanks for the update @veescope. for Xcode packages issues, please use an Apple feedback rather than a GH issue as the technologies are not exactly the same.

**Comment by tomerd** [comment]
cc @abertelrud
