### ISSUE TITLE
Executable product breaks module namespace

### ISSUE THREAD

**Issue by TeamPuzel** [apple/swift-package-manager#6071]
### Description

Here is an example of my `Package.swift` file:
```swift
let package = Package(
    name: "MyProject",
    products: [.executable(name: "my-executable", targets: ["MyModule"])],   // <- The executable is named here
    targets: [
        // MARK: - Game
        .executableTarget(name: "MyModule", dependencies: ["GLAD", "SDL2"]), // <- The module is named here
        // MARK: - Libraries
        .target(name: "GLAD"),
        .systemLibrary(
            name: "SDL2",
            pkgConfig: "sdl2",
            providers: [
                .brewItem(["sdl2"]),
                .aptItem(["libsdl2-dev"])
            ]
        ),
    ]
)

```

### Expected behavior

I have to resolve an in module name collision between a type and a protocol.
I should be able to solve it like this:
```swift
protocol VertexBuffer {}

enum GL {
    struct VertexBuffer: MyModule.VertexBuffer {}
}
```

### Actual behavior

Instead, Swift package manager confuses the module name and the executable:
```swift
protocol VertexBuffer {}

enum GL {
    struct VertexBuffer: my_executable.VertexBuffer {}
}
```

This is especially bad because the naming convention of executables is completely different from Swift modules and types, renaming either is not ideal and requires a compromise somewhere.
I also wouldn't expect my code to break from renaming the product, but it does.

### Steps to reproduce

Create a Swift package with an executable product and try to resolve a protocol -> type name collision.

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.7.1 (Xcode)

### Swift & OS version (output of `swift --version && uname -a`)

```bash
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0

Darwin macbookpro.local 22.3.0 Darwin Kernel Version 22.3.0: Sun Dec  4 18:16:43 PST 2022; root:xnu-8792.80.21.0.2~9/RELEASE_ARM64_T8103 arm64
```

**Comment by neonichu** [comment]
We don't spell this behavior out very well, AFAIK, but I believe this works as designed.

**Comment by TeamPuzel** [comment]
The package manager uses the `.executableTarget` name and only switches to using the different `.executable` after it's added, breaking existing code.
That is an interesting design choice. Is executableTarget not the target?

If that's the case, may I ask why it's designed like this?

**Comment by neonichu** [comment]
It looks like the concrete behavior for executable products wasn't defined in the original [proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0146-package-manager-product-definitions.md). Maybe @abertelrud remembers the rationale for "merging" executable product and target.
