### ISSUE TITLE
Xcode Project w/ SPM Dependency builds from UI, but not xcodebuild

### ISSUE THREAD

**Issue by bolsinga** [apple/swift-package-manager#6074]
### Description

An Xcode macOS project with a SPM dependency will build and run just fine from the Xcode UI. However if I `xcodebuild` from the command line, the swift tools will fail to find the module in the SPM library while compiling a file with the dependency included.

### Expected behavior

I expect builds that succeed in the Xcode UI to also succeed from `xcodebuild`. I want to be able to use `xcodebuild` from my CI builds successfully. See also: https://developer.apple.com/forums/thread/721630

### Actual behavior

Looking at the build log, the SPM builds, and then the Xcode project code that depends upon the SPM code fails to build, since it cannot find the module defined by the SPM dependency

### Steps to reproduce

1. Clone https://github.com/bolsinga/MissingArt
2. Cmd-B the project in Xcode UI. It will successfully build and run.
3. cd path/to/MissingArt && `xcodebuild`. It will not build successfully, with the error:

```
/Users/bolsinga/Documents/code/git/MissingArt/MissingArt/MissingArtwork+AppleScript.swift:10:8: error: no such module 'MissingArtwork'
import MissingArtwork
       ^

```

To see if it was just a problem affecting my project, I created a new macOS SwiftUI project from scratch, and had it depend upon a random SwiftUI library available via SPM. I then made the SwiftUI ContentView use this library. It also built and ran fine from Xcode UI, but failed in `xcodebuild`.

### Swift Package Manager version/commit hash

$ swift package --version Swift Package Manager - Swift 5.7.1

### Swift & OS version (output of `swift --version && uname -a`)

```
$ swift --version && uname -a && xcodebuild -version
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
Darwin neu.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 arm64
Xcode 14.2
Build version 14C18
```

**Comment by neonichu** [comment]
Packages are not supported in legacy-style builds, you will need to pass `-scheme` on the commandline. You can run `xcodebuild -list` to see available schemes or use the same scheme name that you're using in the IDE.

**Comment by bolsinga** [comment]
Thanks @neonichu I appreciate the info! It worked for me. I will file a follow up Feedback on `xcodebuild` to at least warn "hey you're using SPM and legacy, and that won't work!" later today.

**Comment by bolsinga** [comment]
FWIW I filed FB11966377
