### ISSUE TITLE
Xcode generates Info.plist with bad bundle id

### ISSUE THREAD

**Issue by jasonbobier** [apple/swift-package-manager#6077]
### Description

I'm not sure if this is an SPM issue or an Xcode issue. It is also being tracked at: FB11575987 (I copied and pasted the issue here from there.)

Please provide a descriptive title for your feedback:
Xcode generates Info.plist with bad bundle id

Which area are you seeing an issue with?
Xcode

What type of feedback are you reporting?
Incorrect/Unexpected Behavior

Details

What version of Xcode are you using?
Version 14.2 (14C18)

Did you see an error message?
Yes

What was the error?
 Showing All Issues invalid character in Bundle Identifier. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters.  

What time did the issue occur?

What devices were you using when the issue occurred?
Mac

Description

Please describe the issue:
Xcode is generating a bad bundle id for the GoogleUtilities package.

Please see: https://github.com/firebase/firebase-ios-sdk/issues/9912

I have included a project that demonstrates the issue as well.

Please list the steps you took to reproduce the issue:
Please build the enclosed app and look at the build issues. You will see the bad bundle id being generated.

What did you expect to happen?
Xcode generates a good bundle id

[BadBundleID.zip](https://github.com/apple/swift-package-manager/files/10498456/BadBundleID.zip)

**Comment by neonichu** [comment]
Definitely sounds like an Xcode issue, thanks for filling FB11575987!
