### ISSUE TITLE
`swift-test` cannot determine if output writes to a terminal

### ISSUE THREAD

**Issue by grynspan** [apple/swift-package-manager#6081]
### Description

It's common to change the format of output (notably, adding ANSI escape codes) when `stdout`/`stderr` is a TTY/terminal. SPM uses pipes to route output from a plugin back to the main `swift` process and its `stdout`, which prevents the use of `isatty()` etc. to determine the format of output.

swift-test could, in particular, leverage this information to make failed tests more visible (red, bold, etc.)

SPM could dodge the issue by setting an environment variable on spawned test processes when it determines its own output is a TTY, and then plugins could be modified to check that variable. For example:

```swift
  var environment: [String: String] = ...
#if os(macOS) || os(iOS) || os(watchOS) || os(tvOS) || os(Linux)
  if nil != getenv("TERM") {
    if 0 != isatty(STDOUT_FILENO) {
      environment["SPM_STDOUT_IS_TTY"] = "1"
    }
    if 0 != isatty(STDERR_FILENO) {
      environment["SPM_STDERR_IS_TTY"] = "1"
    }
  }
#elseif os(Windows)
  if let stdoutHandle = GetStdHandle(STD_OUTPUT_HANDLE) {
    var screenBufferInfo = CONSOLE_SCREEN_BUFFER_INFO()
    if GetConsoleScreenBufferInfo(stderrHandle, &screenBufferInfo) {
      environment["SPM_STDOUT_IS_TTY"] = "1"
    }
  }
  if let stderrHandle = GetStdHandle(STD_ERROR_HANDLE) {
    var screenBufferInfo = CONSOLE_SCREEN_BUFFER_INFO()
    if GetConsoleScreenBufferInfo(stderrHandle, &screenBufferInfo) {
      environment["SPM_STDERR_IS_TTY"] = "1"
    }
  }
#endif
```

### Expected behavior

I'd expect the typical behaviour for `isatty(STDOUT_FILENO)` and `isatty(STDERR_FILENO)` (and the Windows equivalents.)

### Actual behavior

These streams are pipes on the swift-test side.

### Steps to reproduce

N/A

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.8.0-dev

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.73 Apple Swift version 5.8 (swiftlang-5.8.0.113.42 clang-1403.0.19.8)
Target: arm64-apple-macosx13.0
macOS Ventura

**Comment by tomerd** [comment]
cc @neonichu @abertelrud
