### ISSUE TITLE
Docs talk about making system modules, but doing so results in deprecation warnings

### ISSUE THREAD

**Issue by JetForMe** [apple/swift-package-manager#6121]
### Description

The [docs](https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#requiring-system-libraries) talk about how to create a `Clibgit2` example, but if you follow that, you'll get a warning like this:

```
warning: 'clibmagic': system packages are deprecated; use system library targets instead
```

However, the docs don’t mention that, and don’t talk about “system libraries” except in the context of system modules.

### Swift & OS version (output of `swift --version && uname -a`)

$ swift --version && uname -a
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
Darwin EclipseM1.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

**Comment by tomerd** [comment]
thanks @JetForMe. would you like to submit a PR to address this?

**Comment by JetForMe** [comment]
@tomerd [This](https://github.com/apple/swift-package-manager/blob/263171977ebcd47f4aaca1202cff5a96c5158a64/Documentation/Usage.md#import-system-libraries) version of the docs exist; I'm not sure how accurate they are. I have so far failed to successfully import a library using the steps, but I deviated slightly from the instructions.

**Comment by Sberm** [comment]
I used .systemLibrary in example's Package.swift:
```
// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "example",
    targets: [
        .systemLibrary(name: "libgit2", path : "Sources/libgit2", pkgConfig: "libgit2"),
        .executableTarget(name: "example", dependencies: ["libgit2"]),
        .testTarget(
            name: "exampleTests",
            dependencies: ["example"])
    ]
)
```
it looks like this
```
./
├── Package.swift
├── README.md
├── Sources
│   ├── example
│   │   └── example.swift
│   └── libgit2
│       ├── libgit2.h
│       └── module.modulemap
└── Tests
    └── exampleTests
        └── exampleTests.swift
```
I ran swift build and swift run there is no `warning: 'x': system packages are deprecated; use system library targets instead` warning anymore. But I guess libgit2.dylib is kinda old, but that's not swiftPM's problem.

```
~/Desktop/Cabin/Cabin/testdoc/example$ swift run
Building for debugging...
ld: warning: dylib (/usr/local/Cellar/libgit2/1.5.0/lib/libgit2.dylib) was built for newer macOS version (12.0) than being linked (10.13)
[3/3] Linking example
Build complete! (3.48s)
Hello, World!
git_repository_init_options(version: 0, flags: 0, mode: 0, workdir_path: nil, description: nil, template_path: nil, initial_head: nil, origin_url: nil)
```

**Comment by Sberm** [comment]
> thanks @JetForMe. would you like to submit a PR to address this?

By using .systemLibrary target, the above warning is no longer reported. Can I submit a PR to it?

**Comment by JetForMe** [comment]
> Can I submit a PR to it?

I'm sure they'll happily review it.

**Comment by natikgadzhi** [comment]
Uh, hello there @JetForMe and @Sberm! Didn't mean to be rude, just stumbled at this, and thought I'd try to get some experience with SwiftPM, and update the docs as a side effect. 

I think the approach in the PR is aligned with what @Sberm proposed, but without copying the header file into the project directory.
