### ISSUE TITLE
Xcode does not show latest version for packages tagged with `10` as a major version 

### ISSUE THREAD

**Issue by ncooke3** [apple/swift-package-manager#6143]
### Description

> Note: I'm not sure that the logic corresponding to this behavior lives in SPM or in Xcode, so I'd appreciate if the SwiftPM team could help clarify as this may be better served as a Radar?

Xcode does not show the correct latest tag when the package being added has `10` as a major version. In my example, I have a package tagged with `9.0.0` and `10.0.0`. When adding it in a client project, one would expect `10.0.0` to show as the current major version to pin at, but Xcode keeps showing `9.0.0`.

<p align="center">
  <img 
    width="750" 
    align="center"
    alt="Screenshot of issue." 
    src="https://user-images.githubusercontent.com/36927374/218178647-5147de27-71ed-4cf4-9d19-a913ff097c12.png"
  >
</p>

It appears that the latest tag is not being surfaced correctly.

### Expected behavior

I expected Xcode to pin to version `10.0.0`.

### Actual behavior

Xcode to pinned to the previous major version, `9.0.0`.

### Steps to reproduce

1. Create a package and host it on a repo
2. Push a tag with a major version under `10` (e.g. `9.0.0`)
3. Push a tag with a major version of `10` (e.g. `10.0.0`)
4. In a client project, add the package via Xcode.
5. On the package preview page, selecting the _Up to Next Major Version_ dependency rule will pin 9.0.0 as the current major version. **This is unexpected as the latest version is 10.0.0.**

Here is a repro project with instructions: https://github.com/ncooke3/MyPackage. Try adding it as a package to see the unexpected tag behavior.

So far, I've reproduced on Xcode 13.3.1 and Xcode 14.2.

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.6.0

### Swift & OS version (output of `swift --version && uname -a`)

```
swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
Target: x86_64-apple-macosx12.0
Darwin nickcooke-macbookpro.roam.corp.google.com 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64
```

**Comment by SDGGiesbrecht** [comment]
Xcode seems to be sorting them as strings instead of as versions. (i.e.  1 < 10 < 1a < 2 < 200 < 3) From a quick glance at the relevant source, SwiftPM does not appear to do this. (See [here](https://github.com/apple/swift-package-manager/blob/8f62a4cb12ef83c74da26368c5a5c2c67b95cda5/Sources/Workspace/SourceControlPackageContainer.swift#L102-L133) and [here](https://github.com/apple/swift-tools-support-core/blob/b484fbe608bb6fed4838ef52ff0fe0ea2f88537d/Sources/TSCUtility/Version.swift#L161-L211).)

**Comment by ncooke3** [comment]
Thanks @SDGGiesbrecht! That makes sense, so a Radar for the Xcode team is probably in order here then.

**Comment by ncooke3** [comment]
I filed `FB11991841` to track this. I'll close this since I don't think the issue lies in this repo, but within Xcode's integration with SPM. I'll update if I receive any news regarding a confirmation/fix for the issue.

cc: @neonichu

**Comment by gerchicov-vg** [comment]
> Xcode seems to be sorting them as strings instead of as versions. (i.e. 1 < 10 < 1a < 2 < 200 < 3) From a quick glance at the relevant source, SwiftPM does not appear to do this. (See [here](https://github.com/apple/swift-package-manager/blob/8f62a4cb12ef83c74da26368c5a5c2c67b95cda5/Sources/Workspace/SourceControlPackageContainer.swift#L102-L133) and [here](https://github.com/apple/swift-tools-support-core/blob/b484fbe608bb6fed4838ef52ff0fe0ea2f88537d/Sources/TSCUtility/Version.swift#L161-L211).)

@SDGGiesbrecht 
https://github.com/facebook/facebook-ios-sdk
currently there latest version is 18.0.0 but when you try to add Facebook spm "as is" it downloads 14.x version. 18 > 14

**Comment by SDGGiesbrecht** [comment]
@gerchicov-vg, I got your note, but I do not think I can help you. My hardware restricts me to an older version, which treats your Facebook package as described two years ago. You will have to get the attention of a more recently active contributor. I do not know who would be best to talk to these days. From the contribution statistics, maybe @MaxDesiatov?

**Comment by gerchicov-vg** [comment]
@SDGGiesbrecht I also found this:
https://github.com/facebook/facebook-ios-sdk/issues/2363
They say that spm tries to download an older Facebook SDK because there was a mistake in version names - they wrote "14.1.0" instead of "v14.1.0" and that broke version sequence.
