### ISSUE TITLE
No warning is emitted if no return value is provided in Objective-C

### ISSUE THREAD

**Issue by richardtop** [apple/swift-package-manager#6357]
### Description

Hi. We noticed quite a strange behavior in SwiftPM where it does not warn about missing return statements in Objective-C. Is this behavior expected?

Is there a way to tell SwiftPM to inherit build/compile flags from the Xcode project? When I try to do the same on the Xcode project side, I get the expected behavior. Build fails and I must fix the issue before proceeding. But not in case with SwiftPM.

Feedback: [FB1155848](https://feedbackassistant.apple.com/feedback/1155848)
Apple Forum: [No warning about missing return statement in Objective-C code in SwiftPM](https://developer.apple.com/forums/thread/715437)

In addition to a case described below, using the following constructs also doesn't lead to a warning when used in the SwiftPM environment:

```Objective-C
- (BOOL)doTheJob:(NSArray<NSString *> *)parameter {

// no return value

}
```

### Expected behavior

Build fails due missing return statement

### Actual behavior

Build succeeds and every time the method is run, it returns random values

### Steps to reproduce

1. Create an Xcode project in Objective-C
2. Create an SwiftPM package in Objective-C
3. Add a method in the SwiftPM package that returns a BOOL
4. Leave the body of the method empty (no return statement)
5. Import the package in the project and invoke the method in the project

### Swift Package Manager version/commit hash

Swift 5.8 (5.8.0.124.2) Xcode 14.3 Release

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
Darwin ******************* 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

**Comment by neonichu** [comment]
```
❯ swift build              
Building for debugging...
/private/tmp/pkg10/Sources/pkg10/foo.m:14:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
1 warning generated.
[1/1] Compiling pkg10 foo.m
```

Warning is present, so I guess this is either something Xcode specific or maybe happens because we hide warnings from dependencies? Either way, feedback is the right venue for it.
