### ISSUE TITLE
Windows: Freshly created package with executable target builds with error `0: error: missing required module 'SwiftShims'`

### ISSUE THREAD

**Issue by valeriyvan** [apple/swift-package-manager#6387]
### Description

Windows: Freshly created package with executable target builds with error `0: error: missing required module 'SwiftShims'`

### Expected behavior

Freshly created package should build without errors

### Actual behavior

Windows: Freshly created package with executable target builds with error `0: error: missing required module 'SwiftShims'`

```
c:\Users\1\Documents\tmp>swift package init --type executable
Creating executable package: tmp
Creating Package.swift
Creating .gitignore
Creating Sources/
Creating Sources\main.swift

c:\Users\1\Documents\tmp>swift build
error: 'tmp': Invalid manifest (compiled with: ["C:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\bin\\swiftc.exe", "-L", "C:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\lib\\swift\\pm\\ManifestAPI", "-lPackageDescription", "-sdk", "C:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\SDKs\\Windows.sdk", "-libc", "MD", "-I", "C:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows", "-I", "C:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows\\x86_64", "-L", "C:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows\\x86_64", "-use-ld=lld", "-swift-version", "5", "-I", "C:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\lib\\swift\\pm\\ManifestAPI", "-package-description-version", "5.8.0", "C:\\Users\\1\\AppData\\Local\\Temp\\TemporaryDirectory.fYGiNk\\manifest.swift", "-Xfrontend", "-disable-implicit-concurrency-module-import", "-Xfrontend", "-disable-implicit-string-processing-module-import", "-o", "C:\\Users\\1\\AppData\\Local\\Temp\\TemporaryDirectory.TxK9Yr\\tmp-manifest.exe"])
<unknown>:0: error: missing required module 'SwiftShims'
```

### Steps to reproduce

Run commands:

* `swift package init --type executable`
* `swift build`

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.8.0

### Swift & OS version (output of `swift --version && uname -a`)

Swift 5.8
```
swift --version
compnerd.org Swift version 5.8 (swift-5.8-RELEASE)
Target: x86_64-unknown-windows-msvc
```

WIndows 10 Pro 10.0.19045

**Comment by tomerd** [comment]
cc @compnerd

**Comment by compnerd** [comment]
Given that this is 5.8, I would hazard a guess that you have failed to repair the installation after an update of Visual Studio.

**Comment by valeriyvan** [comment]
You are right. Documentation at https://www.swift.org/getting-started/ has paragraph:

> Repairing after Visual Studio Updates
> If Visual Studio is updated, you may have to repair the installation. See Microsoft’s [instructions](https://support.microsoft.com/en-us/windows/repair-apps-and-programs-in-windows-10-e90eefe4-d0a2-7c1b-dd59-949a9030f317) for repairing installed programs.

It's not clear exactly what has to be "repaired" and how.

Here are the steps.

* Launch **Control Panel**.
* In **Control Panel** launch **Programs and Features**.
* In **Programs and Features** find **Swift Developer Package for Windows x86_64**.
* Right click on **Swift Developer Package for Windows x86_64** and click **Change** in contectual menu.
* In launched installer click **Repair** and follow instructions.

![Знімок екрана 2023-04-07 100939](https://user-images.githubusercontent.com/1630974/230560442-1080cd80-1056-403c-9860-255ab5cc259c.png)

After these steps `swift build` builds package normally.

Probably, in does make sense update documentation with these "repair" steps. Does it?

**Comment by tomerd** [comment]
cc @compnerd

**Comment by compnerd** [comment]
@valeriyvan yeah, I think that it makes sense as 5.8 was just released so it is the current stable release.  Would you mind making a PR against apple/swift-website for that?

**Comment by compnerd** [comment]
I don't think that we should do this anymore.  The toolchain will no longer modify the VS installation and instead injects a VFS to map the module in to the build.  This will properly remove this along with the necessity for administrator privileges (other than to instal to a system directory).
