### ISSUE TITLE
Xcode 14.3 doesn't use credentials (from netrc or keychain) for auth to a package registry

### ISSUE THREAD

**Issue by FirstAM** [apple/swift-package-manager#6395]
### Description

I'd tried to use this [solution](https://github.com/apple/swift-evolution/blob/main/proposals/0292-package-registry-service.md) (self hosted spm registry ) 
The main thing is - after success auth, utility append new credentials to ~/.netrc file or mac os keychain 
In my case all credential was appended, but credential getting from netrc or keychain only when i use command line utility
If i try to use Xcode, i got auth error status response that means credentials didn't send.
I've checked request headers, and exactly as i thought, credential didn't send 

In my case file content seems like that: 

**.swiftpm/configuration/registries.json**
```
{
  "authentication": {
    "spm-registry.net": {
      "type": "token"
    },
  },
  "registries" : {
    "scope" : {
      "url" : "https://spm-registry.net/api/spm-registry/"
    }
  },
  "version" : 1
}
```

**~/.netrc**

```
machine spm-registry.net 
login token 
password <TOKEN>
```

### Expected behavior

Xcode use credentials from netrc or keychain 

### Actual behavior

Credential was used only when i run cmd utility 

### Steps to reproduce

1. Install Xcode 14.3 
2. Setup registries url by command line 
3. Setup registries auth by command line 
4. Run your self-hosted spm registry
5. Try to resolve dependencies by Xcode application 

### Swift & OS version (output of `swift --version && uname -a`)

```
###############################

$ swift --version
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

###############################

$ swift package  --version
Swift Package Manager - Swift 5.8.0

###############################

$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.1 (22C65)
      Kernel Version: Darwin 22.2.0
      ...

###############################

$ system_profiler SPDeveloperToolsDataType
Developer:

    Developer Tools:

      Version: 14.3 (14E222b)
      Location: /Applications/Xcode.app
      Applications:
          Xcode: 14.3 (21812)
          Instruments: 14.3 (64559.163)
      ...
```

**Comment by yim-lee** [comment]
rdar://107679395

**Comment by tomerd** [comment]
cc @abertelrud

**Comment by FirstAM** [comment]
Hi @yim-lee, @abertelrud 
Do you have any updates?

**Comment by lukepistrol** [comment]
@yim-lee Can you confirm this will be available in a Xcode 14.x.x update or is it more likely this will be available only in the upcoming Xcode 15 beta?

**Comment by yim-lee** [comment]
@lukepistrol We will let you know the version when it's available.

**Comment by lukepistrol** [comment]
Seems to be included in the Xcode 15 Beta!

**Comment by yim-lee** [comment]
@lukepistrol Yep!

**Comment by felipeska** [comment]
Hello, I'm using XCode Version 15.0 beta 4 (15A5195m)

<img width="663" alt="Screenshot 2023-07-17 at 6 36 12 PM" src="https://github.com/apple/swift-package-manager/assets/613443/41a5cf9a-bffa-42df-9264-0b7ee32fde72">


<img width="1137" alt="Screenshot 2023-07-17 at 6 35 58 PM" src="https://github.com/apple/swift-package-manager/assets/613443/e8fcbeb3-425f-49f9-8509-a9698214db5d">

Xcode can't accept the credentials but in the server the authentication is valid.

**Comment by yim-lee** [comment]
@felipeska That's for npm?

**Comment by felipeska** [comment]
Hello @yim-lee, No. I'm using https://jfrog.com/help/r/jfrog-artifactory-documentation/swift-registry.
Swift registry works fine using CLI, but when I add a dependency from Xcode (File -> Add package dependency) the error mentioned error is what I get.

It's possible to use private and authenticated repository from XCode?
It's possible to use authentication similar to the one used via .netrc? basic token.
I am aware that XCode offers some authentication for most used platforms (Github, GitLab. Sourcetree), but it seems that handling Swift packages from JFrog is not possible.

Thanks!

**Comment by yim-lee** [comment]
@felipeska Xcode only supports registry credentials saved in Keychain. Is there an internet password entry for the registry you use in Keychain? 

https://github.com/apple/swift-evolution/blob/main/proposals/0378-package-registry-auth.md#macos-keychain

**Comment by yim-lee** [comment]
Xcode15 should make use of registry credentials from keychain, so closing this. Please create new issue if you still experience problem.

**Comment by saschpe** [comment]
> Hello, I'm using XCode Version 15.0 beta 4 (15A5195m)
> ...
> Xcode can't accept the credentials but in the server the authentication is valid.

Same issue, doesn't work with Xcode 15.0.1

**Comment by jeremybarr** [comment]
@saschpe I'm also having a hard time getting this working in Xcode. Have you gotten anywhere with this since?

**Comment by yim-lee** [comment]
Package registry credentials need to be added to Keychain via the [`swift package-registry login` command](https://github.com/apple/swift-package-manager/blob/main/Documentation/PackageRegistry/PackageRegistryUsage.md#registry-authentication) or manually (by creating an item under "Internet Passwords"). 

At the end you should have an entry like this in Keychain:
![image](https://github.com/apple/swift-package-manager/assets/12647725/c433a7a3-0793-41db-b111-3dc12cc2ad1f)

Note that this is different from source control account. Registry operations do not use source control credentials.

If it still doesn't work after ensuring the registry credentials are in Keychain, one thing you might check is if there is more than one entry for the same registry in Keychain. In this case, delete all the entries for the registry and create a new entry again. We don't know what causes multiple entries to be saved for the same registry, for we can't reproduce it consistently, so it would be great to get more information if that's what's happening for you.

**Comment by yim-lee** [comment]
> The proposal included using netrc, which would work for a CI environment, but that doesn't seem to work anymore.

What problem do you run into with netrc? netrc should still work, it's just that it's no longer the default if Keychain is available, but one can still override that using the `--netrc` option:

```bash
  --netrc                 Use netrc file even in cases where other credential stores are preferred
```

**Comment by justin-doordash** [comment]
@yim-lee Yes the command correctly adds the credentials to netrc, however xcodebuild refuses to utilize them. xcodebuild fails on Resolve Package Graph saying `missing or invalid authentication credential`.  xcodebuild doesn't seem to utilize netrc as a valid source of credentials for package auth. If we instead authorize without --netrc, xcodebuild prompts the user for access to keychain and correctly resolves the package, but we can't do that on CI

**Comment by yim-lee** [comment]
> xcodebuild doesn't seem to utilize netrc as a valid source of credentials for package auth. If we instead authorize without --netrc, xcodebuild prompts the user for access to keychain and correctly resolves the package, but we can't do that on CI

@justin-doordash I see. I will check with the team to see if we can fix/workaround this. In the meantime maybe there is some way to disable the Keychain prompt in CI?

**Comment by justin-doordash** [comment]
@yim-lee There doesn't seem to be a way to disable the keychain prompt, but even if we did the package resolution would still fail because it's not using the netrc for auth. Should I open a new issue and describe the issue in depth?

**Comment by yim-lee** [comment]
> but even if we did the package resolution would still fail because it's not using the netrc for auth

I was thinking you could use Keychain to store credentials if that's available in your CI environment.

> Should I open a new issue and describe the issue in depth?

Yes, that would be great. Thanks @justin-doordash.

**Comment by jeremybarr** [comment]
> Package registry credentials need to be added to Keychain via the [`swift package-registry login` command](https://github.com/apple/swift-package-manager/blob/main/Documentation/PackageRegistry/PackageRegistryUsage.md#registry-authentication) or manually (by creating an item under "Internet Passwords").
> 
> At the end you should have an entry like this in Keychain: ![image](https://private-user-images.githubusercontent.com/12647725/277779022-c433a7a3-0793-41db-b111-3dc12cc2ad1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMDMzNzQsIm5iZiI6MTcwMTIwMzA3NCwicGF0aCI6Ii8xMjY0NzcyNS8yNzc3NzkwMjItYzQzM2E3YTMtMDc5My00MWRiLWIxMTEtM2RjMTJjYzJhZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDIwMjQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YjkwZGVkMTY1OTc1ZTZhOTg4MzhlNjA0MjdiZjAzZTljMmU5OTliZjZiZTRhNjczYmExODI2MjcxNTk4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4yz7CgjDQFKfDeCAFRH4D3X5sxCz_dOAXj47kezEwI)
> 
> Note that this is different from source control account. Registry operations do not use source control credentials.
> 
> If it still doesn't work after ensuring the registry credentials are in Keychain, one thing you might check is if there is more than one entry for the same registry in Keychain. In this case, delete all the entries for the registry and create a new entry again. We don't know what causes multiple entries to be saved for the same registry, for we can't reproduce it consistently, so it would be great to get more information if that's what's happening for you.

@yim-lee The multiple credentials issue repeatedly happened to me.  I also was unable to connect to an authenticated repo with Xcode 15.  I've found that this problem seems to be due to upgrading from Xcode 14 to Xcode 15.  I've installed Xcode through the App Store and was constantly having these problems.  Once I deleted Xcode, and also deleted Xcode settings files like `com.apple.dt.Xcode` in locations like `~/Library/Application Scripts` , `~/Library/Preferences` , `~/Library/Containers`, `~/Library/Developer`, and `~/Library/Saved Application State` followed by a reinstall of Xcode directly from the App Store, both of my problems disappeared.

**Comment by yim-lee** [comment]
@jeremybarr Yeah we were unable to reproduce the multiple credentials issue ourselves, so we didn't know what caused it or how to fix/workaround it. I am sorry for not able to offer solutions or alternatives when you ran into that problem. Glad to hear you figured that out and I am sure your notes will help others as well!

**Comment by Baza207** [comment]
I see there's been a variety of questions here regarding authentication, but I still can't get past the adding the package as a local repository to an Xcode Project. We're trying it similar to @felipeska with Atrifactory, but can't get past the File -> Add package dependency step. Am I missing something?

We have .netrc file with the token credentials at the user level, there's a keychain (internet password type) item looking the same as @yim-lee posted above, but I still constantly get a dialog saying "authentication failed". 😞

Any help or pointers appreciated.

**Comment by ncharniauski** [comment]
> I see there's been a variety of questions here regarding authentication, but I still can't get past the adding the package as a local repository to an Xcode Project. We're trying it similar to @felipeska with Atrifactory, but can't get past the File -> Add package dependency step. Am I missing something?
> 
> We have .netrc file with the token credentials at the user level, there's a keychain (internet password type) item looking the same as @yim-lee posted above, but I still constantly get a dialog saying "authentication failed". 😞
> 
> Any help or pointers appreciated.

Yes, I am experiencing the same issue. Trying to add package dependency from the protected Artifactory Swift registry and failing at the Xcode Authentication screen. Keychain has credentials to connect to Artifactory. When I open "Add Package Dependency" window - Xcode prompts me to get access to keychain, which I grant. Then when I enter Artifactory URL to locate the package, Xcode displays Authentication window with error: "Authentication failed because the credentials were rejected". Once I manually enter User name/password - authentication still fails. 
Registry URL and credentials are correct, I can confirm via running "swift package-registry login" and then "swift package resolve". I tried both types of authentication - basic and token -- both fail. 
What am I missing? Why I cannot simply add protected Artifactory package dependency to Xcode app project via keychain creds or via manually entering credentials? Any missing steps here?

**Comment by yim-lee** [comment]
Registry package dependency is specified with package id in `Package.swift` rather than a URL. For example:

```swift
dependencies: [
    .package(id: "mona.LinkedList", .upToNextMajor(from: "1.0.0")),
],
```

I suggest that you try editing `Package.swift` to use `id` for packages that are supposed to be downloaded from Artifactory Swift registry, make sure the credentials are in Keychain, then see if Xcode and/or `swift package resolve` works.

Note that the corresponding Artifactory repo must have the "Swift" package type.

**Comment by ncharniauski** [comment]
> Registry package dependency is specified with package id in `Package.swift` rather than a URL. For example:
> 
> ```swift
> dependencies: [
>     .package(id: "mona.LinkedList", .upToNextMajor(from: "1.0.0")),
> ],
> ```
> 
> I suggest that you try editing `Package.swift` to use `id` for packages that are supposed to be downloaded from Artifactory Swift registry, make sure the credentials are in Keychain, then see if Xcode and/or `swift package resolve` works.
> 
> Note that the corresponding Artifactory repo must have the "Swift" package type.

Xcode resolves private Artifactory dependencies listed in Package.swift just fine. This is not the issues.
The issue is only with adding private packages to application xcproject directly from the Xcode UI:
<img width="1375" alt="Screenshot 2024-01-08 at 7 00 01 PM" src="https://github.com/apple/swift-package-manager/assets/90726135/346c9bf6-92a9-494d-ae21-1a2eb7fea349">

Application project does not contain Package.swift. It is not a package, it is a simple application project.

**Comment by yim-lee** [comment]
> Xcode resolves private Artifactory dependencies listed in Package.swift just fine. This is not the issues.
> The issue is only with adding private packages to application xcproject directly from the Xcode UI:

@ncharniauski Can you create a new issue detailing the steps it takes to reproduce the issue? Please include example of values you enter in the UI. e.g., do you type in Artifactory URL or package identifier?

**Comment by ncharniauski** [comment]
> > Xcode resolves private Artifactory dependencies listed in Package.swift just fine. This is not the issues.
> > The issue is only with adding private packages to application xcproject directly from the Xcode UI:
> 
> @ncharniauski Can you create a new issue detailing the steps it takes to reproduce the issue? Please include example of values you enter in the UI. e.g., do you type in Artifactory URL or package identifier?

new issue is created: https://github.com/apple/swift-package-manager/issues/7237

**Comment by choli** [comment]
Why is this issue closed? The netrc issue is still open. Or how can i resolve it? I have no access to the keychain on our CI, but I can add a token to the .netrc, but then it fails as described above.

**Comment by KushalChoudhary14sep** [comment]
@yim-lee @felipeska  I am facing the same issue of authentication failure while adding the swift package hosted in JFROG artifact using the url.

The same is working while trying to run "swift package-registry login" using the same credentials and following message occurs - "Login successful."

Can you please help me to resolve this issue?

**Comment by nhatlee** [comment]
I faced same issue, already generated new token with full permission but didn't work

<img width="1096" alt="Image" src="https://github.com/user-attachments/assets/06b9f282-d0af-411e-8d14-859e16426703" />

**Comment by AlekseyLibin** [comment]
Hi all, I've managed to solve the problem and it now works for me (hint: not an Xcode problem). I explained everything in  following article: [https://medium.com/@a_libin01/how-to-add-a-swift-package-from-jfrog-artifactory-to-an-xcode-project-058ee0678b64](https://medium.com/@a_libin01/how-to-add-a-swift-package-from-jfrog-artifactory-to-an-xcode-project-058ee0678b64)

**Comment by choli** [comment]
Thank you for this, 4) blew my mind 😄

Not exactly the issue, but if someone looks for this:
It doesn't solve the issue for a CI where you have no possibility to login on a keychain though. 

We solved this by calling the following login on the CI script:
`swift package-registry --netrc login https://my.artifactory.url/artifactory/api/swift/my-virtual-repo --username myuser --password #{secrets.token} --no-confirm`

and then xcodebuild is called additionally with 
`xcodebuild clean build -packageAuthorizationProvider netrc`

**Comment by nhatlee** [comment]
For me, I used `git config --global url."git@github.com:".insteadOf "https://github.com/"` that led to a problem 👉 only able to fetch package via ssh. 
If the package had no dependency will be ok, however if the package of that repo using dependencies which are set up as https url, then Xcode will fail to fetch. 
To fixed run commands:
```
git config --global --unset-all url.https://github.com/.insteadof || true
git config --global --unset-all url.git@github.com:.insteadof || true
```
