### ISSUE TITLE
The binaryTarget in Package.swift does not appear in the list of alternative Libraries

### ISSUE THREAD

**Issue by tamwei** [apple/swift-package-manager#6494]
### Description

For ease of description, I will use Kingfisher's [Package.swift](https://github.com/onevcat/Kingfisher/blob/master/Package.swift) and Flurry's [Package.swift](https://github.com/flurry/FlurrySwiftPackage/blob/master/Package.swift), but this is not a bug of Flurry, I also made a swift Package like Flurry, and I encountered the same problem.

In the below image, I have added Kingfisher and Flurry to the target `TestSPM`, but when I want to add these two Libraries to another target `TestSPMExtensionExtension` (add to `target->General->Frameworks and Libraries`), I find that there is no Flurry in the Library candidate list.

![1682647755](https://user-images.githubusercontent.com/13300832/235071628-82000f10-3718-4d37-a6c4-555323247f75.png)

![1682664033](https://user-images.githubusercontent.com/13300832/235073458-1da0fe9a-7d18-4420-a5bc-b13d95735677.png)

After comparing Kingfisher and Flurry, I suspect that the reason why Flurry does not appear in the Library candidate list may be that Flurry uses binaryTarget with Flurry.xcframework in Package.swift
(https://github.com/flurry/FlurrySwiftPackage/blob/master/Package.swift#LL36C30-L36C48)

### Expected behavior

The swift package using the binary library can also appear in the Library candidate list like Kingfisher in above image.

### Swift Package Manager version/commit hash

 swift-tools-version:5.6

### Swift & OS version (output of `swift --version && uname -a`)
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx12.0

**Comment by tomerd** [comment]
cc @abertelrud seems like Xcode feedback?

**Comment by neonichu** [comment]
In theory any library product should show up in that list, regardless if it is comprised of binaries or not, so this sounds like a bug in Xcode to me.

**Comment by tamwei** [comment]
Can you give feedback to the Xcode team? Please comment with me when this is resolved or has a schedule. Thanks.
