### ISSUE TITLE
Packages that depends on binary targets cannot be build with iOS/iOS Simulator SDKs

### ISSUE THREAD

**Issue by aleksproger** [apple/swift-package-manager#6571]
### Context

We have several packages which contain multiplatform code on C/C++/Swift.
We want to build packages against macOS/iOS/iOS Simulator SDKs to ensure that code compiles on all needed platforms.
We want to build Swift command plugin for this which calls `packageManager.build()` with all necessary flags. (`xcodebuild` not an option because of sandbox environment and I want to stay consistent with what SPM provides). 
Some of the packages have **`.binaryTarget()` dependencies** on `XCFrameworks` 

### Initial solution

Initially I came up with the following script to build package against custom SDK
And this **works fine** with packages that **don't have  `.binaryTarget()` dependencies**
```shell
swift build \
  --configuration release \
  -Xswiftc "-sdk" -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \ 
  -Xswiftc "-target" -Xswiftc "arm64-apple-ios15.0-simulator" \
  -Xcc "-isysroot" -Xcc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \
  -Xcc "-target" -Xcc "arm64-apple-ios15.0-simulator"
```

After several experiments I discovered that it **doesn't work** with packages that **have `.binaryTarget()` dependencies**
The following error is emitted in such case

```shell
error: link command failed with exit code 1 (use -v to see invocation)
clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone' [-Wincompatible-sysroot]
ld: building for iOS Simulator, but linking in dylib built for macOS, file '.../.build/arm64-apple-macosx/release/OpenSSL.framework/OpenSSL'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Solution based on `swift build --triple`

Where `OpenSSL.framework` is part of `XCFramework` binary dependency.
This error means that  `XCFramework` was thinned not for `iOS` which I'm trying to build for but for `macOS`, so I've decided to set a triple explicitly for `swift build`
And supported `swift build` triples which are interesting for me are `arm64/x86_64-apple-macosx` and `arm64/x86_64-apple-darwin`

```shell
swift build \
  --configuration release \
  --triple arm64-apple-darwin \
  -Xswiftc "-sdk" -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \ 
  -Xswiftc "-target" -Xswiftc "arm64-apple-ios15.0-simulator" \
  -Xcc "-isysroot" -Xcc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \
  -Xcc "-target" -Xcc "arm64-apple-ios15.0-simulator"
```

And specifying `arm64-apple-darwin` indeed allowed to make SPM to resolve the whole package not only macOS slice.
But, the other error raised from this
```shell 
/.../src/lib/CryptoImpl.cpp:341:10: fatal error: 'OpenSSL/evp.h' file not found
#include <OpenSSL/evp.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```
So, I realised that now it cannot locate the proper `LibraryInfo` from the `XCFramework`, because of how platform string and and filter are implemented `Sources/SPMBuildCore/BinaryTarget+Extensions.swift`

```swift
guard let library = metadata.libraries.first(where: {
      $0.platform == triple.os.asXCFrameworkPlatformString &&
      $0.architectures.contains(triple.arch.rawValue)
 }) else { return [] }
  
extension Triple.OS {
    /// Returns a representation of the receiver that can be compared with platform strings declared in an XCFramework.
    fileprivate var asXCFrameworkPlatformString: String? {
        switch self {
        case .darwin, .linux, .wasi, .windows, .openbsd, .noneOS:
            return nil // XCFrameworks do not support any of these platforms today.
        case .macOS:
            return "macos"
        }
    }
}
```

### Proposal

- Add parsing of `ios/ios-simulator` triples and `watchOS/tvOS` could be added separately
- Add parsing of `SupportedPlatformVariant` to `XCFrameworkMetadata`
- Add `ios` to `Triple.OS` and `simulator` to `Triple.ABI` and separately `watchos/tvos` related models

### Further idea
I'm not sure how it could be implemented technically, but would be happy to work on this

- Add flags to link proper SDKs based on the triple provided to swift-build

```shell
  -Xswiftc "-sdk" -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \ 
  -Xswiftc "-target" -Xswiftc "arm64-apple-ios15.0-simulator" \
  -Xcc "-isysroot" -Xcc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \
  -Xcc "-target" -Xcc "arm64-apple-ios15.0-simulator"
```

### Expected behavior

`swift build --triple arm64-apple-ios` exists and works with binary targets properly

### Actual behavior

`swift build --triple arm64-apple-ios` doesn't exist and `swift build --triple arm64-apple-darwin` doesn't work with binary targets

### Steps to reproduce

1. Create Package with `.binaryTarget()` which depends on `.xcframework`
2. Try to build it for iOS Simulator using
```shell
swift build \
  --configuration release \
  --triple arm64-apple-darwin \
  -Xswiftc "-sdk" -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \ 
  -Xswiftc "-target" -Xswiftc "arm64-apple-ios15.0-simulator" \
  -Xcc "-isysroot" -Xcc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \
  -Xcc "-target" -Xcc "arm64-apple-ios15.0-simulator"
```

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

**Comment by aleksproger** [comment]
Pull request - https://github.com/apple/swift-package-manager/pull/6572

**Comment by neonichu** [comment]
Note that building with SwiftPM for iOS etc will not be a valid way to verify your package entirely since it won't 1:1 match the behavior of Xcode's build system (especially around resources, but not limited to that). That said, I think it's still a reasonable enhancement to allow building for other Apple platforms using SwiftPM.

**Comment by peterkos** [comment]
For anyone else sleuthing, PR was recreated here: https://github.com/apple/swift-package-manager/pull/6732

**Comment by peterkos** [comment]
Since that was merged, I believe this can be closed -- is the issue resolved for you? cc @aleksproger

**Comment by aleksproger** [comment]
Yeah, we can close it now
