### ISSUE TITLE
Can't build for macCatalyst SPM(library, plugin, executable)

### ISSUE THREAD

**Issue by zunda-pixel** [apple/swift-package-manager#6619]
### Description

There is a package that uses a plugin to execute an executable and generate code. The configuration is such that a library uses the code generated by that plugin. While it can be built on iOS and macOS, it fails to build on macCatalyst.

The error is simple that the directory doesn't exist. Even when checking through Finder, the directory was not created.
```
sandbox-exec: execvp() of '//Users/zunda/Documents/GitHub/SampleLibrary/DerivedData/SampleLibrary/Build/Products/Debug/SampleExec' failed: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

### Steps to reproduce

Code: https://github.com/zunda-pixel/SampleLibrary
Process: Clean(Shift + Command + K) And Build

![image](https://github.com/apple/swift-package-manager/assets/47569369/1b633ca5-53b5-434e-a8cb-0d9a9030925b)

### Swift & OS version (output of `swift --version ; uname -a`)

```
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
Darwin zundas-MacBook-Air.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103 arm64
```

**Comment by neonichu** [comment]
I believe this is a known Xcode issue, cc @abertelrud

**Comment by zunda-pixel** [comment]
Xcode 15 beta 1(15A5160n) has same issue.

**Comment by neonichu** [comment]
Thanks for your report, but please file it through http://feedbackassistant.apple.com/ since the SwiftPM project doesn't track issues in Xcode.

**Comment by zunda-pixel** [comment]
I reported through http://feedbackassistant.apple.com/
but no response...

**Comment by robaho** [comment]
@neonichu  Is there any public comment from Apple on this? What about a work around so that the script checks the other directory? With the https://github.com/SwiftyLab/MetaCodable project, if I copied the binary from the Debug_maccatalyst to the Debug directory, it works correctly.

Not being able to use a swift package with a plugin with MacCatalyst seems like a critical problem.
