### ISSUE TITLE
Parallel test output needs more newlines

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-package-manager#6625]
### Description

If I run `swift test --parallel` on my project with a failing test, the output looks like this:

```
...
[277/278] Testing ValCommandTests.ValCommandTests/testBinary
[278/278] Testing ValTests.TypeCheckerTests/testTypeChecker
Test Suite 'Selected tests' started at 2023-05-27 08:57:28.226Test Suite 'ValPackageTests.xctest' started at 2023-05-27 08:57:28.228Test Suite 'TypeCheckerTests' started at 2023-05-27 08:57:28.228Test Case '-[ValTests.TypeCheckerTests testTypeChecker]' started./Users/dave/src/val.1/Tests/ValTests/TestCases/TypeChecking/While.val:1: error: -[ValTests.TypeCheckerTests testTypeChecker] : compilation stages succeeded, but failure was expected/Users/dave/src/val.1/Tests/ValTests/TestCases/TypeChecking/While.val:10: error: -[ValTests.TypeCheckerTests testTypeChecker] : missing expected diagnostic: 'incompatible types 'Int' and 'Bool''Test Case '-[ValTests.TypeCheckerTests testTypeChecker]' failed (6.082 seconds).Test Suite 'TypeCheckerTests' failed at 2023-05-27 08:57:34.310.
	 Executed 1 test, with 2 failures (0 unexpected) in 6.082 (6.082) secondsTest Suite 'ValPackageTests.xctest' failed at 2023-05-27 08:57:34.310.
	 Executed 1 test, with 2 failures (0 unexpected) in 6.082 (6.083) seconds
Test Suite 'Selected tests' failed at 2023-05-27 08:57:34.310.
	 Executed 1 test, with 2 failures (0 unexpected) in 6.082 (6.085) seconds
```

If I omit `--parallel`, the failure looks something like this, which is easily parsed by humans and tools:

```
...
Test Case '-[UtilsTests.ThreeValuedBitTests testNot]' passed (0.000 seconds).
Test Case '-[UtilsTests.ThreeValuedBitTests testOr]' started.
Test Case '-[UtilsTests.ThreeValuedBitTests testOr]' passed (0.000 seconds).
Test Suite 'ThreeValuedBitTests' passed at 2023-05-27 09:00:14.224.
	 Executed 3 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'TypeCheckerTests' started at 2023-05-27 09:00:14.224
Test Case '-[ValTests.TypeCheckerTests testTypeChecker]' started.
/Users/dave/src/val.1/Tests/ValTests/TestCases/TypeChecking/While.val:1: error: -[ValTests.TypeCheckerTests testTypeChecker] : compilation stages succeeded, but failure was expected
/Users/dave/src/val.1/Tests/ValTests/TestCases/TypeChecking/While.val:10: error: -[ValTests.TypeCheckerTests testTypeChecker] : missing expected diagnostic: 'incompatible types 'Int' and 'Bool''
Test Case '-[ValTests.TypeCheckerTests testTypeChecker]' failed (6.011 seconds).
Test Suite 'TypeCheckerTests' failed at 2023-05-27 09:00:20.234.
	 Executed 1 test, with 2 failures (0 unexpected) in 6.011 (6.011) seconds
Test Suite 'ValCommandTests' started at 2023-05-27 09:00:20.234
Test Case '-[ValCommandTests.ValCommandTests testBinary]' started.
Test Case '-[ValCommandTests.ValCommandTests testBinary]' passed (0.291 seconds).
...
```

### Expected behavior

Failures should be output on their own lines.  See also #6566; oh, the irony!

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.8.0

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
Darwin DaveA-MBP14.localdomain 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

**Comment by compnerd** [comment]
This may be a XCTest issue (where it does not normally emit a newline).  But, I agree, this would be wonderful.

**Comment by grynspan** [comment]
Let me see what I can do here.

**Comment by grynspan** [comment]
(I think! Gosh, GitHub is picky about formatting.)

**Comment by dabrahams** [comment]
@grynspan I'm unclear on how this can be a dup of #6566, which is about too many/random newlines and exclusively **non-parallel builds**, while this one is about not enough newlines (at a minimum) and only parallel builds.

**Comment by grynspan** [comment]
The root cause of both issues is that a 1KB buffer was being artificially imposed and that it inserted its own newlines (and ignored newlines from calling code.) The fix for that issue should have addressed both. If you're still seeing an issue with that fix in place, feel free to reopen.

**Comment by grynspan** [comment]
> And then why it's closed as "not planned" instead of "it's a dup", also unclear.

You would have to ask the GitHub folks; they consider "dup" to fall under the "not planned" category. 🙂

<img width="318" alt="Screenshot 2024-01-17 at 7 09 49 PM" src="https://github.com/apple/swift-package-manager/assets/4145863/8eca7c5f-741c-4eb4-8ae8-9fe45981eb2e">

**Comment by dabrahams** [comment]
Thanks for all the explanation!
