### ISSUE TITLE
Binary target to reference resources bundle

### ISSUE THREAD

**Issue by maheshbijapur** [apple/swift-package-manager#6651]
### Description

I've a Objective C SDK, which I was able to convert to XCFramework. I can publish it in cocoapods, however I am not able to publish the same in SPM as a binary target since it has resources bundle which it is not able to locate. 

Following is the format in cocoapods. 

`s.resource_bundles 	  = {
    'MYResources' => [
        'ResourcePod/**/*.{png,storyboard}'
    ]
} `

Please suggest.

**Comment by neonichu** [comment]
Is there a reason why you aren't including the resources as part of your XCFramework?

**Comment by maheshbijapur** [comment]
@neonichu Yes, my XCFramework is made from binaries (.a) & headers. Not actually a framework.

**Comment by neonichu** [comment]
Ah I see, I think [this](https://forums.swift.org/t/swiftpm-binary-target-resource-bundles/57178/7) describes my stance here. We really need Xcode to extend the XCFramework format to support this use case rather than SwiftPM essentially inventing its own dialect for XCFrameworks here.

**Comment by maheshbijapur** [comment]
Thanks @neonichu, so can you confirm if is it not possible to add support? or is their any alternative.?

**Comment by hwbricker** [comment]
Hello, I have the same situation. The third-party library xcframework and bundle I reference are separated. Will you consider letting SwiftPM support this scenario in the future?
