### ISSUE TITLE
Plugin with executableTarget doesn't work when we archive iOS App

### ISSUE THREAD

**Issue by PoissonBallon** [apple/swift-package-manager#6658]
### Description

When you want to use a plugin as a build step along with an executable target.
It works well during debug but not when we launch an archive.
The plugins doesn't find the binary

The Package.swift : 
```swift
// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "AppConfigKit",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        .library( name: "AppConfigKit", targets: ["AppConfigKit"])
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.2.2"),
        .package(url: "https://github.com/ReactiveX/RxSwift.git", from: "6.5.0"),
        .package(url: "https://github.com/Swinject/Swinject.git", from: "2.7.1"),
        .package(url: "https://github.com/firebase/firebase-ios-sdk", .upToNextMinor(from: "8.15.0")),
        .package(url: "https://github.com/SwiftGen/SwiftGenPlugin", from: "6.6.0")
    ],
    targets: [
        .target(
            name: "AppConfigCatalog"
        ),
        .target(
            name: "AppConfigCommon"
        ),
        .executableTarget(
            name: "AppConfigObfuscator",
            dependencies: [
                .target(name: "AppConfigCommon"),
                .product(name: "ArgumentParser", package: "swift-argument-parser")
            ]
        ),
        .plugin(
            name: "AppConfigPlugin",
            capability: .buildTool(),
            dependencies: [.target(name: "AppConfigObfuscator")]
        ),
        .target(
            name: "AppConfigKit",
            dependencies: [
                .product(name: "RxSwift", package: "RxSwift"),
                .product(name: "RxCocoa", package: "RxSwift"),
                .product(name: "Swinject", package: "Swinject"),
                .product(name: "FirebaseRemoteConfig", package: "firebase-ios-sdk"),
                .target(name: "AppConfigCommon")
            ],
            resources: [
                .copy("Assets/Images.xcassets")
            ],
            plugins: [
                .plugin(name: "AppConfigPlugin"),
                .plugin(name: "SwiftGenPlugin", package: "SwiftGenPlugin")
            ]
        )
    ]
)

```

### Expected behavior

The plugin should work.

### Actual behavior

The plugin doesn't find the executable. 

```
sandbox-exec: execvp() of '//Users/allanvialatte/Library/Developer/Xcode/DerivedData/Company-gqfwhoeacbgyswapkicevjpjcgsr/Build/Intermediates.noindex/ArchiveIntermediates/CompanyApp/BuildProductsPath/CompanyApp/AppConfigObfuscator' failed: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

### Steps to reproduce

1. Create a package with a `.plugin` and an `.executableTarget` 
2. Archive iOS App which depends on the package

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.8.1

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
Darwin Macbook-Pro-M1.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64

**Comment by neonichu** [comment]
My guess would be that this might be related to custom build configurations, as I do see `BuildProductsPath/CompanyApp` in the path, which by default would be `BuildProductsPath/Release`. 

Do you see the executable in the path `/Users/allanvialatte/Library/Developer/Xcode/DerivedData/Company-gqfwhoeacbgyswapkicevjpjcgsr/Build/Intermediates.noindex/ArchiveIntermediates/CompanyApp/BuildProductsPath/Release/AppConfigObfuscator` by any chance?

In any case, this seems Xcode specific, cc @abertelrud

**Comment by PoissonBallon** [comment]
@neonichu thanks for your help 

To answer you : 


### Script path : 
`
    /bin/sh -c /Users/allanvialatte/Library/Developer/Xcode/DerivedData/Shopmium-gqfwhoeacbgyswapkicevjpjcgsr/Build/Intermediates.noindex/ArchiveIntermediates/ShopmiumSandbox/IntermediateBuildFilesPath/AppConfigKit.build/ShopmiumSandbox-iphoneos/AppConfigKit_AppConfigKit.build/Script-9386591236704714098.sh
`

### Content : 

```bash
#!/bin/bash
/usr/bin/sandbox-exec -p "(version 1)
(deny default)
(import \"system.sb\")
(allow file-read*)
(allow process*)
(allow file-write*
    (subpath \"/private/tmp\")
    (subpath \"/private/var/folders/4k/kldjrlls46z9r2k4cjz_j0bh0000gn/T\")
)
(deny file-write*
    (subpath \"/Users/allanvialatte/Developer/shopmium-org/shopmium-ios/app/Packages/Foundation/AppConfigKit\")
)
(allow file-write*
    (subpath \"/Users/allanvialatte/Library/Developer/Xcode/DerivedData/Shopmium-gqfwhoeacbgyswapkicevjpjcgsr/SourcePackages/plugins/appconfigkit.output/AppConfigKit/AppConfigPlugin\")
)
" "/${BUILD_DIR}/${CONFIGURATION}/AppConfigObfuscator" /Users/allanvialatte/Developer/shopmium-org/shopmium-ios/app/Packages/Foundation/AppConfigKit/Sources/AppConfigCatalog/appconfig-private.json"
```

### Error message : 

`
sandbox-exec: execvp() of '//Users/allanvialatte/Library/Developer/Xcode/DerivedData/Shopmium-gqfwhoeacbgyswapkicevjpjcgsr/Build/Intermediates.noindex/ArchiveIntermediates/ShopmiumSandbox/BuildProductsPath/ShopmiumSandbox/AppConfigObfuscator' failed: No such file or directory
`

### Executable path : 

`
/Users/allanvialatte/Library/Developer/Xcode/DerivedData/Shopmium-gqfwhoeacbgyswapkicevjpjcgsr/Build/Intermediates.noindex/ArchiveIntermediates/ShopmiumSandbox/BuildProductsPath/ShopmiumSandbox/AppConfigObfuscator
`

But it's a symbolic link to : 
`
AppConfigObfuscator -> ../../IntermediateBuildFilesPath/UninstalledProducts/macosx/AppConfigObfuscator
`

But in this folder we have nothings (no executable)

**Comment by PoissonBallon** [comment]
FYI it's look like this issue too : 
[[Package Manager executable not available when building for platforms other than macOS](https://forums.swift.org/t/package-manager-executable-not-available-when-building-for-platforms-other-than-macos/56279)](https://forums.swift.org/t/package-manager-executable-not-available-when-building-for-platforms-other-than-macos/56279/2)

**Comment by neonichu** [comment]
Thanks for your report, but please file it through http://feedbackassistant.apple.com/ since the SwiftPM project doesn't track issues in Xcode.

**Comment by maxkazakov** [comment]
I have a very similar issue when archiving for simulator using the following command:
```
xcodebuild archive \
  -workspace ${WORKSPACE} \
  -scheme ${SCHEME} \
  -sdk iphonesimulator \
  -archivePath "${ARCHIVES_PATH}/ios_simulators.xcarchive" \
  SKIP_INSTALL=NO
```

The error:
`sandbox-exec: execvp() of '/.../Library/Developer/Xcode/DerivedData/AdjoeWave-fcgudfeqvvujvffwqfgobeipgoua/Build/Intermediates.noindex/ArchiveIntermediates/AdjoeWaveSDK/BuildProductsPath/Release/version-gen-tool' failed: No such file or directory`

There's indeed no `Release` folder, but there's `Release-iphonesimulator`:

<img width="493" height="403" alt="Image" src="https://github.com/user-attachments/assets/400c22dc-b103-477d-815d-83ecc8f8df7b" />


At the same time, when building for iPhone devices, the `Release` folder is generated, and `version-gen-tool` can be found:

<img width="506" height="277" alt="Image" src="https://github.com/user-attachments/assets/76a398e2-0eec-4a45-a86b-2b4573b796c6" />

I use Xcode 16.4 and don't have any special configurations for the build scripts; it clearly looks like some sort of bug, but I'm not sure whether it's related to SwiftPM or Xcode.
———

Update: I found the answer here https://elegantchaos.com/2024/10/11/xcodebuild-platforms-and-plugins.html
