### ISSUE TITLE
Using storyboard references to a storyboard in a swift package doesn't work.

### ISSUE THREAD

**Issue by tychop** [apple/swift-package-manager#6664]
### Description

I have the Main storyboard in my app that has a storyboard reference to a storyboard located in the swift package.
I've added the storyboard name in the Attributes Inspector for the storyboard reference.
I've added "MyPackageName-MyPackageName-resources" in the Bundle field of the Attributes Inspector for the storyboard reference.

### Expected behavior

I expect the storyboard name to be present in the pulldownlist in the Attributes Inspector for the storyboard reference and the app not to crash with the message mentioned in the 'Actual behavior'

### Actual behavior

The storyboard name does not get resolved, and I get a crash:

```*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'ReportList' in bundle NSBundle </Users/klm47954/Library/Developer/CoreSimulator/Devices/FAE7557F-9840-4571-A03A-D4C861CA7835/data/Containers/Bundle/Application/B641F0FC-B27E-472D-9B1F-E7EB570133A7/eForms.app>```

### Swift Package Manager version/commit hash

5.7

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
Darwin P0WNJPXX0L.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

**Comment by neonichu** [comment]
The error suggests that the storyboard is not being looked up in the resource bundle but in the main bundle. 

I don't know if that is a mistake on your end or a bug somewhere in Xcode. I suggest filing a report through http://feedbackassistant.apple.com since the SwiftPM open source project doesn't deal with storyboards directly.

**Comment by tychop** [comment]
Thanks for the suggestion.
I reported the Issue to Apple.
