### ISSUE TITLE
`swift build` is creating `.modulemap` files significantly before building the corresponding module

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-package-manager#6671]
When building a package, it appears like all module maps are created at the start of the entire build, instead of when the corresponding module is being built. This leaves a time period in which the module map exists, but the header it references (or the `.swiftmodule` that should be used if the module is being used from Swift) don’t exist yet. In that time period, sourcekitd will complain that it `could not build Objective-C module` because the header file referenced by the modulemap doesn’t exist yet.

I think the module maps should only be created once SwiftPM starts building that module and not at the start of the entire build, reducing the time period in which you see the `could not build Objective-C module` error. 

See https://github.com/swift-server/vscode-swift/issues/138#issuecomment-1609261916

**Comment by neonichu** [comment]
Yah, I agree. This also leads to confusing build errors when there are unexpressed dependencies. I recently did some work to move generating things like link file lists during the build instead of eagerly, maybe that could be leveraged here as well.

**Comment by compnerd** [comment]
@neonichu depends on the content ... if we do not need the sources and targets, we should be able to do that (I ran into that limitation recently trying to clean up the output file map emission).

**Comment by tomerd** [comment]
@ahoppen this seems to be the same as https://github.com/apple/swift-package-manager/issues/5925? if so, should we close this one and track in the original?

**Comment by ahoppen** [comment]
Yes, this should be the same underlying issue. Feel free to dupe it whichever way you want.

**Comment by neonichu** [comment]
Thanks, closing this one in favor of the older https://github.com/apple/swift-package-manager/issues/5925
