### ISSUE TITLE
Target with copyable resources fails to build on macOS

### ISSUE THREAD

**Issue by BradLarson** [apple/swift-package-manager#6672]
### Description

In nightly Swift toolchain snapshots after 2023-05-25, a simple project that has a target with `.copy()` resources and any Swift source files will fail to build at the command line on macOS (the same will succeed on Linux). Upon invoking `swift build`, an error message like 

```
<unknown>:0: error: error opening '/Users/larson/Developer/TestResources/.build/arm64-apple-macosx/debug/SharedResources.build/Sources/myfile.swift.o' for output: /Users/larson/Developer/TestResources/.build/arm64-apple-macosx/debug/SharedResources.build/Sources/myfile.swift.o: Not a directory
```

will be printed and the build will fail. A sample project that exhibits this behavior is attached below.

This appears to be due to the changes in PR #6573. Swift nightly toolchains of 2023-05-25 and prior build this kind of project correctly, and those of 2023-05-28 and newer do not. What appears to be happening is that a `sources` auxiliary file is being written in a place where there normally would be a `Sources` directory and this causes problems on the case-insensitive file system of macOS (but Linux evades this). To support this, in a `swift build -vvv` invocation, I see the following lines:

```
Write auxiliary file /Users/larson/Developer/TestResources/.build/arm64-apple-macosx/debug/SharedResources.build/sources
Copying /Users/larson/Developer/TestResources/SharedResources/Files
```

That first line is missing when a toolchain prior to PR #6573 is used.

### Expected behavior

The project should build cleanly at the command line on macOS.

### Actual behavior

It errors out on macOS with

```
<unknown>:0: error: error opening '/Users/larson/Developer/TestResources/.build/arm64-apple-macosx/debug/SharedResources.build/Sources/myfile.swift.o' for output: /Users/larson/Developer/TestResources/.build/arm64-apple-macosx/debug/SharedResources.build/Sources/myfile.swift.o: Not a directory
```

### Steps to reproduce

1. Unzip the following project on a macOS system with a Swift nightly toolchain of 2023-05-28 or newer (or SwiftPM after PR #6573):
[TestResources.zip](https://github.com/apple/swift-package-manager/files/11900388/TestResources.zip)
2. Run `swift build` in the project directory.

### Swift Package Manager version/commit hash

8bf6bd7 or newer

### Swift & OS version (output of `swift --version ; uname -a`)

Swift nightly toolchain snapshot 2023-05-28 and newer
macOS 13.4

**Comment by BradLarson** [comment]
cc @compnerd

**Comment by neonichu** [comment]
I wonder here the extra `/Sources` comes from? I believe the path for the object file is supposed to be `.build/arm64-apple-macosx/debug/SharedResources.build/myfile.swift.o` in this case.

**Comment by neonichu** [comment]
Oh I see, we're using the entire target relative file path to construct the paths to the object files. This feels like a pre-existing bug that just happens to be hit here because the target contains a `Sources` subdirectory which clashes with the name for the sources file list.
