### ISSUE TITLE
Swift plugins are incorrectly built using cross compilation sdk

### ISSUE THREAD

**Issue by rauhul** [apple/swift-package-manager#6673]
### Description

Package plugins are incorrectly built using target sdk settings when using the `--experimental-swift-sdk` flag.

This results in the plugin failing to build in my case because my cc SDK doesn't contain a module required for the plugin (Foundation). Additionally my sdk has a toolset.json that uses a number of compiler and linker flags entirely incompatible with the host platform.

**Comment by rauhul** [comment]
cc @MaxDesiatov

**Comment by neonichu** [comment]
IIRC, we are already building plugins in a separate build invocation, with parameters created via [this method](https://github.com/apple/swift-package-manager/blob/main/Sources/SPMBuildCore/BuildParameters.swift#L360). So I *think* we "just" need to tweak that to do the right thing.
