### ISSUE TITLE
Add configuration support for cxxExtension

### ISSUE THREAD

**Issue by figitaki** [apple/swift-package-manager#6681]
### Description

I'm trying to build a C++ package that requires support for C++14 extensions. After digging around in the source code, it seems like there's internal support for passing `-std=c++14` through to clang, however I cannot set that option in the `Package.swift`. I'm curious if it would be possible to add an option to pass the cxxExtension through via the `.cxxSettings` enum.

### Expected behavior

I've added a `Package.swift` to the [tree-sitter-norg](https://github.com/nvim-neorg/tree-sitter-norg) project. I would expect this package to compile fine since this exact configuration has been used in a variety of other `tree-sitter` grammar projects which use c++ code. 

### Actual behavior

I get a compilation error since the source code uses some c++14 extensions.

### Steps to reproduce

```
git clone https://github.com/figitaki/tree-sitter-norg && cd tree-sitter-norg
swift build
```

### Swift & OS version (output of `swift --version && uname -a`)

```
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: x86_64-apple-macosx13.0
Darwin
```

**Comment by neonichu** [comment]
This should be possible through the [cxxlanguagestandard](https://developer.apple.com/documentation/packagedescription/package/cxxlanguagestandard) parameter
