### ISSUE TITLE
`swift-test list --skip-build` builds SwiftPM plugins

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-package-manager#6683]
When invoking `swift-test list --skip-build`, SwiftPM builds all plugins, even though it was explicitly requested that no build should be performed. This appears to be the cause of https://github.com/apple/sourcekit-lsp/issues/676.

Steps to reproduce.
1. `git clone https://github.com/adam-fowler/soto-codegenerator-plugin-test`
2. `/Library/Developer/Toolchains/swift-5.9-DEVELOPMENT-SNAPSHOT-2023-07-06-a.xctoolchain/usr/bin/swift-test list --skip-build`
3. Notice that we get log output about plugins being built and `ls .build/plugins/` contains build artifacts

**Comment by neonichu** [comment]
Looks like `getBuildDescription()` calls `plan()` which unconditionally compiles and invokes plugins. Seems like we need to make the build system itself aware of the `--skip-build` option instead of just trying to not invoke `build()` on it from the outside.

**Comment by compnerd** [comment]
This may be related to https://github.com/apple/swift-package-manager/issues/6596
