### ISSUE TITLE
Internal inconsistency error (didStartTask)

### ISSUE THREAD

**Issue by BarredEwe** [apple/swift-package-manager#6705]
### Description

When **Package.swift** contains a plugin that generates code using `.prebuildCommand'. this leads to a build error:

```swift
Internal inconsistency error (didStartTask): targetID (174) not found in _activeTargets.
Internal inconsistency error (didEndTask): '12' missing from _activeTasks.
```

For example [SwiftGenPlugin](https://github.com/SwiftGen/SwiftGenPlugin) has this issue https://github.com/SwiftGen/SwiftGenPlugin/issues/15
Or others plugin like [Sourcery](https://github.com/krzysztofzablocki/Sourcery).

To get rid of this error, you need to call the build cleanup and rebuild the project.

There are also other discussions of a similar problem:
- [forums.swift.org](https://forums.swift.org/t/internal-inconsistency-error-didstarttask/61194)
- [stackoverflow.com](https://stackoverflow.com/questions/76014787/internal-inconsistency-error-didstarttask)

### Expected behavior

Expected Behavior:
The build process should complete successfully without any internal inconsistency errors.

### Actual behavior

Actual Behavior:
Xcode displays the internal inconsistency error message and subsequent builds fail to produce the expected result, launching stale products instead.

### Steps to reproduce

1. Install and configure [SwiftGenPlugin](https://github.com/SwiftGen/SwiftGenPlugin) in Xcode.
2. Make changes to the build plan, such as adding a file, or start a build during Xcode's indexing stage.
3. Observe the build error message:
  ```swift
  Internal inconsistency error (didStartTask): targetID (174) not found in _activeTargets.
  Internal inconsistency error (didEndTask): '12' missing from _activeTasks.
  ```

### Swift Package Manager version/commit hash

5.7-5.9(latest)

### Swift & OS version (output of `swift --version ; uname -a`)

Xcode version: 14.3.1 
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
Darwin barredewe 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

**Comment by neonichu** [comment]
This looks like output from XCBuild, so this should be Xcode-specific. cc @abertelrud

**Comment by pyrtsa** [comment]
This definitely looks like a bug around XCBuild, and it's still an issue in Xcode 15.0 RC. The build error strings originate from `Xcode.app/Contents/PlugIns/XCBuildSupportCore.ideplugin/Contents/MacOS/XCBuildSupportCore`, but it's near-impossible for us to debug it further, because XCBuildSupportCore is closed source.

We're hit by this issue almost daily. Having to first realise that you'd been debugging an old build all along because the build silently failed, and then clean all and rebuild… Can't say it's a great developer experience.

**Comment by neonichu** [comment]
Thanks for your report, but please file it through http://feedbackassistant.apple.com/ since the SwiftPM project doesn't track issues in Xcode and/or Xcode Cloud.

**Comment by setoelkahfi** [comment]
We encountered this today using GitHub runner `macos-13-xl` Xcode 15. Strangely our workflow was marked as successful.

**Comment by rpassis** [comment]
Xcode 15.1 beta reports the inconsistency as an error now which is a step on the right direction 👍

**Comment by marcprux** [comment]
Still a bug in Xcode 15.1.

This is a crippling problem.

**Comment by joshuawright11** [comment]
I've also found that closing and re-opening Xcode is the quickest way (faster than clean, slower than clear all issues) to (usually) resolve this issue.

**Comment by jsimonlane** [comment]
Seconding this, this dramatically slows down dev time

**Comment by PeterSenyszyn** [comment]
Coming in here to add another +1, extremely annoying and crippling to dev time. Only way around it for me is to do a clean / full rebuild.

**Comment by marcprux** [comment]
> Coming in here to add another +1, extremely annoying and crippling to dev time. Only way around it for me is to do a clean / full rebuild.

It has also gotten much much worse with Xcode 15.3. The only "improvement" is that the message now appends: "Build again to continue". Thanks, I will. 🙄 

<img width="1442" alt="Screenshot 2024-03-13 at 17 27 13" src="https://github.com/apple/swift-package-manager/assets/659086/0aaa33b0-d858-4860-ac58-beb6e2073d70">

Can someone from Apple please escalate this internally? Feedback reports are just ignored.

**Comment by PeterSenyszyn** [comment]
> > Coming in here to add another +1, extremely annoying and crippling to dev time. Only way around it for me is to do a clean / full rebuild.
> 
> It has also gotten much much worse with Xcode 15.3. The only "improvement" is that the message now appends: "Build again to continue". Thanks, I will. 🙄
> 
> <img alt="Screenshot 2024-03-13 at 17 27 13" width="1442" src="https://private-user-images.githubusercontent.com/659086/312627392-0aaa33b0-d858-4860-ac58-beb6e2073d70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNjU2MTMsIm5iZiI6MTcxMDM2NTMxMywicGF0aCI6Ii82NTkwODYvMzEyNjI3MzkyLTBhYWEzM2IwLWQ4NTgtNDg2MC1hYzU4LWJlYjZlMjA3M2Q3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QyMTI4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDE3ZTZhYjhhNzZiMDFkZmU3ZGVkMjZkNjQ5YzE5ODY3NDg3ODQyMTU5ZWE1Y2EwMGMxNjU0YmQ3ZjM3MzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DgoscRhRi8GE1h2eOLlbYsSkCT1_kO38RDz3qFIf4zY">
> Can someone from Apple please escalate this internally? Feedback reports are just ignored.

It got worse for me as well in 15.3. Before it would happen every other recompile, but now it happens every time for me.

**Comment by sebj** [comment]
Has anyone filed feedback with an ID to mention/dupe?

**Comment by jaredsinclair** [comment]
@sebj Yes here: `FB13368618`

**Comment by marcprux** [comment]
FTR, still a major problem in Xcode 15.4 released yesterday.

**Comment by jaminguy-jh** [comment]
Yes, I've encountered it several times this AM on Xcode 15.4.

**Comment by bilousoleksandr** [comment]
Have the similat issue with Xcode 15.4.0, we use both swiftGen and sourcery plugin for code generationg in Xcode.

**Comment by BarredEwe** [comment]
In [Xcode 16 Beta](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes#Resolved-Issues) it seems to have been fixed: 

> Fixed an issue where projects using SwiftPM build tool plugins would sometimes report internal inconsistency errors when building. (121851192) (FB13565986)
