### ISSUE TITLE
Availability of new PackagePlugin APIs

### ISSUE THREAD

**Issue by benrimmington** [apple/swift-package-manager#6733]
Do the APIs introduced by @neonichu in apple/swift-package-manager#6110 need `@available` annotations?

(And should the APIs be moved to the [Sources/PackagePlugin/Utilities.swift][1] file?)

[1]: <https://github.com/apple/swift-package-manager/blob/main/Sources/PackagePlugin/Utilities.swift>

**Comment by tomerd** [comment]
@neonichu these are some good questions

**Comment by neonichu** [comment]
Yah, it seems like we should add availability here, thanks for catching that. Moving the code also sounds like a reasonable suggestion.
