### ISSUE TITLE
Target (not products) conflicts from dependencies

### ISSUE THREAD

**Issue by blindspotbounty** [apple/swift-package-manager#6771]
### Description

SwiftPM have module aliases and it works for products. 

### Expected behavior

I would expect that products or dependencies might conflict between different packages.

But local targets that are not products (so, not exposed) should not be clashing between each other.

### Actual behavior

Surprisingly, targets are clashing as well (while should not be seeing).

As a lightweight example there are 3 projects:
1. FooA (contains FooAA product + Helpers targets)
2. FooB (contains FooBB product + Helpers targets)
3. FooC (depends on FooAA and FooBB)

`FooA/Package.swift`:
```swift
// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "FooA",
    platforms: [
        .macOS(.v13),
        .iOS(.v16)
    ],
    products: [
        .library(
            name: "FooAA",
            targets: ["FooAA"]
        ),
    ],
    dependencies:
    [
    ],
    targets: [
        .target(
            name: "Helpers"
        ),
        .target(
            name: "FooAA",
            dependencies: [
                "Helpers"
            ]
        ),
    ]
)
```

`FooB/Package.swift`:
```swift
// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "FooB",
    platforms: [
        .macOS(.v13),
        .iOS(.v16)
    ],
    products: [
        .library(
            name: "FooBB",
            targets: ["FooBB"]
        ),
    ],
    dependencies:
    [
    ],
    targets: [
        .target(
            name: "Helpers"
        ),
        .target(
            name: "FooBB",
            dependencies: [
                "Helpers"
            ]
        ),
    ]
)
```
and `FooB/Package.swift`:
```swift
// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "FooC",
    platforms: [
        .macOS(.v13),
        .iOS(.v16)
    ],
    products: [
        .library(
            name: "FooCC",
            targets: ["FooCC"]
        ),
    ],
    dependencies:
    [
        .package(path: "../FooA"),
        .package(path: "../FooB"),
    ],
    targets: [
        .target(
            name: "FooCC",
            dependencies: [
                .product(name: "FooAA", package: "FooA"/*, moduleAliases: ["Helpers": "__UNNEEDED_HELPERS"]*/),
                .product(name: "FooBB", package: "FooB"),
            ]
        ),
    ]
)
```

If I try to run `swift build`, it lead to error:
```
% swift build
error: multiple targets named 'Helpers' in: 'fooa', 'foob'; consider using the `moduleAliases` parameter in manifest to provide unique names
error: ExitCode(rawValue: 1)
[0/1] Planning build
```

### Steps to reproduce

Full example is located at: https://github.com/ordo-one/external-reproducers/tree/main/swift/dependencies
```
$ cd FooC/
$  swift build  
error: multiple targets named 'Helpers' in: 'fooa', 'foob'; consider using the `moduleAliases` parameter in manifest to provide unique names
```

### Swift Package Manager version/commit hash

Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100) Target: arm64-apple-macosx13.0

### Swift & OS version (output of `swift --version ; uname -a`)

% swift --version ; uname -a
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
Darwin <name> 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020 arm64

**Comment by neonichu** [comment]
Yes, that is expected. There is only a single namespace for modules, so they *do* conflict with each other, regardless of the package that they're in.

**Comment by blindspotbounty** [comment]
@neonichu could you advise whether some swift evolution pitch at forums exist for such scenario, please?
