### ISSUE TITLE
[SR-13136] swift test --filter doesn't work in snapshot

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-package-manager#6833]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13136      |
   |Radar             | None         |
   |Original Reporter | cukier (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

macos 10.15.4 (19E287)

swift-DEVELOPMENT-SNAPSHOT-2020-07-01-a.xctoolchain

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 95892b810a292f1d132251ac085b5ec5

  </details>

**Issue Description:**

Steps to reproduce:

-   boot your macos 10.15.4 (19E287) machine

-   download and install the snapshot from swift.org

-   create new package called \`NewPackage\`

-   try to run \`/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift test --filter='NewPackageTests.NewPackageTests/testExample'\` command to run a single test method

 

expected:

``` java
Test Suite 'Selected tests' started at 2020-07-03 00:49:06.032
Test Suite 'NewPackagePackageTests.xctest' started at 2020-07-03 00:49:06.032
Test Suite 'NewPackageTests' started at 2020-07-03 00:49:06.032
Test Case '-[NewPackageTests.NewPackageTests testExample]' started.
Test Case '-[NewPackageTests.NewPackageTests testExample]' passed (0.055 seconds).
Test Suite 'NewPackageTests' passed at 2020-07-03 00:49:06.087.
         Executed 1 test, with 0 failures (0 unexpected) in 0.055 (0.055) seconds
Test Suite 'NewPackagePackageTests.xctest' passed at 2020-07-03 00:49:06.087.
         Executed 1 test, with 0 failures (0 unexpected) in 0.055 (0.055) seconds
Test Suite 'Selected tests' passed at 2020-07-03 00:49:06.087.
         Executed 1 test, with 0 failures (0 unexpected) in 0.055 (0.056) seconds 
```

What happened:

``` java
[6/6] Linking NewPackagePackageTests
error: signalled(6): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2020-07-01-a.xctoolchain/usr/libexec/swift/pm/swiftpm-xctest-helper /Users/cukier/Desktop/NewPackage/.build/x86_64-apple-macosx/debug/NewPackagePackageTests.xctest /var/folders/9r/3t0y3zlj2l34w2t5vsgxz_7w0000gn/T/TemporaryFile.3Jzu9d output:
    dyld: Library not loaded: @rpath/XCTest.framework/Versions/A/XCTest
      Referenced from: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2020-07-01-a.xctoolchain/usr/libexec/swift/pm/swiftpm-xctest-helper
      Reason: image not found
   
```

**Comment by neonichu** [comment]
This is normal, because the toolchain does not come with XCTest.
