### ISSUE TITLE
Build tool plugins don't seem to run at all on Windows

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-package-manager#6850]
### Description

See the windows runs of https://github.com/hylo-lang/hylo/pulls/926 and https://github.com/hylo-lang/hylo/pulls/927 for two different examples.  It's not clear to me that the executable the plugins depend on is ever built either.

**Comment by neonichu** [comment]
This is basically the same as #6851, is that correct?

**Comment by dabrahams** [comment]
Possibly.  I've worked around that issue and just (without remembering I had filed this) filed an [issue](https://github.com/apple/swift-package-manager/issues/6859) for the next problem.  I suggest closing this one unless you want it for some reason.

**Comment by neonichu** [comment]
Closing in favor of #6851
