### ISSUE TITLE
Build plugin source code is included in executable built from generated code

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-package-manager#6864]
### Description

If you have a build plugin whose executable is built by SwiftPM then the build plugin source code is also linked with any executable built from code generated by this build plugin. 
eg
```swift
targets: [
    .executableTarget(
        name: "MyCodeGenerator"
    ),
    .plugin(
        name: "MyCodeGeneratorPlugin",
        capability: .buildTool(),
        dependencies: ["MyCodeGenerator"]
    )
]
```

### Expected behavior

I would expect that code not used in the final executable to not be included in it.

### Steps to reproduce

This uses the Soto Code generator as an example
1. `git clone https://github.com/adam-fowler/soto-codegenerator-plugin-test`
2. `cd soto-codegenerator-plugin-test`
3. `swift build`
4. `llvm-nm .build/debug/SNSTest | grep SotoCodeGenerator`

I would expect this to return nothing as the SotoCodeGenerator code is not used in the SNSTest executable but instead it prints out a load of symbols from the code generator build plugin.

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: x86_64-apple-macosx13.0
Darwin Adams-iMac-Pro-2.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64

**Comment by gwynne** [comment]
Can confirm this also happens with 5.9, both macOS (Xcode 15 beta 7) and Linux (current nightlies of 5.9 and main):
```
Xcode 15.0
Build version 15A5229h
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1)
Target: arm64-apple-macosx13.0
```
```
swift-5.9-DEVELOPMENT-SNAPSHOT-2023-08-24-a
Swift version 5.9-dev (LLVM 46ac717ed0ec21c, Swift 05fe36c7b352712)
Target: aarch64-unknown-linux-gnu
```
```
swift-DEVELOPMENT-SNAPSHOT-2023-08-25-a
Swift version 5.9-dev (LLVM cce90ed6f6829a7, Swift 11c45c9c3e2937e)
Target: aarch64-unknown-linux-gnu
```

**Comment by tomerd** [comment]
@neonichu I was under the impression this was fixed? or only on nightlies?

**Comment by rauhul** [comment]
Yes this should be fixed on main, see the series of PRs referenced by #6673

**Comment by adam-fowler** [comment]
I just tested this with latest `swiftlang/swift:nightly` docker image and it is still the case that build plugin code is being included in the final executable.

**Comment by neonichu** [comment]
Looks like your example is using tools-version 5.6, the new behavior is only active when using tools-version 5.9 or later.

**Comment by adam-fowler** [comment]
Oh yes, upping the tools-version to 5.9 works. Shame it can't be back ported. This only ever seems like a bug.

**Comment by neonichu** [comment]
We were just worried about the implications since it could mean existing packages would not build because they were relying on the bug.
