### ISSUE TITLE
Specify registry specific .netrc location in ~/.swiftpm/configuration/registries.json

### ISSUE THREAD

**Issue by dafangc-amazon** [apple/swift-package-manager#6865]
### Description

Currently we need to specify the `--netrc-file` option in every swift command to use the .netrc file on a custom path. It would be much more convenient if we only had to specify `--netrc-file` in the `swift package-registry login` command and Swift would automatically store the custom path in registries.json for reference. 

It would benefit users who don't want to store every credential in ~/.netrc, because they could use custom .netrc more easily without having to specify the path whenever resolving dependencies or building the project.

### Expected behavior

Swift would add new field in the json similar to below:
```
{
  "authentication" : {
    "https://example.com" : {
      "loginAPIPath" : "/registry-1/login",
      "type" : "token"
      "netrcPath": "/custom/path/.netrc"
    }
  },
  "registries" : {
    "default" : {
      "url" : "hhttps://example.com/registry-1"
    }
  },
  "version" : 1
}

### Actual behavior

_No response_

### Steps to reproduce

_No response_

### Swift Package Manager version/commit hash

_No response_

### Swift & OS version (output of `swift --version && uname -a`)

```
Swift version 5.8.1 (swift-5.8.1-RELEASE)
Target: x86_64-unknown-linux-gnu
```
```
5.4.250-173.369.amzn2int.x86_64
```

**Comment by yim-lee** [comment]
Another approach that we might consider is for SwiftPM to support custom auth provider that can be plugged in and used instead of `netrc` and Keychain.

**Comment by yim-lee** [comment]
Discussed with @dafangc-amazon/team. This is not needed for now, so closing this. Please reopen if there is a need for it in the future.
