### ISSUE TITLE
How to custom the file indentation like Xcode project?

### ISSUE THREAD

**Issue by miku1958** [apple/swift-package-manager#6889]
### Description

If I open the package in Xcode and change the file indentation, the next time I start it up it will reset to the Xcode setting.

### Expected behavior

I can change the file indentation in Xcode and keep it forever.

### Actual behavior

Next time I open the package, file indentation will reset to the Xcode setting.

### Swift Package Manager version/commit hash

5.8

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: x86_64-apple-macosx13.0
Darwin macbook 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

**Comment by neonichu** [comment]
Thanks for your report, but please file it through http://feedbackassistant.apple.com/ since the SwiftPM project doesn't track issues in Xcode.
