### ISSUE TITLE
SPM project: Xcode (only) reports non-existent dependency cycle

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-package-manager#6908]
### Description

If you check out the `xcode-only-bug` tag of [this project](https://github.com/dabrahams/TestGeneration/releases/tag/xcode-only-bug), open Package.swift in Xcode and hit cmd-U to run the tests, you'll get the attached [attached](https://github.com/apple/swift-package-manager/files/12629394/trace.txt) incorrect cycle error that isn't reported by `swift package build` with Swift Package Manager - Swift 5.8.1.

swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
Darwin davea-mbp16.corp.adobe.com 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

**Comment by neonichu** [comment]
Thanks for your report, but please file it through http://feedbackassistant.apple.com/ since the SwiftPM project doesn't track issues in Xcode.

**Comment by dabrahams** [comment]
https://feedbackassistant.apple.com/feedback/13188529
