### ISSUE TITLE
Package-level module aliases are not applied

### ISSUE THREAD

**Issue by fumoboy007** [apple/swift-package-manager#6911]
### Description

I have a package that needs to [alias](https://github.com/fumoboy007/msgpack-swift/blob/e17ad007e39a26cd3fcf4e9a605ccd4b25982887/Package.swift#L50-L52) a dependency’s module due to conflicting module names.

Currently, I am doing this at the product level like so:
```swift
.product(name: "MessagePack", package: "MessagePack", moduleAliases: [
   "MessagePack": "FlightSchoolMessagePack",
]),
```

This works, but I would like to do the alias at the package level like so:
```swift
let flightSchoolMessagePackDependency: PackageDescription.Package.Dependency =
   .package(url: "https://github.com/Flight-School/MessagePack.git", from: "1.2.4")
flightSchoolMessagePackDependency.moduleAliases = ["MessagePack": "FlightSchoolMessagePack"]

let package = Package(
   …
   dependencies: [
      flightSchoolMessagePackDependency,
   …
)
```

### Expected behavior

I expect the package-level module alias to be applied, similar to the product-level module alias.

### Actual behavior

The package manager returns an error:
> multiple targets named 'MessagePack' in: 'messagepack', 'msgpack-swift'; consider using the `moduleAliases` parameter in manifest to provide unique names

### Steps to reproduce

1. Download my [package](https://github.com/fumoboy007/msgpack-swift).
2. Switch to the `with-flight-school-dep` branch.
3. Replace the dependency `.package(url: "https://github.com/Flight-School/MessagePack.git", from: "1.2.4")` with a similar dependency that has the `moduleAliases` property specified.
4. Remove the `moduleAliases` parameter from `.product(name: "MessagePack", package: "MessagePack", moduleAliases: …)`.
5. `swift build`

### Swift Package Manager version/commit hash

swift-5.8.1-RELEASE

### Swift & OS version (output of `swift --version ; uname -a`)

```
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
Darwin Darrens-Mac.momahome 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64
```

**Comment by fumoboy007** [comment]
@elsh @tomerd Perhaps related to #6913? This one is 100% reproducible though.

**Comment by neonichu** [comment]
Do I understand correctly that this compiles?

```
let flightSchoolMessagePackDependency: PackageDescription.Package.Dependency =
   .package(url: "https://github.com/Flight-School/MessagePack.git", from: "1.2.4")
flightSchoolMessagePackDependency.moduleAliases = ["MessagePack": "FlightSchoolMessagePack"]
```

I would not expect that, IIRC we only defined module aliases at the product dependency level? cc @tomerd

**Comment by fumoboy007** [comment]
@neonichu The package-level property is defined [here](https://github.com/apple/swift-package-manager/blame/de8e6e8e416f0ddf66ded9bf9c9abafe9517f3c3/Sources/PackageDescription/PackageDependency.swift#L86-L89).

**Comment by elsh** [comment]
It was meant to be used as a property of a product dependency. It was declared `public` in Package.Dependency at the time it was added due to the need for intra-module visibility; there are other properties such as `.targetItem(name:...)` that were made `public` for the same reason even though they weren't meant to be visible to users. However, as of swift 5.9, a new access level called `package` is introduced, which limits visibility of such properties, so they can be hidden from users once modified with that access level.

**Comment by fumoboy007** [comment]
Hmm I guess we could/should have prefixed those symbols with an underscore to make that clear. When are we changing the access level to `package`? Shall we repurpose this issue to track that work?

**Comment by neonichu** [comment]
I don't think we can do that until the next release after 5.10, but we should be able to use `@spi` here in the meantime, I think?

**Comment by neonichu** [comment]
Actually seems like we can just make it internal. It may have been needed to be public because of how the old serialization code worked that I refactored in 5.9
