### ISSUE TITLE
SwiftPM build error with `update-checkout --tag swift-5.9-RELEASE`

### ISSUE THREAD

**Issue by thekief** [apple/swift-package-manager#6970]
### Description

When building the Swift 5.9 OSS release on a M2 macMini we get following issue while building:

```
...
[531/543] Compiling TSCUtility Archiver.swift
[532/546] Compiling TSCTestSupport AssertMatch.swift
[533/546] Compiling Basics Archiver.swift
[534/550] Compiling SPMLLBuild llbuild.swift
[535/550] Compiling SwiftOptions DriverKind.swift
[536/551] Compiling LLBuildManifest BuildManifest.swift
[537/551] Compiling PackageCollectionsSigning Certificate.swift
[538/551] Compiling PackageModel ArtifactsArchiveMetadata.swift
[539/555] Compiling PackageSigning CertificateStores.swift
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/SignatureProvider.swift:270:36: error: generic parameter 'some VerifierPolicy' could not be inferred
            let result = await CMS.isValidSignature(
                                   ^
/Users/ob1/swift5.9/swift-certificates/Sources/X509/CryptographicMessageSyntax/CMSOperations.swift:88:24: note: in call to function 'isValidSignature(dataBytes:signatureBytes:additionalIntermediateCertificates:trustRoots:policy:)'
    public static func isValidSignature<
                       ^
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/SignatureProvider.swift:284:30: error: cannot convert value of type 'PolicySet' (aka 'AnyPolicy') to expected argument type '() throws -> some VerifierPolicy'
                policy: self.buildPolicySet(configuration: verifierConfiguration, httpClient: self.httpClient)
                             ^
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/SignatureProvider.swift:300:92: error: cannot infer key path type from context; consider explicitly specifying a root type
                    return .certificateInvalid("failures: \(failure.validationFailures.map(\.policyFailureReason))")
                                                                                           ^
                                                                                            <#Root#>
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/SignatureProvider.swift:346:32: error: generic parameter 'Policy' could not be inferred
                var verifier = Verifier(rootCertificates: CertificateStore(trustRoots), policy: policySet)
                               ^
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/SignatureProvider.swift:346:32: note: explicitly specify the generic arguments to fix this issue
                var verifier = Verifier(rootCertificates: CertificateStore(trustRoots), policy: policySet)
                               ^
                                       <<#Policy: VerifierPolicy#>>
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/SignatureProvider.swift:346:97: error: cannot convert value of type 'PolicySet' (aka 'AnyPolicy') to expected argument type '() throws -> Policy'
                var verifier = Verifier(rootCertificates: CertificateStore(trustRoots), policy: policySet)
                                                                                                ^
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/SignatureProvider.swift:361:85: error: cannot infer key path type from context; consider explicitly specifying a root type
                            .certificateInvalid("failures: \(validationFailures.map(\.policyFailureReason))")
                                                                                    ^
                                                                                     <#Root#>
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/SigningEntity/SigningEntity.swift:19:10: warning: associated value 'recognized(type:name:organizationalUnit:organization:)' of 'Sendable'-conforming enum 'SigningEntity' has non-sendable type 'SigningEntityType'
    case recognized(type: SigningEntityType, name: String, organizationalUnit: String, organization: String)
         ^
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/SigningEntity/SigningEntity.swift:79:13: note: consider making enum 'SigningEntityType' conform to the 'Sendable' protocol
public enum SigningEntityType: String, Hashable, Codable {
            ^
                                                        , Sendable
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/VerifierPolicies.swift:23:90: warning: 'PolicySet' is deprecated: use PolicyBuilder to construct a custom policy
    func buildPolicySet(configuration: VerifierConfiguration, httpClient: HTTPClient) -> PolicySet {
                                                                                         ^
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/VerifierPolicies.swift:72:16: warning: 'PolicySet' is deprecated: use PolicyBuilder to construct a custom policy
        return PolicySet(policies: policies)
               ^
/Users/ob1/swift5.9/swiftpm/Sources/PackageSigning/VerifierPolicies.swift:72:16: warning: 'init(policies:)' is deprecated: use PolicyBuilder to construct a custom policy
        return PolicySet(policies: policies)
               ^
env SDKROOT=/Applications/Xcode_15.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk SWIFTCI_USE_LOCAL_DEPS=1 SWIFTPM_MACOS_DEPLOYMENT_TARGET=10.15 DYLD_LIBRARY_PATH=/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/bootstrap/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/tsc/lib:/Users/ob1/swift5.9/build/buildbot_osx/llbuild-macosx-arm64/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/yams/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-argument-parser/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-crypto/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-driver/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-system/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-collections/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-asn1/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-certificates/lib SWIFT_EXEC=/Users/ob1/swift5.9/swift-nightly-install/Library/Developer/Toolchains/swift-LOCAL-2023-09-19-a.xctoolchain/usr/bin/swiftc SWIFT_DRIVER_SWIFT_EXEC=/Users/ob1/swift5.9/swift-nightly-install/Library/Developer/Toolchains/swift-LOCAL-2023-09-19-a.xctoolchain/usr/bin/swiftc CC=/Users/ob1/swift5.9/swift-nightly-install/Library/Developer/Toolchains/swift-LOCAL-2023-09-19-a.xctoolchain/usr/bin/clang SWIFTPM_CUSTOM_LIBS_DIR=/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/bootstrap/pm /Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/bootstrap/bin/swift-bootstrap --build-path /Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64 --configuration release -Xswiftc -module-cache-path -Xswiftc /Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/module-cache -Xmanifest -module-cache-path -Xmanifest /Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/module-cache
--- bootstrap: error: Command '['env', 'SDKROOT=/Applications/Xcode_15.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk', 'SWIFTCI_USE_LOCAL_DEPS=1', 'SWIFTPM_MACOS_DEPLOYMENT_TARGET=10.15', 'DYLD_LIBRARY_PATH=/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/bootstrap/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/tsc/lib:/Users/ob1/swift5.9/build/buildbot_osx/llbuild-macosx-arm64/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/yams/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-argument-parser/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-crypto/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-driver/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-system/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-collections/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-asn1/lib:/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/swift-certificates/lib', 'SWIFT_EXEC=/Users/ob1/swift5.9/swift-nightly-install/Library/Developer/Toolchains/swift-LOCAL-2023-09-19-a.xctoolchain/usr/bin/swiftc', 'SWIFT_DRIVER_SWIFT_EXEC=/Users/ob1/swift5.9/swift-nightly-install/Library/Developer/Toolchains/swift-LOCAL-2023-09-19-a.xctoolchain/usr/bin/swiftc', 'CC=/Users/ob1/swift5.9/swift-nightly-install/Library/Developer/Toolchains/swift-LOCAL-2023-09-19-a.xctoolchain/usr/bin/clang', 'SWIFTPM_CUSTOM_LIBS_DIR=/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/bootstrap/pm', '/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/arm64-apple-macosx/bootstrap/bin/swift-bootstrap', '--build-path', '/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64', '--configuration', 'release', '-Xswiftc', '-module-cache-path', '-Xswiftc', '/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/module-cache', '-Xmanifest', '-module-cache-path', '-Xmanifest', '/Users/ob1/swift5.9/build/buildbot_osx/swiftpm-macosx-arm64/module-cache']' returned non-zero exit status 1.
```

There have been no modifications made to the source code.

### Expected behavior

The build of the toolchain finishes.

### Actual behavior

The build stops and exits.

### Steps to reproduce

- checkout Swift repository
- `utils/update-checkout --clone --tag  swift-5.9-RELEASE`
- `swift/utils/build-toolchain test_tc`
- wait

### Swift Package Manager version/commit hash

swift-5.9-RELEASE

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
Darwin ob2.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112 arm64

**Comment by MaxDesiatov** [comment]
The fact that you're using Apple Silicon CPU to build is unrelated.

I don't think that building SwiftPM with `update-checkout` and `build-toolchain` is a supported scenario outside of Swift CI. This is not how you build SwiftPM locally for development, at least in the vast majority of cases. For that, you can just clone this repository directly, check out `release/5.9` branch (or `main` if you need that one), and just run `swift build`.

If you insist on using `update-checkout`, you should use `--scheme release/5.9` option instead of `--tag swift-5.9-RELEASE`, as `swift-5.9-RELEASE` tag doesn't exist on all of the dependencies of SwiftPM, and `swift-certificates` is one of them. `--scheme release/5.9` will check out the correct versions for you, if you're targeting the 5.9 release.

Would you be able to confirm that this fixes the build issue for you?

**Comment by thekief** [comment]
Thank you for your fast answer. I will try it asap. If I may ask:

What is the Apple/Swift policy on tags? I expected the `swift-5.9-RELEASE` tag to be a buildable version that should compile without any problems (what also the common notion is I suppose when it comes to tags). Instead I need to rely on somehting that feels like a rolling release

**Comment by MaxDesiatov** [comment]
> I expected the `swift-5.9-RELEASE` tag to be a buildable version that should compile without any problems (what also the common notion is I suppose when it comes to tags).

That is the case for the Swift compiler itself, but not all dependencies of SwiftPM for example, hence not applicable to SwiftPM itself. If you're building just the compiler and core libraries without SwiftPM, you'll get reproducible builds with tags AFAIU.

>  Instead I need to rely on something that feels like a rolling release

`--scheme` argument passed to `update-checkout` is a rolling release, if I understand correctly what you're looking for. You can also see available schemes and tags/branches they pin in [the `update-checkout-config.json` file](https://github.com/apple/swift/blob/main/utils/update_checkout/update-checkout-config.json). But schemes don't provide reproducible builds, unfortunately.

**Comment by thekief** [comment]
@1 to be honest that is definitely not the answer I expected. I do not get the reason behind it but atleast now I know

@2 I actually want to build the tagged release, execuse the imprecise wording. I need to test some issues with an application I am currently developing and I supposed that the closest I can get to the Xcode 15 tools is the OSS release in the [apple/swift](https://github.com/apple/swift) repository

**Comment by MaxDesiatov** [comment]
> I actually want to build the tagged release, execuse the imprecise wording. I need to test some issues with an application I am currently developing and I supposed that the closest I can get to the Xcode 15 tools is the OSS release in the [apple/swift](https://github.com/apple/swift) repository

If you need a tagged release, you can download it from swift.org/download. What's the reasoning behind building it from scratch?

If you insist on building from source from a specific tag, as I said it's possible for the compiler and the core libraries, not possible for SwiftPM unfortunately. If the issue you're trying to reproduce is not caused by SwiftPM, you can just copy over `swift-build`, `swift-test` and other prebuilt SwiftPM binaries from swift.org/download packages.

Is there anything here to be resolved on the SwiftPM side though?

**Comment by MaxDesiatov** [comment]
Additionally, if using the prebuilt SwiftPM is not working out for you, you can check out the `swift-5.9-RELEASE` tag on the `swift-package-manager` repository clone and build it with `swift build`.

**Comment by thekief** [comment]
> you can check out the swift-5.9-RELEASE tag on the swift-package-manager repository clone 

Are you aware that your suggested tag is literally the one pulled by `utils/update-checkout --clone --tag  swift-5.9-RELEASE` (and yes I double checked the commit hashes)?

That is the tag I have issues with. I am aware that the CI build uses the local version that are sometimes newer but still.

Regarding the other suggestion: I tried to build the toolchain with `swiftpm` disabled and got some issues. I restarted the build and I will update you asap :)

**Comment by MaxDesiatov** [comment]
> Are you aware that your suggested tag is literally the one pulled by `utils/update-checkout --clone --tag swift-5.9-RELEASE` (and yes I double checked the commit hashes)?

Of course, I'm aware of that. That's the tag of SwiftPM checked out by `utils/update-checkout` though. As I mentioned previously, that script doesn't check out corresponding versions of SwiftPM dependencies, because the don't have the same tag. `swift build` will do that for you though, it will check out versions recorded in `Package.swift` of SwiftPM as of `swift-5.9-RELEASE`.

> That is the tag I have issues with. I am aware that the CI build uses the local version that are sometimes newer but still.

The issue is not with the SwiftPM tag, but with the lack of tags on SwiftPM dependencies that `utils/update-checkout` relies on. If you're using `swift build`, that lack of tags becomes irrelevant as it pulls correct versions of dependencies on its own into `.build` directory, without any intervention from `utils/update-checkout`.

**Comment by thekief** [comment]
btw, you mentioned something interesting up there:

`I don't think that building SwiftPM with update-checkout and build-toolchain is a supported scenario outside of Swift CI`

What do you think differs so much that we encounter the issue only on a local setup? If I understand it correctly, the issue is caused during the compilation of the Swift code. Is the Swift 5.9 release only compilable with Xcode 14? Do you happen to have insight with this?

**Comment by MaxDesiatov** [comment]
> What do you think differs so much that we encounter the issue only on a local setup? If I understand it correctly, the issue is caused during the compilation of the Swift code. Is the Swift 5.9 release only compilable with Xcode 14? Do you happen to have insight with this?

The issue is caused by versions (checked out commits) of SwiftPM dependencies (specifically `swift-certificates`, most likely at 1.0.x) on your machine not matching the version expected by SwiftPM (`swift-certificates` [0.4.1 up to next minor](https://github.com/apple/swift-package-manager/blob/2dbd2ee3c87999a1d553d12dc065715b4111ac6b/Package.swift#L757)). Xcode version is not relevant here as long as you're not using something too old, like Xcode 13 or older.

If you build SwiftPM with `swift build`, that will check out correct versions of dependencies for you for this tag, unlike `update-checkout`, which can't do that, due to the reasons I've explained upthread.

**Comment by thekief** [comment]
I was able to build release/5.9.0 and the issue does not occure anymore. Thank you for your help.
