### ISSUE TITLE
Image asset "unassigned" issue

### ISSUE THREAD

**Issue by jaesung-0o0** [apple/swift-package-manager#6981]
### Description

I'm not sure whether the issue is from Xcode side or SPM side.

If there's any image that uses other characters, not English, I always face the image-unassigned issue whenever I clone or pull a branch of my Swift package repository.

### Expected behavior

It should be built fine even if the image uses other language characters.

![Screenshot](https://user-images.githubusercontent.com/53814741/273562652-1a904abb-2687-4f76-bf00-1c4908e12861.png)

### Actual behavior

I always face the issues saying:
1. The file "{IMAGE.FILE.NAME}" for the image set "{IMAGE.SET.NAME}" does not exist.
2. The image set "{IMAGE.SET.NAME}" has 3 unassigned children

### Steps to reproduce

1. Create a new Swift package and add resource to the target.
2. Create an image set and assign image files that use other language characters for their names.
3. Push to remote.
4. Clone the repository with a new path.
5. Build.

### Swift Package Manager version/commit hash

0.6.0

### Swift & OS version (output of `swift --version ; uname -a`)

- Xcode15, Swift 5.9 (`swift --version` output)
- Swift Package compiler version is set to `5.7.1`

**Comment by neonichu** [comment]
Sounds like an issue with asset catalog handling itself which is part of Xcode. Please file this through http://feedbackassistant.apple.com instead.
