### ISSUE TITLE
Unable To Copy Files Outside Of Target Source Folder

### ISSUE THREAD

**Issue by brianmichel** [apple/swift-package-manager#6982]
### Description

When constructing a package which may have targets which rely on vendored files (say a `.lib` or `.h` created by an external build system) it would be reasonable to create some kind of `vendor` folder at the root of the package and then use the `.copy` command to specify which resources need to be pulled into which targets, something similar to the following:
![CleanShot 2023-10-09 at 17 32 29@2x](https://github.com/apple/swift-package-manager/assets/63919/6d7fa93b-387e-4d1b-b02b-1fcbc1fcc8f2)

In this setup Swift PM silently fails to copy files within the package root but outside of the target's source folder.

### Expected behavior

I would expect the files to be copied into a bundle under the `.build` folder which does happen successfully if you `.copy` a file within the target's source folder. This would allow people to construct arbitrary bundles that help meet the needs of the software they are building.

### Actual behavior

Swift PM silently fails to copy any files referenced that are outside of the target's source folder.

### Steps to reproduce

1. Run `swift build` on the sample project attached
2. Open up the `.build/debug` folder
3. Look at the contents of `TestCopy_App.bundle` 

Notice there is only 1 file there, while 3 valid file paths have been specified in the Package file.

[TestCopy.zip](https://github.com/apple/swift-package-manager/files/12850799/TestCopy.zip)

### Swift & OS version (output of `swift --version ; uname -a`)

Target: arm64-apple-macosx14.0
Darwin zerocool.localdomain 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

This also happens on the latest Swift on Windows toolchain as well.

**Comment by neonichu** [comment]
This easily reproduces and looking at `TargetSourcesBuilder` also easily explains why: the process is based on looking at the files inside a target and applying the rules to them. Rules which don't match files in the target, but are technically valid (point to an existing file inside the package), are simply never considered.

Looking at [SE-0271](https://github.com/apple/swift-evolution/blob/main/proposals/0271-package-manager-resources.md), it's not 100% clear to me whether this was intended, it feels as if there should at least be diagnostics about the unapplied rules. The proposal talks about files in targets, so I think the implication is that it is correct that this doesn't work, but it doesn't seem right that it happens silently.

**Comment by brianmichel** [comment]
Yeah I think it should at least break, however I think the other behavior is desirable. 

I can see maybe why you wouldn't want to package files from _anywhere_, but I feel like any file in the package should be fair game imo.

**Comment by neonichu** [comment]
> I can see maybe why you wouldn't want to package files from anywhere, but I feel like any file in the package should be fair game imo.

Yah, I tend to agree, was just trying to extrapolate what the behavior most matches the original design.

**Comment by brianmichel** [comment]
> > I can see maybe why you wouldn't want to package files from anywhere, but I feel like any file in the package should be fair game imo.
> 
> Yah, I tend to agree, was just trying to extrapolate what behavior most matches the original design.

Totally! I was re-reading the originally SE and saw this line which potentially supports the idea of anything being copy-able within the package, but the original authors would probably have to clarify:

> Letting package authors put resources where they like in their source directories (to allow functional organization of large code bases).

**Comment by neonichu** [comment]
see also rdar://119040426

**Comment by brianmichel** [comment]
Niceee, thanks @neonichu!
