### ISSUE TITLE
Auto Generated *PackageDiscoveredTest Is Incompatible With C++ Interop

### ISSUE THREAD

**Issue by brianmichel** [apple/swift-package-manager#6990]
### Description

When building a SwiftPM package that includes a test target which triggers automatic this function https://github.com/apple/swift-package-manager/blob/9854e40a1fe2319b11ce91ce6eddea7b5bb179fd/Sources/Build/BuildPlan/BuildPlan%2BTest.swift#L68C18-L68C42 you can end up in a situation where the generated target is not compiled with C++ interop enabled, which then leads to the following compilation error:

```
[3/13] Emitting module ArcPackageDiscoveredTests
<unknown>:0: error: module 'Cxx' was built with C++ interoperability enabled, but current compilation does not enable C++ interoperability
<unknown>:0: note: visit https://www.swift.org/documentation/cxx-interop/project-build-setup to learn how to enable C++ interoperability
C:\Users\brian\AppData\Local\Programs\Swift\Platforms\0.0.0\Windows.platform\Developer\SDKs\Windows.sdk\usr\share\vcruntime.modulemap:120:8: error: module 'std' requires feature 'cplusplus'
module std [system] {
```

While I have discovered this issue on Windows, reading the SPM code I'm not sure it's Windows specific.

### Expected behavior

I would expected any autogenerated code to respect / understand the interoperability mode specified within the `Package.swift` file.

### Actual behavior

It seems that the interoperability flag is _not_ respected and whatever the `*PackageDiscoveredTests` target is is built without interoperability concerns and no way to override the default.

### Steps to reproduce

Test repo here https://github.com/brianmichel/spm-cxx-interop-autogenerated-entrypoint

### Swift & OS version (output of `swift --version ; uname -a`)

compnerd.org Swift version 5.11-dev (LLVM 1cf95e7e61a3714, Swift bf45c55530acd2a)
Windows 11

**Comment by compnerd** [comment]
CC: @hyp @egorzhdan @neonichu

**Comment by brianmichel** [comment]
I've added a test project that demonstrates the problem.

**Comment by neonichu** [comment]
I forgot how the virality of C++ interoperability works, hopefully it is sufficient to just compile the test discovery target with it and we don't need to also compile all other test targets with it since we do end up linking all test targets into a singular executable.

**Comment by brianmichel** [comment]
I just tested and this also seems to be broken in the same way on Linux.

## Setup
1. Follow the instructions at https://www.swift.org/install/linux/ to get a Swift on Linux container
2. run `git clone https://github.com/brianmichel/spm-cxx-interop-autogenerated-entrypoint.git`
3. cd into `spm-cxx-interop-autogenerated-entrypoint`
4. Run `swift build --build-tests`

## Expected Result
The build should compile successfully

## Actual Result
Compilation errors are shown that are unfixable by the end user.

```
root@d7f04fb870a4:/spm-cxx-interop-autogenerated-entrypoint# swift build
Building for debugging...
[4/4] Compiling spm_cxx_interop_autogenerated_entrypoint spm_cxx_interop_autogenerated_entrypoint.swift
Build complete! (1.47s)
root@d7f04fb870a4:/spm-cxx-interop-autogenerated-entrypoint# swift build --build-tests
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/spm-cxx-interop-autogenerated-entrypoint/.build/aarch64-unknown-linux-gnu/debug/spm-cxx-interop-autogenerated-entrypointPackageDiscoveredTests.derived/spm-cxx-interop-autogenerated-entrypointTests.swift:2:18: error: module 'spm_cxx_interop_autogenerated_entrypointTests' was built with C++ interoperability enabled, but current compilation does not enable C++ interoperability
@testable import spm_cxx_interop_autogenerated_entrypointTests
                 ^
/spm-cxx-interop-autogenerated-entrypoint/.build/aarch64-unknown-linux-gnu/debug/spm-cxx-interop-autogenerated-entrypointPackageDiscoveredTests.derived/spm-cxx-interop-autogenerated-entrypointTests.swift:2:18: note: visit https://www.swift.org/documentation/cxx-interop/project-build-setup to learn how to enable C++ interoperability
@testable import spm_cxx_interop_autogenerated_entrypointTests
                 ^
/spm-cxx-interop-autogenerated-entrypoint/.build/aarch64-unknown-linux-gnu/debug/spm-cxx-interop-autogenerated-entrypointPackageDiscoveredTests.derived/spm-cxx-interop-autogenerated-entrypointTests.swift:2:18: error: module 'spm_cxx_interop_autogenerated_entrypointTests' was built with C++ interoperability enabled, but current compilation does not enable C++ interoperability
@testable import spm_cxx_interop_autogenerated_entrypointTests
                 ^
/spm-cxx-interop-autogenerated-entrypoint/.build/aarch64-unknown-linux-gnu/debug/spm-cxx-interop-autogenerated-entrypointPackageDiscoveredTests.derived/spm-cxx-interop-autogenerated-entrypointTests.swift:2:18: note: visit https://www.swift.org/documentation/cxx-interop/project-build-setup to learn how to enable C++ interoperability
@testable import spm_cxx_interop_autogenerated_entrypointTests
                 ^
/spm-cxx-interop-autogenerated-entrypoint/.build/aarch64-unknown-linux-gnu/debug/spm-cxx-interop-autogenerated-entrypointPackageDiscoveredTests.derived/spm-cxx-interop-autogenerated-entrypointTests.swift:2:18: error: module 'spm_cxx_interop_autogenerated_entrypointTests' was built with C++ interoperability enabled, but current compilation does not enable C++ interoperability
@testable import spm_cxx_interop_autogenerated_entrypointTests
                 ^
/spm-cxx-interop-autogenerated-entrypoint/.build/aarch64-unknown-linux-gnu/debug/spm-cxx-interop-autogenerated-entrypointPackageDiscoveredTests.derived/spm-cxx-interop-autogenerated-entrypointTests.swift:2:18: note: visit https://www.swift.org/documentation/cxx-interop/project-build-setup to learn how to enable C++ interoperability
@testable import spm_cxx_interop_autogenerated_entrypointTests
                 ^
error: fatalError
```

**Comment by neonichu** [comment]
Makes sense that it works fine on macOS, we have a different way to do test discovery there which doesn't involve building a separate target. 

We unfortunately don't have a way to influence how the generated target gets build (maybe we should), so there's no way to influence it from the package manifest to try workarounds. That said, maybe passing `-Xswiftc -cxx-interoperability-mode=default` does something.

**Comment by brianmichel** [comment]
> Makes sense that it works fine on macOS, we have a different way to do test discovery there which doesn't involve building a separate target.
> 
> We unfortunately don't have a way to influence how the generated target gets build (maybe we should), so there's no way to influence it from the package manifest to try workarounds. That said, maybe passing `-Xswiftc -cxx-interoperability-mode=default` to `swift build` does something.

It looks like adding this flag gets us a little bit further (and then we run into a dep that wasn't designed to compile with C++ interop that needs to be fixed). Does this mean that the entire package is now compiled with interop on? This seems like a big hammer if so...
