### ISSUE TITLE
Bundle.module is not generated if Resources only has xcstrings file

### ISSUE THREAD

**Issue by bolsinga** [apple/swift-package-manager#6993]
### Description

I converted my Package to use xcstrings. That is my only Resource. When building with `swift build` the helpful `Bundle.module` property is not created, and my build fails. Somehow when I open the Package.swift in Xcode 15, it will build OK.

Here is the PR that demonstrates the problem. https://github.com/bolsinga/site/pull/685 I have also filed FB13261704

### Expected behavior

I expect a Package with only a .xcstrings resource to generate the Bundle.module accessor.

### Actual behavior

It seems Bundle.module is not generated when there is only a xcstrings file in the Resources directory.

### Steps to reproduce

See FB13261704 and https://github.com/bolsinga/site/pull/685

### Swift Package Manager version/commit hash

stock install

### Swift & OS version (output of `swift --version ; uname -a`)

neu:site bolsinga$ swift --version && uname -a
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
Darwin neu.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

**Comment by bolsinga** [comment]
If you look at the diff, it used to have `Sources/Site/Resources/en.lproj`, but now it just has `Sources/Site/Resources`. The .xcstrings file has "en" embedded within it. The Xcode 15.0 conversion tool moves it to this location. 

https://github.com/apple/swift-package-manager/blame/9854e40a1fe2319b11ce91ce6eddea7b5bb179fd/Sources/PackageModel/Resource.swift#L17 seems to be looking for the lproj however.

**Comment by bolsinga** [comment]
Yes! If I add: `Sources/Site/Resources/en.lproj/fake` `swift build` will succeed. See the updated change in my PR.

**Comment by neonichu** [comment]
This seems expected to me, SwiftPM's build system does not support .xcstrings files, only Xcode does. 

I also see the expected warning when building your package:

```
warning: 'site': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/neonacho/Desktop/site/Sources/Site/Resources/Localizable.xcstrings
```

Since we end up with zero resources, `Bundle.module` is not generated.

**Comment by bolsinga** [comment]
OK. However, SwiftPM's build system supported .strings in this manner, and when I used Xcode to convert to .xcstrings, SPM failed to build. Therefore it's possible to create a Package in Xcode 15. that will not build with `swift build`. Is that expected behavior? It was not the behavior previously.

There is a workaround, so it seems fine to close, but it results in a different outcome than expected.

Thank you.

**Comment by bolsinga** [comment]
Is https://github.com/apple/swift-package-manager/pull/2704 related?

**Comment by neonichu** [comment]
I could see that Xcode should probably not convert .strings to .xcstrings if they are in a package until these files are supported by SwiftPM's build system? Or at least warn the user? I agree that it isn't ideal that we don't have support for .xcstrings in SwiftPM.
