### ISSUE TITLE
Is it possible to specify capabilities and keychain access-sharing in Package.swift

### ISSUE THREAD

**Issue by thisisaaronland** [apple/swift-package-manager#7032]
### Description

Is it possible to specify capabilities and keychain access-sharing flags in a `Package.swift` file?

Based on my reading of the documentation these are both things configured in XCode but none of those configuration options appear available in XCode for projects create with `swift package init`.

Maybe I am just misunderstanding where those options are found for these kinds of projects?

Thanks,

**Comment by neonichu** [comment]
It is not currently possible to configure capabilities or entitlements in a Swift package. I believe typically people configure these in the ultimate app that they are building and packages just document that a certain capability is required to use their library.

**Comment by thisisaaronland** [comment]
Okay, thanks.
