### ISSUE TITLE
Running `swift test` with 0 tests should create empty xunit results file

### ISSUE THREAD

**Issue by jozefizso** [apple/swift-package-manager#7065]
### Description

Create a new Swift package with 0 tests. Configure the test target so `swift test` can run.

Running `swift test` with 0 tests results in this output:

```
$ swift test
Building for debugging...
[1/1] Linking AppcastPackageTests
Build complete! (3.88s)
Test Suite 'All tests' started at 2023-11-08 15:23:10.174.
Test Suite 'All tests' passed at 2023-11-08 15:23:10.175.
         Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
```

Running `swift test --parallel --xunit-output empty.xml` to create results file in this case will not create the file:

```shell
$ swift test --parallel --xunit-output empty.xml  
Building for debugging...
Build complete! (0.12s)
warning: No matching test cases were run

$ ls empty.xml
ls: empty.xml: No such file or directory
```

### Expected behavior

When results file is requests and 0 tests are run (either the project does not have any tests or the filter does not match any test) the xunit result file should be created with information about 0 tests run.

Empty results file may look like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="AcmeLibraryTests" tests="0" failures="0" errors="0" time="0.001">
</testsuites>
```

Creating empty results file will ensure we don't have to check for missing file in our build pipeline which processes test results.

### Actual behavior

No results file is create.

### Swift Package Manager version/commit hash

swift 5.9

### Swift & OS version (output of `swift --version ; uname -a`)

```
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
```
```
Darwin PC 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64
```

**Comment by grynspan** [comment]
I'm touching relevant code right now, so I'll take a look at this.
