### ISSUE TITLE
linker/compiler errors are silently consumed and don't appear in stdout or stderr

### ISSUE THREAD

**Issue by compnerd** [apple/swift-package-manager#7114]
### Description

Some recent work that @neonichu (or @tomerd?) did to silence some output seems to have resulted in linker errors being silently dropped making it difficult to identify build failures.

### Expected behavior

Linker errors should be presented to the user.

### Steps to reproduce

`swift build` a project that has undefined references.

### Swift & OS version (output of `swift --version ; uname -a`)

Windows 11

**Comment by compnerd** [comment]
@al45tair I just happened to run into that same thing on Windows!

**Comment by neonichu** [comment]
Seems like we should revert https://github.com/apple/swift-package-manager/pull/7078 -- we'll need a broader change to address the issue with code-signing output.
