### ISSUE TITLE
Failed to resolve two dependencies with the same repository name 

### ISSUE THREAD

**Issue by kapitoshka438** [apple/swift-package-manager#7129]
### Description

It's impossible to add two different Swift packages which have equal repository names on GitHub. It causes packages names conflict even if the dependencies have different product names.
```
// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "SPMIssueTest",
    platforms: [
        .macOS(.v10_13),
        .iOS(.v12),
    ],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "SPMIssueTest",
            targets: ["SPMIssueTest"]),
    ],
    dependencies: [
        .package(url: "git@github.com:inappstory/ios-sdk.git", exact: Version("1.22.5")),
        .package(url: "git@github.com:mindbox-cloud/ios-sdk.git", exact: Version("2.8.0"))
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "SPMIssueTest",
            dependencies: [
            //    .product(name: "InAppStorySDK", package: "ios-sdk"),
                .product(name: "Mindbox", package: "ios-sdk")
            ]),
    ]
)
```

### Expected behavior

Package developers may not be aware of another packages and their repository names. Swift Package Manager should allow equal package names and identify dependencies by any other criteria but not by the repository name. Or maybe allow aliasing when adding dependencies like this way: `package(url: , exact: , packageNameAlias:)`.

### Actual behavior

`Failed to resolve dependencies Dependencies could not be resolved because root depends on 'ios-sdk' 1.22.5 and root depends on 'ios-sdk' 2.8.0.`

### Swift Package Manager version/commit hash

swift-tools-version: 5.9

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

**Comment by kapitoshka438** [comment]
> This behaves correctly, the repository name is used as the identity of packages.

So you mean every package developer in the world has to worry about all other repositories to avoid exact names? Let's say I want to create a library with my custom collection types, call it "MyAwesomeCollections" and put it to my repo to a URL like https://github.com/kapitoshka438/swift-collections. And all developers who are using https://github.com/apple/swift-collections in their projects won't be able to import my package?
I don't think this is a good behaviour. Please consider another way to identify packages, maybe taking into account the organization name.

**Comment by thekoc** [comment]
> This behaves correctly, the repository name is used as the identity of packages.

Shouldn't the identity to be username combined with the repository? Or at least the the user should be able to specify an alias?

**Comment by coenttb** [comment]
I would like to indicate that this is a rather large issue for me, because I have two organizations that have packages with the same name. In my use case, it makes semantic sense to have both have the same name.

**Comment by garygrace** [comment]
Just encountered this issue with these two repositories:

https://github.com/statsig-io/ios-sdk
https://github.com/spotify/ios-sdk

I'm going to fork the Spotify SDK repository to get around this, but it's far from ideal behaviour.
