### ISSUE TITLE
Allow umbrella headers to share a "root" directory in C++ Interop.

### ISSUE THREAD

**Issue by furby-tm** [apple/swift-package-manager#7185]
### Description

Hello SwiftPM team,

First off, C++ introp included with Swift 5.9 is a major success, after successfully building much of the computer graphics [landscape](https://github.com/wabiverse/MetaverseKit) in the pursuit of building Pixar's USD for the Swift programming language with the [**SwiftUSD**](https://github.com/wabiverse/SwiftUSD) project.

This is a project I'd like to tie into the official [**OpenUSD**](https://github.com/PixarAnimationStudios/OpenUSD) project, however, due to the existing directory structure of **OpenUSD**, SwiftPM imposes the restructuring of the entire project as you can see in the **SwiftUSD** project.

The reason this restructuring is necessary is due to the rule that all Swift target headers must not be visible to other Swift targets with the `publicHeadersPath` field. However, I believe that even if a shared "root" include path is used, we can still uniquely identify the paths to each target's respective "contextual headers" within a shared "root" include path.

Is there any possibility of adding more flexibility to how **SwiftPM** accepts these headers, one that would allow for the directory structure of **OpenUSD** as well as other project directory structures as seen across the [**ASWF landscape**](https://landscape.aswf.io) - I believe with this feature we can see rapid (or, shall I say *swift* 😉) adoption of both the Swift programming language, and the power of **SwiftPM** across the industry.

Thank you,

Tyler Furby

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
Darwin wabitwo.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:27:54 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T6000 arm64

**Comment by neonichu** [comment]
Do you have a more concrete (ideally smaller) example of which header structure currently doesn't work?

**Comment by furby-tm** [comment]
> Do you have a more concrete (ideally smaller) example of which header structure currently doesn't work?

Sure, I will provide a simple example repository with a `Package.swift`, to replicate that Swift targets are not allowed to have a shared include directory visible to other swift targets.

**Comment by furby-tm** [comment]
@neonichu Here is an example repository, when running `swift build`, the following error message says the following:

```swift
error: 'helloswiftpm': target 'HelloSwiftPM' has invalid header layout: umbrella header found at '/Users/furby/Wabi/HelloSwiftPM/HelloSwiftPM/HelloSwiftPM.h', but directories exist next to it: /Users/furby/Wabi/HelloSwiftPM/HelloSwiftPM/SayHello, /Users/furby/Wabi/HelloSwiftPM/HelloSwiftPM/SayHelloAgain; consider removing them
error: 'helloswiftpm': target 'SayHello' has overlapping sources: /Users/furby/Wabi/HelloSwiftPM/HelloSwiftPM/SayHello/SayHello.cpp
error: 'helloswiftpm': target 'HelloSwiftPM' has invalid header layout: umbrella header found at '/Users/furby/Wabi/HelloSwiftPM/HelloSwiftPM/HelloSwiftPM.h', but directories exist next to it: /Users/furby/Wabi/HelloSwiftPM/HelloSwiftPM/SayHello, /Users/furby/Wabi/HelloSwiftPM/HelloSwiftPM/SayHelloAgain; consider removing them
error: 'helloswiftpm': target 'SayHello' has overlapping sources: /Users/furby/Wabi/HelloSwiftPM/HelloSwiftPM/SayHello/SayHello.cpp
```

**Comment by furby-tm** [comment]
Would you be able to show me a `module.modulemap` file that would work for this example? When I set it up I receive an error that `'helloswiftpm': target 'SayHello'` has overlapping sources

**Comment by furby-tm** [comment]
I have updated the module maps with the closest I was able to get it compiles just fine and it runs, however, I am unable to refer back to the root include directory of `HelloSwiftPM` for the other C++ target, as the paths must all be stripped down to their own respective modules.

**Comment by furby-tm** [comment]
Here is that revision:

@neonichu https://github.com/furby-tm/HelloSwiftPM/commit/e50d8770fdda538bded5c515284d46186a684b72

**Comment by furby-tm** [comment]
As another attempt I was able to get things to work with everything sharing that root prefix, but it feels like more of a hack that requires moving all project directories into a secondary root directory of the same name (and the reason a `module.modulemap` file cannot go in the repository root is because SwiftPM will pick up on the other root level directories such as `.git` and not allow it):

@neonichu 
https://github.com/furby-tm/HelloSwiftPM/commit/bf0b7a890de71f59002ad7eafd64a10130f2e773

**Comment by egorzhdan** [comment]
@furby-tm you could also try to make the USD target a `systemLibrary` in SwiftPM, that would make SwiftPM a bit more relaxed when it comes to the paths of headers.

**Comment by furby-tm** [comment]
@egorzhdan Thanks! I'll take a look at `systemLibrary` as well, I'm awfully close in that last revision though to get exactly what I need, I just need to be able to refer to that top level `HelloSwiftPM` directory without having to create that secondary `HelloSwiftPM` within it, do you think I'm about at the limits with that approach?

Im thinking there's got to be a way that I can slap a `module.modulemap` at the repo root, because that should fix it, but I wasn't sure if you've ever seen or attempted to have a module map at the repositories root before.

**Comment by furby-tm** [comment]
@egorzhdan In perhaps the strangest of ways, I was able to bring the "root include" in by setting one of the libraries path's (with it's public headers directory) to the root of the swift package repo, now when other targets depend on it - that target includes the root.

It's real ugly! But I think this will work, any possible side effects of doing this?
https://github.com/furby-tm/HelloSwiftPM/commit/081f988f918dce3199b37ac8711064a61b90868f

**Comment by furby-tm** [comment]
Hey folks! I really appreciate your help, currently I am able to build [https://github.com/wabiverse/OpenUSD](**OpenUSD**), no changes from the official repo structuring, and things are building great with this [Swift Package](https://github.com/wabiverse/OpenUSD/blob/release/Package.swift), it required the strange workarounds that I noted above, but I'm just glad to see everything working!

~ Keep up the great work with SwiftPM 🎉

**Comment by furby-tm** [comment]
Quick update with the above workaround, after spending more time with it and messing around with it a bit more, that does not seem to be a suitable fix for large projects with dependencies due to modules getting re-imported and those modules additionally getting re-imported into other dependencies' namespace blocks, sort of turning into a gigantic mess.

It appears all **SwiftPM** is missing here is the ability to support building CXX interop targets without a "project source directory" usually marked by `src`; or in Swift project convention a `Sources` directory. 

For some reason, **SwiftPM** picks up on directories such as `.build` and `.git` at the root of the project repo residing next to a CXX interop target path at the root of the project repo if you attempt to build a CXX interop target with a target configuration of: `path: "."`, complaining that you should "consider reducing the number directories to one".

**Comment by furby-tm** [comment]
Closing in favor of #7413
