### ISSUE TITLE
Providing a scheme for a target

### ISSUE THREAD

**Issue by x-0o0** [apple/swift-package-manager#7217]
### Description

Here's my code example of `Package.swift`:
```swift
  products: [
        .library(
            name: "ExamplePackage",
            targets: ["Module1", "Module2", "Module3"]
        ),
    ],
    targets: [
        .target(
            name: "Module1",
            dependencies: ["Module3"]
        ),
        .target(
          name: "Module2",
          dependencies: ["Module3"]
        ),
        .target(
          name: "Module3"
        ),

        .testTarget(
            name: "Module1Tests",
            dependencies: ["Module1", "Module3"]
        ),
        .testTarget(
            name: "Module2Tests",
            dependencies: ["Module2", "Module3"]
        ),
    ]
```

While Xcode provides the scheme for each defined `testTarget`  (e.g.,`"Module1Tests"`), it doesn't provide the scheme for each defined `target` (e.g., `"Module1"`). It's only able to provide the build schemes for the **products**.

It's weird that the defined target cannot have its own corresponding build scheme on the Xcode. Does the concept of the `target` in `PackageDescription` not equal to a **build target**?
Is there any way to make Xcode to provide the scheme for the defined target on `Package.swift`?

### Expected behavior

Xcode is able to create/manage the schemes for the defined targets

### Actual behavior

There's no provided schemes for the defined targets except for the test targets.

### Steps to reproduce

1. Create a new Swift Package.
2. Copy&Paste the following code to `Package.swift`
```swift
// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "ExamplePackage",
    products: [
        .library(
            name: "ExamplePackage",
            targets: ["Module1", "Module2", "Module3"]
        ),
    ],
    targets: [
        .target(
            name: "Module1",
            dependencies: ["Module3"]
        ),
        .target(
          name: "Module2",
          dependencies: ["Module3"]
        ),
        .target(
          name: "Module3"
        ),
        .testTarget(
            name: "Module1Tests",
            dependencies: ["Module1", "Module3"]
        ),
        .testTarget(
            name: "Module2Tests",
            dependencies: ["Module2", "Module3"]
        ),
    ]
)
```

### Swift Package Manager version/commit hash

0.6.0

### Swift & OS version (output of `swift --version && uname -a`)

Swift 5.9, Xcode15.1, Sonoma 14.0

**Comment by neonichu** [comment]
AFAIK, Xcode only provides schemes for products, but this would be more suitable for https://feedbackassistant.apple.com since this isn't an issue with the SwiftPM open source project.
