### ISSUE TITLE
How do I make SwiftPM output portable?

### ISSUE THREAD

**Issue by wjk** [apple/swift-package-manager#7219]
I am writing a Swift-based application on Linux. My `Package.swift` file builds such that I have four binaries: the app, `libCairoGraphics.so`, `libContentAnimation.so`, and `libAppKid.so`. ([Here are the sources](https://github.com/wjk/AppKid), if you're interested.) If I was to copy these binaries out of the `.build` directory to a different location, everything still works as expected as long as I keep the dependency binaries in the same directory as the main app. However, when I inspect the app with `ldd`, I see references to many different absolute paths pointing into my copy of the Swift compiler. How do I change this so that the Swift libraries used (runtime and standard library) can be copied alongside my app like my three dependencies, and have everything continue to work even if I were to move the Swift compiler install out of its current location? This will be important when it comes time to distribute a Swift-based program. Thanks!

**Comment by MaxDesiatov** [comment]
Hi @wjk, have you tried passing `--static-swift-stdlib` flag to `swift build`? This will link core libraries statically into your executable. Does that resolve your issue?

**Comment by wjk** [comment]
Yep, that worked. I was confused because my build is set up to link one of my dependencies as dynamic libraries, which would seem to make this trick impossible, but I can easily change that so everything is linked statically. Thanks so much!
