### ISSUE TITLE
Xcode 15.1 - not able to add private package dependencies to app project 

### ISSUE THREAD

**Issue by ncharniauski** [apple/swift-package-manager#7237]
### Description

We are hosting Swift package using https://jfrog.com/help/r/jfrog-artifactory-documentation/swift-registry.
Registry is protected and requires authentication.
Swift registry works fine using CLI. 

When I add a dependency to an application project from Xcode UI (File -> Add package dependency)or via this UI:
<img width="1375" alt="Screenshot 2024-01-08 at 7 00 01 PM" src="https://github.com/apple/swift-package-manager/assets/90726135/9a44f6a8-85cf-4f5f-acc5-b7045384ba1a">

Xcode displays error "Authentication failed because the credentials were rejected"

![Screenshot 2024-01-09 at 10 55 14 AM](https://github.com/apple/swift-package-manager/assets/90726135/1bbe5cd3-ca78-4d52-b771-84bb364d891f)

Xcode is able to resolve the same private package dependency just fine if I add dependency to a Swift package project via Package.swift"
![Screenshot 2024-01-09 at 11 28 10 AM](https://github.com/apple/swift-package-manager/assets/90726135/bb7908f1-77b7-4818-bd41-481b46063757)

My registries.json:

```
{
  "authentication" : {
    "example.jfrog.io" : {
      "loginAPIPath" : "/artifactory/api/swift/swift-registry-local",
      "type" : "basic"
    }
  },
  "registries" : {
    "[default]" : {
      "supportsAvailability" : false,
      "url" : "https://example.jfrog.io/artifactory/api/swift/swift-registry-local"
    }
  },
  "version" : 1
}
```

I do have registry credentials stored on keychain. It is just one credentials set. Xcode asks to access registry creds on keychain and I grant the permission.
I tested with both registry authentication types: basic and token. Both types of authentication fail when adding dependency package from Xcode UI.

<img width="1643" alt="Screenshot 2024-01-09 at 11 33 46 AM" src="https://github.com/apple/swift-package-manager/assets/90726135/bf892994-32cb-4dd9-a8ff-f91bcf23017a">

### Expected behavior

Xcode UI should allow adding protected package dependencies to application projects.

### Actual behavior

Xcode displays authentication error when I attempt to add protected package dependency:
![Screenshot 2024-01-09 at 10 55 14 AM](https://github.com/apple/swift-package-manager/assets/90726135/72add22b-3dbd-4aa4-8228-57b3343d28a0)

### Steps to reproduce

1. Install Xcode 15.1
2. Set up SPM registry that requires authentication (such as https://jfrog.com/help/r/jfrog-artifactory-documentation/swift-registry)
3. Setup registry URL by command line:  package-registry set --global "url"
4. Setup registries auth by command line:  package-registry login "url" --username "uname" --password "pwd"
5. Verify registries.json file is created with appropriate authentication type.
6. Verify appropriate Keychain Internet Password is created for registry host URL
7. Open application project in Xcode and go to File->Add Package Dependencies...
8. In the "Add Package" window, in the top right corner input field "Search or Enter Package URL" enter registry URL
9. Xcode displays "Authentication failed because the credentials were missing" window asking to re-enter user name and password
10. Reentering username/password does also fails with authentication error

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: x86_64-apple-macosx13.0
Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:26 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_X86_64 x86_64

**Comment by yim-lee** [comment]
@ncharniauski Thanks for creating this. Have you tried entering the package registry identifier (e.g., `mona.LinkedList`) rather than the Artifactory URL in the search box?

**Comment by ncharniauski** [comment]
yes I did - package is not found.

**Comment by yim-lee** [comment]
Tracking with rdar://120735039

**Comment by ncharniauski** [comment]
> @ncharniauski A couple of things to check/try:
> 
> 1. If you are using user-level `registries.json` (under `~/.swiftpm/configuration/`), please make sure you either don't have `registries.json` in local workspace or the info in it is correct.
> 2. After you type the package registry identifier in the search box, you might need to hit enter to trigger a search. Copy-paste to the search box should also trigger a search.

1. Confirmed - I only have  user-level `registries.json` under `~/.swiftpm/configuration/`
2. Confirmed - typing package id and hitting enter, and copy-paste package id to the search box, both produce 0 packages found result

**Comment by yim-lee** [comment]
I am afraid I am out of idea at the moment. I don't think the issue is Xcode not reading registry credentials from Keychain, because you should have gotten an error rather than 0 packages found.

**Comment by ncharniauski** [comment]
0 packages found is the result of Xcode not being able to connect to my private registry. It couldn't connect, it doesn't know about the package ID i am looking for. This happens only if I am searching for my package by id.

If I enter registry URL into the search box, then I am getting authentication error. Xcode tries to grab credentials from Keychain and authenticate to my registry. This fails and I am getting prompted to enter my username/password as a fallback.

**Comment by yim-lee** [comment]
> If I enter registry URL into the search box, then I am getting authentication error.

When you enter registry URL in the search box it is treated as the Git repo URL, so the authn error results from Xcode/SwiftPM trying to clone it and fails.

**Comment by MaxDesiatov** [comment]
Would you be able to clarify if this issue is reproducible for you with `swift build`, `swift test`, or any other SwiftPM CLI commands?

**Comment by ncharniauski** [comment]
> Could it be this? https://forums.developer.apple.com/forums/thread/729959 I fixed the issue by going to `~/.gitconfig` and removing any reference to entries with `[url "https://github.com/"] insteadOf = ...` or `[url "ssh://git@github.com/"]`
> 
> EDIT: I also have the GitHub account in Xcode, as well as the entry in `~/.netrc`.

Nope. We are not hosting private package on GitHub. It is hosted in Jfrog Swift Registry.

**Comment by ncharniauski** [comment]
> Would you be able to clarify if this issue is reproducible for you with `swift build`, `swift test`, or any other SwiftPM CLI commands?

SwiftPM CLI works just fine. 
Furthermore, Xcode is resolving our private package just fine if package is imported into another package via Package.swift. My test Package lists our private SPM package as dependency on Package.swift. The moment I open the test Package in Xcode, private dependency gets resolved and Package.resolved gets generated.

When I try to add private SPM package dependency to TestApp.xcodeproj via >File>Add Package Dependency> entering Jfrog registry URL in the Search box , this is when Xcode is not able to resolve the package.

What is the difference in how Xcode resolves packages listed on the Package.swift vs via manually resolving through "Add Package Dependency" ?

**Comment by MaxDesiatov** [comment]
Unfortunately, this issue should be closed here then. This repository hosts the open-source SwiftPM project and its CLI, it does not track Xcode-specific issues. Please file anything Xcode-specific at http://feedbackassistant.apple.com.

**Comment by tushar1998** [comment]
@ncharniauski @MaxDesiatov @yim-lee 
I am doing the same stuff but with AWS Code artifacts, there is docs to run a command called `aws codeartifacts login` which should create a .swiftpm directory in root with registry configurations. This works for with Package.swift create keychain and all everything is perfect but not with .xcodeproj

But when I try to Add package from File -> Add Pacakge Dependencies and url in search bar it says repository cannot be accessed, followed the docs same 0 pacakges found everytime

So I wanna know is this issue with Xcode?

**Comment by tushar1998** [comment]
Okay, I dont know whether this is a bug or not. I tried putting this code snippet in user-level registries.json
```json
// ~/.swiftpm/configurations/registries.json
{
  "authentication" : {
    "example.jfrog.io" : {
      "loginAPIPath" : "/artifactory/api/swift/swift-registry-local",
      "type" : "basic"
    }
  },
  "registries" : {
    "[default]" : {
      "supportsAvailability" : false,
      "url" : "https://example.jfrog.io/artifactory/api/swift/swift-registry-local"
    }
  },
  "version" : 1
}
```

and then quit xcode and reopen again and try to add package from Xcode UI it works perfectly 🎉

**Comment by gurelkaynak** [comment]
I solved the same problem, took me a while. @ncharniauski your keychain setup is probably wrong as far as I can see from you screenshot. "Where" should be the url to the swift repository like this: 

<img width="528" alt="Screenshot 2024-07-11 at 18 02 48" src="https://github.com/swiftlang/swift-package-manager/assets/1239895/89e3e06e-d208-436a-9b2f-07f3acbc911d">

I had the same setup as you, then I updated the password entry in the keychain and it worked.

**Comment by hbedekLU** [comment]
Very interested in this topic.
@ncharniauski  where you able to solve this issue ?

@gurelkaynak I did try your solution but I am still not able to retrieve the packages.

The configuration I tried:

1. Setup the swift registry
```swift package-registry set --global "https://example.jfrog.io/artifactory/api/swift/swift-registry-local"```

2. Use the login command to store credential in keychain
```
swift package-registry login https://example.jfrog.io/artifactory/api/swift/swift-registry-local \
    --username myUser \
    --password myToken
```
with **myUser** my artifactory user and  **myToken** the token provided by artifactory with the **set me up** action

Here is the registries.json than I am getting:
```
{
  "authentication" : {
    "example.jfrog.io" : {
      "loginAPIPath" : "/artifactory/api/swift/swift-registry-local",
      "type" : "basic"
    }
  },
  "registries" : {
    "[default]" : {
      "supportsAvailability" : false,
      "url" : "https://example.jfrog.io/artifactory/api/swift/swift-registry-local"
    }
  },
  "version" : 1
}
```

At this point I tried to search for my package in the search bar but not able to get anything.

![Screenshot 2024-07-19 at 13 36 08](https://github.com/user-attachments/assets/6176d424-25b4-4f85-9451-f1c0b894193a)

I tried to put as URL:

- https://example.jfrog.io/artifactory/api/swift/swift-registry-local
- https://example.jfrog.io
- <SCOPE>.<PACKAGE-NAME>

None of these solutions is working.

**Comment by kfa-onewelcome** [comment]
@hbedekLU any success? got the same :)

**Comment by KushalChoudhary14sep** [comment]
@yim-lee I am facing the same issue of authentication failure while adding the swift package hosted in JFROG artifact using the url.

The same is working while trying to run "swift package-registry login" using the same credentials and following message occurs - "Login successful."

Can you please help me to resolve this issue?

**Comment by AlekseyLibin** [comment]
@KushalChoudhary14sep Yes, you are just doing it a bit wrong. Check the article, I've sorted out the problem and explained everything step-by-step very detailed. Hopefully it helps you :)

[https://medium.com/@a_libin01/how-to-add-a-swift-package-from-jfrog-artifactory-to-an-xcode-project-058ee0678b64](https://medium.com/@a_libin01/how-to-add-a-swift-package-from-jfrog-artifactory-to-an-xcode-project-058ee0678b64)

**Comment by MattAydin** [comment]
> Very interested in this topic. [@ncharniauski](https://github.com/ncharniauski) where you able to solve this issue ?
> 
> [@gurelkaynak](https://github.com/gurelkaynak) I did try your solution but I am still not able to retrieve the packages.
> 
> The configuration I tried:
> 
> 1. Setup the swift registry
>    `swift package-registry set --global "https://example.jfrog.io/artifactory/api/swift/swift-registry-local"`
> 2. Use the login command to store credential in keychain
> 
> ```
> swift package-registry login https://example.jfrog.io/artifactory/api/swift/swift-registry-local \
>     --username myUser \
>     --password myToken
> ```
> 
> with **myUser** my artifactory user and **myToken** the token provided by artifactory with the **set me up** action
> 
> Here is the registries.json than I am getting:
> 
> ```
> {
>   "authentication" : {
>     "example.jfrog.io" : {
>       "loginAPIPath" : "/artifactory/api/swift/swift-registry-local",
>       "type" : "basic"
>     }
>   },
>   "registries" : {
>     "[default]" : {
>       "supportsAvailability" : false,
>       "url" : "https://example.jfrog.io/artifactory/api/swift/swift-registry-local"
>     }
>   },
>   "version" : 1
> }
> ```
> 
> At this point I tried to search for my package in the search bar but not able to get anything.
> 
> ![Screenshot 2024-07-19 at 13 36 08](https://github.com/user-attachments/assets/6176d424-25b4-4f85-9451-f1c0b894193a)
> 
> I tried to put as URL:
> 
> * https://example.jfrog.io/artifactory/api/swift/swift-registry-local
> * https://example.jfrog.io
> * .
> 
> None of these solutions is working.

Try using the id and name of the package you've published in the registry.
