### ISSUE TITLE
Bogus duplicate dependency error

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-package-manager#7243]
### Description

dependency on 'https://github.com/apple/swift-docc-plugin.git' conflicts with dependency on 'https://github.com/apple/swift-docc-plugin.git' which has the same identity 'swift-docc-plugin'

https://github.com/hylo-lang/Lotsawa/actions/runs/7483973548/job/20370062536#step:7:54

### Expected behavior

None of that.

### Actual behavior

That.

### Steps to reproduce

1. Check out https://github.com/hylo-lang/Lotsawa at the spm-dup-identity-bug tag.
2. cd into the resulting directory
3. 
  ```
export LOTSAWA_ENABLE_DOC_GENERATION=1
mkdir -p _site/docc
  swift package --allow-writing-to-directory ./_site \
  generate-documentation \
  --product Lotsawa \
  --output-path _site/docc \
  --experimental-documentation-coverage --level detailed \
  --enable-inherited-docs \
  --transform-for-static-hosting \
  --hosting-base-path "Lotsaws/docc/Lotsawa" \
  --source-service github \
  --source-service-base-url "https://github.com/hylo-lang/Lotsawa/blob/main" \
  --checkout-path "$(pwd)"
  ```

### Swift Package Manager version/commit hash

Swift 5.9.0

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
Darwin DaveA-MBP16.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

**Comment by dabrahams** [comment]
PEBKAC!!!

**Comment by rauhul** [comment]
Out of curiosity, what was the user error?

**Comment by rauhul** [comment]
Hmm yeah that is a nasty gotcha, it would be really nice/cool if the dependency declaration source location could be tracked and included in diagnostics. I think that would have helped debug your issue much quicker. e.g.

```
/foo/bar/Package.swift:30:10: error: dependency on 'https://github.com/apple/swift-docc-plugin.git' conflicts with dependency on 'https://github.com/apple/swift-docc-plugin.git' which has the same identity 'swift-docc-plugin'

/foo/bar/Package.swift:40:11: note: conflicting dependency on  'https://github.com/apple/swift-docc-plugin.git' here
```
