### ISSUE TITLE
error: unable to open dependencies file

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-package-manager#7274]
### Description

- `swift package init --type executable`
- add `swiftSettings: [.unsafeFlags(["-no-whole-module-optimization"])]` to the executable target
- `swift build -c release`

### Expected behavior

build completes successfully

### Actual behavior

> error: unable to open dependencies file (/private/tmp/x/.build/arm64-apple-macosx/release/x.build/x.d)

### Steps to reproduce

See description

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.9.0

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
Darwin DaveA-MBP14-5.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

**Comment by owenv** [comment]
When -no-whole-module-optimization is injected through the unsafeFlags mechanism, it breaks the build system's ability to track build outputs correctly, in this case the make-style dependencies file which is handled differently in batch mode. I would consider this to be expected behavior that perhaps could be diagnosed better.

**Comment by dabrahams** [comment]
Then is it intended that there shall be no way to disable WMO when using SPM? 
A bug in WMO is currently breaking my project as far as I can tell.

**Comment by dabrahams** [comment]
It's obvious that this doesn't _need_ to not work, since disabling WMO works once the dependency files have been generated by a regular WMO build.

**Comment by MaxDesiatov** [comment]
The main point is that we can't guarantee that certain behavior holds with `unsafeFlags`, we're calling them unsafe for precisely that reason, use at your own risk.

**Comment by dabrahams** [comment]
I understand your point.  Please answer my question:

> is it intended that there shall be no way to disable WMO when using SPM?

If not, please repurpose this issue to have a safe way to do it.
If so, please tell me how I'm supposed to deal with the fact that a WMO bug is breaking my project.

Thank you.

**Comment by MaxDesiatov** [comment]
I don't think I can help much with this, WMO is not something that SwiftPM itself implements, it's a compiler feature. I feel like this belongs to https://github.com/apple/swift/issues instead.

**Comment by dabrahams** [comment]
"Does SPM intend to support feature X of the compiler?" sure sounds like an SPM question to me.  The compiler people will just tell me they don't have any say over what features SPM supports, won't they?

**Comment by MaxDesiatov** [comment]
Of course they do. In fact, SwiftPM automatically gets new features exposed via [`.enableUpcomingFeatures`](https://developer.apple.com/documentation/packagedescription/swiftsetting/enableupcomingfeature(_:_:)/).

**Comment by MaxDesiatov** [comment]
Closing as superseded by https://github.com/apple/swift/issues/70995.
