### ISSUE TITLE
When using the same target in different products, the SwiftUI previews break

### ISSUE THREAD

**Issue by Juantri94** [apple/swift-package-manager#7323]
### Description

Problem:
SwiftUI previews break when a target is used in two different products. 

Project description:
In the attached project, we have multiple targets defined on the package and 2 products:
- FeaturesLibraries: contains all targets
- FeatureA: contains just one target (FeatureA)

### Expected behavior

When I change from FeatureA scheme into FeaturesLibraries scheme, SwiftUI preview should work

### Actual behavior

When I select FeaturesLibraries product (that contains all the targets), the previews does not work

### Steps to reproduce

1. Open the FeaturesLibraries.zip project attached.
2. Select FeatureA scheme
3. Open FeatureASwiftUIView.swift file
4. Open canvas for visualising the SwiftUI preview
5. Wait until preview works
6. Select FeaturesLibraries scheme
7. Wait until preview works <- FAIL

[FeaturesLibraries.zip](https://github.com/apple/swift-package-manager/files/14181756/FeaturesLibraries.zip)

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.9.0

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

**Comment by MaxDesiatov** [comment]
Hi @Juantri94, thank you for reporting this issue. This repository tracks the development of the open-source SwiftPM project and is not related to close-source products like Xcode or SwiftUI. For any issues related to closed-source software developed by Apple you should be using http://feedbackassistant.apple.com instead.

**Comment by gyulavoros** [comment]
@Juantri94 were you able to resolve this since then? I'm struggling with the same issue.

**Comment by Juantri94** [comment]
> @Juantri94 were you able to resolve this since then? I'm struggling with the same issue.

Hey @gyulavoros ! No, sorry :(
