### ISSUE TITLE
-parse-as-library not added as expected (on Windows)

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-package-manager#7410]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI.

### Description

Effectively reopens #6644 

### Expected behavior

`swift test` builds and tests the code

### Actual behavior

```
[50/59] Emitting module GenerateSwiftXCTestMain
D:\a\GenerateSwiftXCTestMain\GenerateSwiftXCTestMain\Sources\GenerateSwiftXCTestMain.swift:10:1: error: 'main' attribute cannot be used in a module that contains top-level code

@main
```

### Steps to reproduce

1. Check out the `windows-parse-as-library-bug` tag of https://github.com/hylo-lang/GenerateXCTestMain
2. `swift test`

This was reproduced in GitHub CI; full log archive [attached](https://github.com/apple/swift-package-manager/files/14653446/logs_21885188819.zip).  If you can't reproduce locally, fork the GH project and trigger CI there.

### Swift Package Manager version/commit hash

5.9

### Swift & OS version (output of `swift --version ; uname -a`)

5.9

**Comment by MaxDesiatov** [comment]
This was fixed in https://github.com/apple/swift-package-manager/pull/7322 that should be in [latest development snapshots](https://www.swift.org/download/#trunk-development-main) (`swift-DEVELOPMENT-SNAPSHOT-2024-02-07-a` or later).

**Comment by dabrahams** [comment]
@MaxDesiatov Are you certain?  Running `git config --global core.eol lf` before the checkout action runs doesn't change the results.
