### ISSUE TITLE
package-registry login has empty token

### ISSUE THREAD

**Issue by pwallrich** [apple/swift-package-manager#7453]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI.

### Description

When executing `swift package-registry login` it asks for a token but fails to retrieve it properly.

 Screenshot from mitm proxy of the request:
<img width="571" alt="Screenshot 2024-04-11 at 21 21 26" src="https://github.com/apple/swift-package-manager/assets/13999931/429c978f-51ce-42ae-8aa6-3b6b7707bba4">

I've checked the code a bit and it only happens on release builds. When spm is built with debug config it doesn't happen.

The issue seems to be related to `readpassphrase` inside PackageRegistryCommand+Auth.swift. Somehow the buffer and passwordPtr aren't valid anymore, when the string is created.

I also already fixed it locally and will submit a PR soon (not sure, if it's the best solution).

### Expected behavior

It should get the token from the cli and use it for authentication

<img width="563" alt="Screenshot 2024-04-11 at 21 26 59" src="https://github.com/apple/swift-package-manager/assets/13999931/887e2134-21e8-490f-861b-016337259f23">

### Actual behavior

It uses an empty string instead of the password. 

I assume because of some memory management issues related to `readpassphrase`

### Steps to reproduce

1. Build release version of SPM 5.10 or latest version from main
2. swift package-registry login {url}
3. authentication fails

### Swift Package Manager version/commit hash

SPM 5.10 and latest from main

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

**Comment by BlaiseMuhirwa** [comment]
Was this fixed? I happen to encounter the same problem now.
