### ISSUE TITLE
swift-testing does not build with ToT SwiftPM

### ISSUE THREAD

**Issue by grynspan** [apple/swift-package-manager#7479]
A recent Swift Package Manager change seems to have regressed swift-testing:

https://ci.swift.org/job/pr-swift-testing-macos/633/

**Comment by finagolfin** [comment]
The new swift-foundation does not build either since the April 21 trunk snapshot of the linux toolchain:
```
> ../swift-DEVELOPMENT-SNAPSHOT-2024-04-21-a-ubi9/usr/bin/swift build
error: InternalError(description: "Internal error. Please file a bug at https://github.com/apple/swift-package-manager/issues with this info. unknown target <ResolvedModule: FoundationInternationalizationTests, test, tools>")
```
The prior April 13 trunk snapshot works fine.

@MaxDesiatov, maybe you know what's going on here.

**Comment by grynspan** [comment]
We're now seeing it on Linux too. https://ci.swift.org/job/pr-swift-testing-linux-5.10/683/console

**Comment by stmontgomery** [comment]
Our current _suspicion_ is that this may have been caused by #7353

**Comment by finagolfin** [comment]
I can confirm that reverting #7353 again gets swift-foundation building on linux with the latest April 22 trunk snapshot of the toolchain.
