### ISSUE TITLE
Consider renaming `SWIFT_PM_TEST_LIBRARY` to a more general name like `APPLE_TEST_LIBRARY`

### ISSUE THREAD

**Issue by jakepetroules** [apple/swift-package-manager#7584]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI.

### Description

This env var is convenient for shared libraries which want to have support code that might be run by either an XCTest or SwiftTesting test case.

However, I suggest we name this more generally (for example, `APPLE_TEST_LIBRARY`) because it's not SwifPM-specific, and other build tools / IDEs might want to have a uniform way to identify the Apple-provided testing library in use.

I also expect we _wouldn't_ set this environment variable if SwiftPM gained direct support for additional testing libraries from other platforms/environments, since those would likely be run via their own test harnesses which might define their own environment variables across different IDE integrations.

**Comment by grynspan** [comment]
This flag is meant to be used by SwiftPM and is not related to Apple specifically.
