### ISSUE TITLE
Private SPM Pakages authentication in Xcode CI environment

### ISSUE THREAD

**Issue by tushar1998** [apple/swift-package-manager#7673]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI.

### Description

AWS CodeArtifacts support swift packages. The organization decided to host small in house SDKs on to CodeArtifacts and consume it in our mobile apps, here the development process was smooth I was able to authenticate and use my private package from artifacts registry successfully but on CI environment I am having hiccups

First of all running the below command to set authentication with code artifact registry
```bash
aws codeartifact login --tool swift --domain <domain> --domain-owner <domain-owner> --repository my-repo --namespace namespace --region us-west-2 --profile default
```
This create a keychain access item with name `<domain>-<domain-owner>.d.codeartifact.us-west-2.amazonaws.com` and a configuration file at ~/.swiftpm/configuration/registries.json

Xcode successfull resolves packages with below command and in between asks for a prompt for access keychain I enter the password and it starts fetching the package
```bash
xcodebuild -resolvePackageDependencies
```

My problem here is how to replicate this process in CI environment?? I have tried .netrc solution but it is not picking or even reading the netrc file

Is creating a temporary keychain on CI the right way or there is some other solution ?
Is this current problem related to Xcode or swift??

FYI
- Using Bitrise as CI and Xcode 15.2 with edge updates

### Expected behavior

xcodebuild should resolve pacakge dependencies using the ~/.netrc file if present

### Actual behavior

xcodebuild does not resolve pacakge dependencies using the ~/.netrc file and CI gets stuck for user input according to me

### Swift Package Manager version/commit hash

5.9

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
Darwin Tushars-MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64

**Comment by MaxDesiatov** [comment]
This repository is used exclusively for the open source SwiftPM project. `xcodebuild` is a part of Xcode and is closed source project, bug reports for which are tracked in https://feedbackassistant.apple.com, not here.

**Comment by tushar1998** [comment]
Hey @MaxDesiatov as you work in apple this might have occured somewhere or the other.
I just want to know how private swift packages get authenticated in CI pipelines ?? 

Tried Solutions
- The keychain access does not work properly and ask for password prompts everytime
- netrc file is not read by xcodebuild

**Comment by MaxDesiatov** [comment]
@tushar1998 is the issue reproducible for you when using `swift build` instead of `xcodebuild`?

**Comment by tushar1998** [comment]
I was almost gave up accessing key chains on CI environment, I saw AWS docs once again saw each and every page and steps and found the [solution](https://docs.aws.amazon.com/codeartifact/latest/ug/swift-troubleshooting.html#swift-troubleshooting-ci-machine) here.

The thing I was doing wrong was not giving access to xcodebuild which resides in Xcode application.

Hope this issue can help other people and not waste time
@MaxDesiatov you can close this issue
